// Namespace "ball" (SPEC G-3): the mirror ball, the dark-area bubble and the gap card.
// `<key>.one` is used when vars.n === 1 (every locale defines it, even where it reads the same).
import { defineStrings } from '../../i18n'

export const S = defineStrings('ball', {
  ja: {
    label: 'ミラーボール・点灯{n}面',
    'label.one': 'ミラーボール・点灯{n}面',
    roomLabel: '部屋のボール・今夜の曲{n}面',
    'roomLabel.one': '部屋のボール・今夜の曲{n}面',
    areaTitle: '{tempo} × {genre}',
    areaDark: '{n}曲・まだ暗いエリア',
    'areaDark.one': '{n}曲・まだ暗いエリア',
    areaLit: '{n}曲中{k}面が点灯',
    'areaLit.one': '{n}曲中{k}面が点灯',
    openArea: 'このエリアを開く',
    openAreaShort: 'エリアを開く',
    // gap card front (card-front contract: the area as the title, one short line)
    'gapTitle.fast': 'アップテンポな{genre}',
    'gapTitle.mid': 'ミドルテンポの{genre}',
    'gapTitle.slow': 'スローな{genre}',
    gapNone: 'あなたのボールでは、まだ0曲',
    gapSome: 'あなたのボールでは、まだ{n}曲だけ',
    'gapSome.one': 'あなたのボールでは、まだ{n}曲だけ',
    gapSongs: 'このエリアの曲',
  },
  en: {
    label: 'Mirror ball · {n} faces lit',
    'label.one': 'Mirror ball · {n} face lit',
    roomLabel: 'Room ball · {n} faces tonight',
    'roomLabel.one': 'Room ball · {n} face tonight',
    areaTitle: '{tempo} × {genre}',
    areaDark: '{n} songs · still dark',
    'areaDark.one': '{n} song · still dark',
    areaLit: '{k} of {n} faces lit',
    'areaLit.one': '{k} of {n} face lit',
    openArea: 'Open this area',
    openAreaShort: 'Open area',
    'gapTitle.fast': 'Up-tempo {genre}',
    'gapTitle.mid': 'Mid-tempo {genre}',
    'gapTitle.slow': 'Slow {genre}',
    gapNone: 'None lit on your ball yet',
    gapSome: 'Only {n} songs lit on your ball',
    'gapSome.one': 'Only {n} song lit on your ball',
    gapSongs: 'Songs in this area',
  },
  zhHant: {
    label: '鏡球 · 已點亮{n}面',
    'label.one': '鏡球 · 已點亮{n}面',
    roomLabel: '包廂鏡球 · 今晚{n}面',
    'roomLabel.one': '包廂鏡球 · 今晚{n}面',
    areaTitle: '{tempo} × {genre}',
    areaDark: '{n}首 · 還沒點亮',
    'areaDark.one': '{n}首 · 還沒點亮',
    areaLit: '{n}首中已點亮{k}面',
    'areaLit.one': '{n}首中已點亮{k}面',
    openArea: '打開這個區域',
    openAreaShort: '打開區域',
    'gapTitle.fast': '快節奏的{genre}',
    'gapTitle.mid': '中節奏的{genre}',
    'gapTitle.slow': '慢節奏的{genre}',
    gapNone: '你的鏡球上還沒有一首',
    gapSome: '你的鏡球上只亮了{n}首',
    'gapSome.one': '你的鏡球上只亮了{n}首',
    gapSongs: '這個區域的歌',
  },
  zhHans: {
    label: '镜球 · 已点亮{n}面',
    'label.one': '镜球 · 已点亮{n}面',
    roomLabel: '包厢镜球 · 今晚{n}面',
    'roomLabel.one': '包厢镜球 · 今晚{n}面',
    areaTitle: '{tempo} × {genre}',
    areaDark: '{n}首 · 还没点亮',
    'areaDark.one': '{n}首 · 还没点亮',
    areaLit: '{n}首中已点亮{k}面',
    'areaLit.one': '{n}首中已点亮{k}面',
    openArea: '打开这个区域',
    openAreaShort: '打开区域',
    'gapTitle.fast': '快节奏的{genre}',
    'gapTitle.mid': '中节奏的{genre}',
    'gapTitle.slow': '慢节奏的{genre}',
    gapNone: '你的镜球上还没有一首',
    gapSome: '你的镜球上只亮了{n}首',
    'gapSome.one': '你的镜球上只亮了{n}首',
    gapSongs: '这个区域的歌',
  },
  ko: {
    label: '미러볼 · {n}면 점등',
    'label.one': '미러볼 · {n}면 점등',
    roomLabel: '방의 미러볼 · 오늘 밤 {n}면',
    'roomLabel.one': '방의 미러볼 · 오늘 밤 {n}면',
    areaTitle: '{tempo} × {genre}',
    areaDark: '{n}곡 · 아직 어두운 영역',
    'areaDark.one': '{n}곡 · 아직 어두운 영역',
    areaLit: '{n}곡 중 {k}면 점등',
    'areaLit.one': '{n}곡 중 {k}면 점등',
    openArea: '이 영역 열기',
    openAreaShort: '영역 열기',
    'gapTitle.fast': '빠른 {genre}',
    'gapTitle.mid': '중간 템포 {genre}',
    'gapTitle.slow': '느린 {genre}',
    gapNone: '내 미러볼엔 아직 0곡',
    gapSome: '내 미러볼엔 아직 {n}곡뿐',
    'gapSome.one': '내 미러볼엔 아직 {n}곡뿐',
    gapSongs: '이 영역의 곡',
  },
})
