// Namespace "ball" (SPEC G-3): the mirror ball, the dark-area bubble and the gap card.
import { defineStrings } from '../../i18n'

export const S = defineStrings('ball', {
  ja: {
    label: 'ミラーボール・点灯{n}面',
    roomLabel: '部屋のボール・今夜の曲{n}面',
    areaTitle: '{tempo} × {genre}',
    areaDark: '{n}曲・まだ暗いエリア',
    areaLit: '{n}曲中{k}面が点灯',
    openArea: 'このエリアを開く',
    'region.fast': '北側（アップテンポ）',
    'region.mid': '赤道（ミドル）',
    'region.slow': '南側（スロー）',
    gapHead: 'あなたのボール、{region}×{genre}がまだ暗い',
    gapSongs: 'このエリアの曲',
    gapCount: 'まだ光っていない曲が{n}曲',
  },
  en: {
    label: 'Mirror ball · {n} faces lit',
    roomLabel: 'Room ball · {n} faces tonight',
    areaTitle: '{tempo} × {genre}',
    areaDark: '{n} songs · still dark',
    areaLit: '{k} of {n} faces lit',
    openArea: 'Open this area',
    'region.fast': 'the north (up-tempo)',
    'region.mid': 'the equator (mid-tempo)',
    'region.slow': 'the south (slow)',
    gapHead: 'Your ball: {region} × {genre} is still dark',
    gapSongs: 'Songs in this area',
    gapCount: '{n} songs not lit yet',
  },
  zhHant: {
    label: '鏡球・已點亮{n}面',
    roomLabel: '包廂鏡球・今晚{n}面',
    areaTitle: '{tempo} × {genre}',
    areaDark: '{n}首歌・還沒亮',
    areaLit: '{n}首中已點亮{k}面',
    openArea: '打開這個區域',
    'region.fast': '北側（快板）',
    'region.mid': '赤道（中板）',
    'region.slow': '南側（慢板）',
    gapHead: '你的鏡球：{region}×{genre}還是暗的',
    gapSongs: '這個區域的歌',
    gapCount: '還有{n}首沒亮',
  },
  zhHans: {
    label: '镜球・已点亮{n}面',
    roomLabel: '包厢镜球・今晚{n}面',
    areaTitle: '{tempo} × {genre}',
    areaDark: '{n}首歌・还没亮',
    areaLit: '{n}首中已点亮{k}面',
    openArea: '打开这个区域',
    'region.fast': '北侧（快板）',
    'region.mid': '赤道（中板）',
    'region.slow': '南侧（慢板）',
    gapHead: '你的镜球：{region}×{genre}还是暗的',
    gapSongs: '这个区域的歌',
    gapCount: '还有{n}首没亮',
  },
  ko: {
    label: '미러볼 · {n}면 점등',
    roomLabel: '방의 미러볼 · 오늘 밤 {n}면',
    areaTitle: '{tempo} × {genre}',
    areaDark: '{n}곡 · 아직 어두운 구역',
    areaLit: '{n}곡 중 {k}면 점등',
    openArea: '이 구역 열기',
    'region.fast': '북쪽(업템포)',
    'region.mid': '적도(미디엄)',
    'region.slow': '남쪽(슬로)',
    gapHead: '내 미러볼의 {region} × {genre}가 아직 어두워요',
    gapSongs: '이 구역의 곡',
    gapCount: '아직 {n}곡이 빛나지 않았어요',
  },
})
