// M10 services strings (SPEC G-3 namespace `services`): order menu, coaster, bring-in, entrance
// and the travel journal. Five locales, same keys and the same {variables} everywhere.
import { defineStrings } from '../../i18n'

export const S = defineStrings('services', {
  ja: {
    // menu
    'menu.highball': 'ハイボール',
    'menu.oolong': 'ウーロン茶',
    'menu.ginger': 'ジンジャー\u200Bエール',
    'menu.cola': 'コーラ',
    'menu.fries': 'ポテト',
    'menu.karaage': 'からあげ',
    'menu.water': 'お水',
    'menu.rest': 'ひと休み',
    'tag.free': '無料',
    'tag.noOrder': '注文なし',
    'kind.drink': 'ドリンク',
    'kind.food': 'フード',

    // order screen
    'order.title': '注文',
    'order.lead': 'この部屋まで届けます',
    'order.price': '価格は店舗の表示に従います（デモ）',
    'order.tap': 'タップで注文',
    'order.tracker': '注文の状況',
    'order.etaCard': '今頼むと{n}曲後に届く目安（デモ）',
    'order.eta': '{n}曲後に届く目安',
    'order.etaSoon': 'まもなく届きます',
    'order.closedSub': '退室したので、新しい注文は送れません',
    'order.restOn': '1曲ぶん、ゆっくり流れます',
    'order.restTap': 'タップで1曲ぶん休む',
    'order.count': '×{n}',
    'order.more': 'ほか{n}件',
    'order.aria': '{item}を注文',
    'status.sending': '送信中',
    'status.accepted': '受付済み {time}',
    'status.acceptedVenue': '店舗で受付済み {time}',
    'status.preparing': '準備中',
    'status.delivered': 'お届け済み',
    'status.closed': '締め切り',
    'step.sending': '送信',
    'step.accepted': '受付',
    'step.preparing': '準備',
    'step.delivered': 'お届け',
    dup: '同じ注文は受付済み（{time}）',
    dupSending: '同じ注文を送信中です',
    again: 'もう1つ',
    keepAsIs: 'このままでOK',

    // coaster card
    'coaster.rest': 'お水・ひと休み',
    'coaster.menu': 'メニューを見る',
    'coaster.order': '{item}を注文',
    'coaster.pick': 'ナビのおすすめ',

    // bring-in (import)
    'import.lead': 'サブスクのお気に入りから、ここで歌える候補が{n}曲',
    'import.src': '例：Apple Music・デモデータ',
    'import.private': 'このスマホだけに表示',
    'import.save': 'マイうたに保存',
    'import.saved': 'マイうたに保存済み',
    'import.savedShort': '保存済み',
    'import.show': 'この1曲だけ部屋に見せる（10秒）',
    'import.showing': '部屋の画面に表示中',
    'import.showBusy': '部屋の画面は使用中',
    'import.version': '歌唱版',
    'import.noAuto': '自動では保存しません。選んだ曲だけが保存されます',
    'import.noAutoShort': '自動では保存しません',
    'import.all': '候補をすべて見る',
    'import.done': '候補はすべてマイうたに保存しました',
    'import.title': '持ち込み',
    'import.next': '保存した曲は、次の来店の最初の手札に入ります',
    'import.count': 'マイうた {n}曲',
    'import.candidate': '候補',
    'import.pickOne': '候補のディスクを選んでください',

    // entrance (S0)
    'entry.welcome': 'ようこそ',
    'entry.tagline': '部屋の空気を読んで、次に歌いたくなる理由を配るナビ',
    'entry.qr': 'QRで参加中・ログイン不要',
    'entry.lang': '言語はいつでも切り替えられます',
    'entry.how': '入り方を選んでください',
    'entry.guest': 'ゲストで入る',
    'entry.guestSub': 'そのまま部屋へ。登録はいりません',
    'entry.continue': 'マイうたの続きから',
    'entry.continueSub': '前回までのボールと、保存した曲から始めます',
    'entry.continueSaved': 'マイうた {n}曲を持って入ります',
    'entry.voucher': '旅行予約のバウチャーで入る',
    'entry.voucherSub': '旅のしおり：案内→予約→バウチャー→受付→ルーム',
    'entry.mock': '模擬。実際の予約・決済にはつながりません',

    // travel journal (OTA flow)
    'ota.title': '旅のしおり',
    'ota.mock': '模擬',
    'ota.back': '戻る',
    'ota.s1': '多言語の店舗案内',
    'ota.s2': '予約（OTA・模擬）',
    'ota.s3': 'バウチャー提示',
    'ota.s4': 'フロントで受付',
    'ota.s5': 'ルーム案内',
    'ota.venue': '新ナビ デモ店（架空）',
    'ota.venueLine': '駅から徒歩3分・深夜まで営業（デモ）',
    'ota.f1': '曲名を母語で探せるナビ（5言語）',
    'ota.f2': 'QRで参加。ログインはいりません',
    'ota.f3': '飲み物は部屋からスマホで注文',
    'ota.readIn': 'この案内は5言語で読めます',
    'ota.toBook': '予約へ進む',
    'ota.site': '旅行予約サイト（模擬）',
    'ota.date': '日付',
    'ota.tonight': '今夜',
    'ota.time': '時間',
    'ota.people': '人数',
    'ota.peopleN': '{n}名',
    'ota.length': '利用時間',
    'ota.minutes': '{n}分',
    'ota.book': '予約する（模擬）',
    'ota.noPay': '決済は発生しません',
    'ota.voucher': 'バウチャー',
    'ota.code': '予約番号',
    'ota.showDesk': 'フロントでこの画面を見せてください',
    'ota.shown': 'フロントに見せた',
    'ota.checking': '受付中…',
    'ota.checked': '受付完了',
    'ota.deskLang': 'スタッフの画面にも{locale}で案内が出ています',
    'ota.toRoom': 'ルームへ',
    'ota.roomWay': 'エレベーターで3階、右手の奥（デモ）',
    'ota.roomTip': '部屋に入ると、このスマホがそのままナビになります',
    'ota.enter': '部屋に入る',
    'ota.complete': '旅のしおり、完成',
  },
  en: {
    'menu.highball': 'Highball',
    'menu.oolong': 'Oolong tea',
    'menu.ginger': 'Ginger ale',
    'menu.cola': 'Cola',
    'menu.fries': 'Fries',
    'menu.karaage': 'Karaage',
    'menu.water': 'Water',
    'menu.rest': 'Take a breather',
    'tag.free': 'Free',
    'tag.noOrder': 'No order',
    'kind.drink': 'Drinks',
    'kind.food': 'Food',

    'order.title': 'Order',
    'order.lead': 'Brought right to this room',
    'order.price': 'Prices follow the venue’s menu (demo)',
    'order.tap': 'Tap to order',
    'order.tracker': 'Your orders',
    'order.etaCard': 'Order now and it arrives in about {n} songs (demo)',
    'order.eta': 'Arrives in about {n} songs',
    'order.etaSoon': 'Arriving soon',
    'order.closedSub': 'You have left the room, so no new orders can be sent',
    'order.restOn': 'The room slows down for one song',
    'order.restTap': 'Tap to rest for one song',
    'order.count': '×{n}',
    'order.more': '{n} more',
    'order.aria': 'Order {item}',
    'status.sending': 'Sending',
    'status.accepted': 'Received {time}',
    'status.acceptedVenue': 'Received by the venue {time}',
    'status.preparing': 'Preparing',
    'status.delivered': 'Delivered',
    'status.closed': 'Closed',
    'step.sending': 'Sent',
    'step.accepted': 'Received',
    'step.preparing': 'Preparing',
    'step.delivered': 'Delivered',
    dup: 'Already received ({time})',
    dupSending: 'The same order is being sent',
    again: 'One more',
    keepAsIs: 'Keep it as is',

    'coaster.rest': 'Water / take a breather',
    'coaster.menu': 'See the menu',
    'coaster.order': 'Order {item}',
    'coaster.pick': 'Navi’s pick',

    'import.lead': '{n} songs from your subscription favorites you can sing here',
    'import.src': 'e.g. Apple Music · demo data',
    'import.private': 'Only on your phone',
    'import.save': 'Save to My Songs',
    'import.saved': 'Saved to My Songs',
    'import.savedShort': 'Saved',
    'import.show': 'Show just this song to the room (10 s)',
    'import.showing': 'On the room screen now',
    'import.showBusy': 'The room screen is busy',
    'import.version': 'Version',
    'import.noAuto': 'Nothing is saved automatically. Only the songs you pick are saved',
    'import.noAutoShort': 'Never saved automatically',
    'import.all': 'See all candidates',
    'import.done': 'Every candidate is saved to My Songs',
    'import.title': 'Bring your songs',
    'import.next': 'Saved songs come back in your first hand next visit',
    'import.count': 'My Songs: {n}',
    'import.candidate': 'Candidate',
    'import.pickOne': 'Pick a candidate disc',

    'entry.welcome': 'Welcome',
    'entry.tagline': 'A navi that reads the room and deals you reasons to sing next',
    'entry.qr': 'Joined by QR · no login',
    'entry.lang': 'You can switch languages any time',
    'entry.how': 'Choose how to come in',
    'entry.guest': 'Enter as a guest',
    'entry.guestSub': 'Straight into the room. No sign-up',
    'entry.continue': 'Continue from My Songs',
    'entry.continueSub': 'Start from your ball and the songs you saved',
    'entry.continueSaved': 'Bringing {n} songs from My Songs',
    'entry.voucher': 'Enter with a travel voucher',
    'entry.voucherSub': 'Travel journal: guide → booking → voucher → front desk → room',
    'entry.mock': 'Mock-up. Nothing connects to real booking or payment.',

    'ota.title': 'Travel journal',
    'ota.mock': 'Mock',
    'ota.back': 'Back',
    'ota.s1': 'Venue guide in your language',
    'ota.s2': 'Booking (OTA, mock)',
    'ota.s3': 'Show the voucher',
    'ota.s4': 'Front desk check-in',
    'ota.s5': 'To your room',
    'ota.venue': 'Shin-Navi demo venue (fictional)',
    'ota.venueLine': '3 min from the station · open late (demo)',
    'ota.f1': 'Find songs in your own language (5 languages)',
    'ota.f2': 'Join by QR. No login needed',
    'ota.f3': 'Order drinks from your phone in the room',
    'ota.readIn': 'This guide reads in 5 languages',
    'ota.toBook': 'Go to booking',
    'ota.site': 'Travel booking site (mock)',
    'ota.date': 'Date',
    'ota.tonight': 'Tonight',
    'ota.time': 'Time',
    'ota.people': 'Guests',
    'ota.peopleN': '{n} guests',
    'ota.length': 'Duration',
    'ota.minutes': '{n} min',
    'ota.book': 'Book (mock)',
    'ota.noPay': 'No payment is taken',
    'ota.voucher': 'Voucher',
    'ota.code': 'Booking no.',
    'ota.showDesk': 'Show this screen at the front desk',
    'ota.shown': 'Shown at the desk',
    'ota.checking': 'Checking in…',
    'ota.checked': 'Checked in',
    'ota.deskLang': 'The staff screen shows your guide in {locale} too',
    'ota.toRoom': 'To the room',
    'ota.roomWay': 'Elevator to 3F, at the end on the right (demo)',
    'ota.roomTip': 'Once inside, this phone becomes your navi',
    'ota.enter': 'Enter the room',
    'ota.complete': 'Journal complete',
  },
  zhHant: {
    'menu.highball': '高球',
    'menu.oolong': '烏龍茶',
    'menu.ginger': '薑汁汽水',
    'menu.cola': '可樂',
    'menu.fries': '薯條',
    'menu.karaage': '日式炸雞',
    'menu.water': '開水',
    'menu.rest': '休息一下',
    'tag.free': '免費',
    'tag.noOrder': '不點餐',
    'kind.drink': '飲料',
    'kind.food': '餐點',

    'order.title': '點餐',
    'order.lead': '直接送到這間包廂',
    'order.price': '價格以店內標示為準（示意）',
    'order.tap': '點一下即點餐',
    'order.tracker': '點餐狀態',
    'order.etaCard': '現在點，約{n}首歌後送達（示意）',
    'order.eta': '約{n}首歌後送達',
    'order.etaSoon': '即將送達',
    'order.closedSub': '已離開包廂，無法再送出新的點餐',
    'order.restOn': '放慢一首歌的時間',
    'order.restTap': '點一下，休息一首歌',
    'order.count': '×{n}',
    'order.more': '其他{n}筆',
    'order.aria': '點{item}',
    'status.sending': '傳送中',
    'status.accepted': '已受理 {time}',
    'status.acceptedVenue': '店家已受理 {time}',
    'status.preparing': '準備中',
    'status.delivered': '已送達',
    'status.closed': '已截止',
    'step.sending': '傳送',
    'step.accepted': '受理',
    'step.preparing': '準備',
    'step.delivered': '送達',
    dup: '相同的點餐已受理（{time}）',
    dupSending: '相同的點餐正在傳送',
    again: '再來一份',
    keepAsIs: '維持原樣',

    'coaster.rest': '開水・休息一下',
    'coaster.menu': '看菜單',
    'coaster.order': '點{item}',
    'coaster.pick': '導航推薦',

    'import.lead': '從訂閱服務的收藏中，這裡能唱的候選有{n}首',
    'import.src': '例：Apple Music・示意資料',
    'import.private': '只顯示在你的手機',
    'import.save': '存到我的歌單',
    'import.saved': '已存到我的歌單',
    'import.savedShort': '已儲存',
    'import.show': '只把這首給大家看（10秒）',
    'import.showing': '正在包廂畫面顯示',
    'import.showBusy': '包廂畫面使用中',
    'import.version': '演唱版本',
    'import.noAuto': '不會自動儲存，只存你選的歌',
    'import.noAutoShort': '不會自動儲存',
    'import.all': '查看全部候選',
    'import.done': '候選都存到我的歌單了',
    'import.title': '帶歌進來',
    'import.next': '存下的歌會出現在下次來店的第一手牌',
    'import.count': '我的歌單 {n}首',
    'import.candidate': '候選',
    'import.pickOne': '請選一張候選唱片',

    'entry.welcome': '歡迎光臨',
    'entry.tagline': '讀懂包廂氣氛、發給你下一首想唱理由的導航',
    'entry.qr': '已用QR加入・免登入',
    'entry.lang': '隨時可以切換語言',
    'entry.how': '請選擇進入方式',
    'entry.guest': '以訪客身分進入',
    'entry.guestSub': '直接進包廂，不用註冊',
    'entry.continue': '從我的歌單繼續',
    'entry.continueSub': '從你的鏡球和存下的歌開始',
    'entry.continueSaved': '帶著我的歌單 {n}首進場',
    'entry.voucher': '用旅遊訂位憑證進入',
    'entry.voucherSub': '旅遊手帖：介紹→訂位→憑證→報到→包廂',
    'entry.mock': '模擬示意，不會連到實際的訂位或付款。',

    'ota.title': '旅遊手帖',
    'ota.mock': '模擬',
    'ota.back': '返回',
    'ota.s1': '多語言店家介紹',
    'ota.s2': '訂位（OTA・模擬）',
    'ota.s3': '出示憑證',
    'ota.s4': '櫃檯報到',
    'ota.s5': '包廂引導',
    'ota.venue': '新ナビ 示範店（虛構）',
    'ota.venueLine': '車站步行3分鐘・營業到深夜（示意）',
    'ota.f1': '能用母語找歌的導航（5種語言）',
    'ota.f2': '掃QR加入，免登入',
    'ota.f3': '在包廂用手機點飲料',
    'ota.readIn': '此介紹提供5種語言',
    'ota.toBook': '前往訂位',
    'ota.site': '旅遊訂位網站（模擬）',
    'ota.date': '日期',
    'ota.tonight': '今晚',
    'ota.time': '時間',
    'ota.people': '人數',
    'ota.peopleN': '{n}位',
    'ota.length': '使用時間',
    'ota.minutes': '{n}分鐘',
    'ota.book': '訂位（模擬）',
    'ota.noPay': '不會產生付款',
    'ota.voucher': '憑證',
    'ota.code': '訂位編號',
    'ota.showDesk': '請在櫃檯出示此畫面',
    'ota.shown': '已向櫃檯出示',
    'ota.checking': '報到中…',
    'ota.checked': '報到完成',
    'ota.deskLang': '店員的畫面也以{locale}顯示說明',
    'ota.toRoom': '前往包廂',
    'ota.roomWay': '搭電梯到3樓，右手邊最裡面（示意）',
    'ota.roomTip': '進入包廂後，這支手機就是你的導航',
    'ota.enter': '進入包廂',
    'ota.complete': '旅遊手帖完成',
  },
  zhHans: {
    'menu.highball': '高球',
    'menu.oolong': '乌龙茶',
    'menu.ginger': '姜汁汽水',
    'menu.cola': '可乐',
    'menu.fries': '薯条',
    'menu.karaage': '日式炸鸡',
    'menu.water': '饮用水',
    'menu.rest': '休息一下',
    'tag.free': '免费',
    'tag.noOrder': '不点餐',
    'kind.drink': '饮料',
    'kind.food': '餐点',

    'order.title': '点餐',
    'order.lead': '直接送到这间包厢',
    'order.price': '价格以店内标示为准（示意）',
    'order.tap': '点一下即点餐',
    'order.tracker': '点餐状态',
    'order.etaCard': '现在点，约{n}首歌后送达（示意）',
    'order.eta': '约{n}首歌后送达',
    'order.etaSoon': '即将送达',
    'order.closedSub': '已离开包厢，无法再发送新的点餐',
    'order.restOn': '放慢一首歌的时间',
    'order.restTap': '点一下，休息一首歌',
    'order.count': '×{n}',
    'order.more': '其他{n}笔',
    'order.aria': '点{item}',
    'status.sending': '发送中',
    'status.accepted': '已受理 {time}',
    'status.acceptedVenue': '店家已受理 {time}',
    'status.preparing': '准备中',
    'status.delivered': '已送达',
    'status.closed': '已截止',
    'step.sending': '发送',
    'step.accepted': '受理',
    'step.preparing': '准备',
    'step.delivered': '送达',
    dup: '相同的点餐已受理（{time}）',
    dupSending: '相同的点餐正在发送',
    again: '再来一份',
    keepAsIs: '保持原样',

    'coaster.rest': '饮用水・休息一下',
    'coaster.menu': '看菜单',
    'coaster.order': '点{item}',
    'coaster.pick': '导航推荐',

    'import.lead': '从订阅服务的收藏中，这里能唱的候选有{n}首',
    'import.src': '例：Apple Music・示意数据',
    'import.private': '只显示在你的手机',
    'import.save': '存到我的歌单',
    'import.saved': '已存到我的歌单',
    'import.savedShort': '已保存',
    'import.show': '只把这首给大家看（10秒）',
    'import.showing': '正在包厢画面显示',
    'import.showBusy': '包厢画面使用中',
    'import.version': '演唱版本',
    'import.noAuto': '不会自动保存，只存你选的歌',
    'import.noAutoShort': '不会自动保存',
    'import.all': '查看全部候选',
    'import.done': '候选都存到我的歌单了',
    'import.title': '带歌进来',
    'import.next': '存下的歌会出现在下次来店的第一手牌',
    'import.count': '我的歌单 {n}首',
    'import.candidate': '候选',
    'import.pickOne': '请选一张候选唱片',

    'entry.welcome': '欢迎光临',
    'entry.tagline': '读懂包厢气氛、发给你下一首想唱理由的导航',
    'entry.qr': '已用QR加入・免登录',
    'entry.lang': '随时可以切换语言',
    'entry.how': '请选择进入方式',
    'entry.guest': '以访客身份进入',
    'entry.guestSub': '直接进包厢，不用注册',
    'entry.continue': '从我的歌单继续',
    'entry.continueSub': '从你的镜球和存下的歌开始',
    'entry.continueSaved': '带着我的歌单 {n}首进场',
    'entry.voucher': '用旅游预订凭证进入',
    'entry.voucherSub': '旅游手帐：介绍→预订→凭证→登记→包厢',
    'entry.mock': '模拟示意，不会连到实际的预订或付款。',

    'ota.title': '旅游手帐',
    'ota.mock': '模拟',
    'ota.back': '返回',
    'ota.s1': '多语言店家介绍',
    'ota.s2': '预订（OTA・模拟）',
    'ota.s3': '出示凭证',
    'ota.s4': '前台登记',
    'ota.s5': '包厢引导',
    'ota.venue': '新ナビ 示范店（虚构）',
    'ota.venueLine': '车站步行3分钟・营业到深夜（示意）',
    'ota.f1': '能用母语找歌的导航（5种语言）',
    'ota.f2': '扫QR加入，免登录',
    'ota.f3': '在包厢用手机点饮料',
    'ota.readIn': '此介绍提供5种语言',
    'ota.toBook': '前往预订',
    'ota.site': '旅游预订网站（模拟）',
    'ota.date': '日期',
    'ota.tonight': '今晚',
    'ota.time': '时间',
    'ota.people': '人数',
    'ota.peopleN': '{n}位',
    'ota.length': '使用时长',
    'ota.minutes': '{n}分钟',
    'ota.book': '预订（模拟）',
    'ota.noPay': '不会产生付款',
    'ota.voucher': '凭证',
    'ota.code': '预订编号',
    'ota.showDesk': '请在前台出示此画面',
    'ota.shown': '已向前台出示',
    'ota.checking': '登记中…',
    'ota.checked': '登记完成',
    'ota.deskLang': '店员的画面也以{locale}显示说明',
    'ota.toRoom': '前往包厢',
    'ota.roomWay': '坐电梯到3楼，右手边最里面（示意）',
    'ota.roomTip': '进入包厢后，这部手机就是你的导航',
    'ota.enter': '进入包厢',
    'ota.complete': '旅游手帐完成',
  },
  ko: {
    'menu.highball': '하이볼',
    'menu.oolong': '우롱차',
    'menu.ginger': '진저에일',
    'menu.cola': '콜라',
    'menu.fries': '감자튀김',
    'menu.karaage': '가라아게',
    'menu.water': '물',
    'menu.rest': '잠깐 쉬기',
    'tag.free': '무료',
    'tag.noOrder': '주문 없음',
    'kind.drink': '음료',
    'kind.food': '푸드',

    'order.title': '주문',
    'order.lead': '이 방까지 가져다드려요',
    'order.price': '가격은 매장 표시를 따릅니다 (데모)',
    'order.tap': '탭해서 주문',
    'order.tracker': '주문 현황',
    'order.etaCard': '지금 주문하면 약 {n}곡 뒤 도착 예정 (데모)',
    'order.eta': '약 {n}곡 뒤 도착 예정',
    'order.etaSoon': '곧 도착해요',
    'order.closedSub': '퇴실해서 새 주문은 보낼 수 없어요',
    'order.restOn': '한 곡 동안 천천히 흘러가요',
    'order.restTap': '탭해서 한 곡 쉬기',
    'order.count': '×{n}',
    'order.more': '외 {n}건',
    'order.aria': '{item} 주문',
    'status.sending': '전송 중',
    'status.accepted': '접수됨 {time}',
    'status.acceptedVenue': '매장에서 접수됨 {time}',
    'status.preparing': '준비 중',
    'status.delivered': '전달 완료',
    'status.closed': '마감',
    'step.sending': '전송',
    'step.accepted': '접수',
    'step.preparing': '준비',
    'step.delivered': '전달',
    dup: '같은 주문은 이미 접수됨 ({time})',
    dupSending: '같은 주문을 전송하고 있어요',
    again: '하나 더',
    keepAsIs: '그대로 둘게요',

    'coaster.rest': '물 · 잠깐 쉬기',
    'coaster.menu': '메뉴 보기',
    'coaster.order': '{item} 주문',
    'coaster.pick': '내비 추천',

    'import.lead': '구독 서비스 즐겨찾기 중 여기서 부를 수 있는 후보 {n}곡',
    'import.src': '예: Apple Music · 데모 데이터',
    'import.private': '내 폰에만 표시',
    'import.save': '마이 노래에 저장',
    'import.saved': '마이 노래에 저장됨',
    'import.savedShort': '저장됨',
    'import.show': '이 곡만 방 화면에 보여주기 (10초)',
    'import.showing': '방 화면에 표시 중',
    'import.showBusy': '방 화면 사용 중',
    'import.version': '버전',
    'import.noAuto': '자동으로 저장하지 않아요. 고른 곡만 저장돼요',
    'import.noAutoShort': '자동 저장 안 해요',
    'import.all': '후보 모두 보기',
    'import.done': '후보를 모두 마이 노래에 저장했어요',
    'import.title': '가져온 곡',
    'import.next': '저장한 곡은 다음 방문 첫 카드에 들어가요',
    'import.count': '마이 노래 {n}곡',
    'import.candidate': '후보',
    'import.pickOne': '후보 디스크를 골라 주세요',

    'entry.welcome': '환영합니다',
    'entry.tagline': '방의 분위기를 읽고 다음에 부르고 싶은 이유를 건네는 내비',
    'entry.qr': 'QR로 참여 중 · 로그인 불필요',
    'entry.lang': '언제든 언어를 바꿀 수 있어요',
    'entry.how': '입장 방법을 골라 주세요',
    'entry.guest': '게스트로 입장',
    'entry.guestSub': '바로 방으로. 가입은 필요 없어요',
    'entry.continue': '마이 노래에서 이어서',
    'entry.continueSub': '지난번의 볼과 저장한 곡에서 시작해요',
    'entry.continueSaved': '마이 노래 {n}곡을 가지고 입장',
    'entry.voucher': '여행 예약 바우처로 입장',
    'entry.voucherSub': '여행 수첩: 안내→예약→바우처→접수→룸',
    'entry.mock': '모의 화면입니다. 실제 예약·결제로 이어지지 않아요.',

    'ota.title': '여행 수첩',
    'ota.mock': '모의',
    'ota.back': '뒤로',
    'ota.s1': '다국어 매장 안내',
    'ota.s2': '예약 (OTA · 모의)',
    'ota.s3': '바우처 제시',
    'ota.s4': '프런트 접수',
    'ota.s5': '룸 안내',
    'ota.venue': '신나비 데모점 (가상)',
    'ota.venueLine': '역에서 도보 3분 · 심야 영업 (데모)',
    'ota.f1': '모국어로 곡을 찾는 내비 (5개 언어)',
    'ota.f2': 'QR로 참여. 로그인 불필요',
    'ota.f3': '방에서 폰으로 음료 주문',
    'ota.readIn': '이 안내는 5개 언어로 볼 수 있어요',
    'ota.toBook': '예약하러 가기',
    'ota.site': '여행 예약 사이트 (모의)',
    'ota.date': '날짜',
    'ota.tonight': '오늘 밤',
    'ota.time': '시간',
    'ota.people': '인원',
    'ota.peopleN': '{n}명',
    'ota.length': '이용 시간',
    'ota.minutes': '{n}분',
    'ota.book': '예약하기 (모의)',
    'ota.noPay': '결제는 발생하지 않아요',
    'ota.voucher': '바우처',
    'ota.code': '예약 번호',
    'ota.showDesk': '프런트에서 이 화면을 보여 주세요',
    'ota.shown': '프런트에 보여줬어요',
    'ota.checking': '접수 중…',
    'ota.checked': '접수 완료',
    'ota.deskLang': '직원 화면에도 {locale}(으)로 안내가 표시돼요',
    'ota.toRoom': '룸으로',
    'ota.roomWay': '엘리베이터로 3층, 오른쪽 가장 안쪽 (데모)',
    'ota.roomTip': '방에 들어가면 이 폰이 그대로 내비가 돼요',
    'ota.enter': '방에 들어가기',
    'ota.complete': '여행 수첩 완성',
  },
})

export type ServicesKey = Parameters<typeof S.t>[0]
