// M6 stage strings (namespace "stage"): the lane, the floor, the mood word, the sing tab,
// standby, the room screen, the seam and the shift card. Every key exists in all 5 locales.
// Nothing here ever says "does not know" (SPEC E-12): only positive or neutral wording.
import { defineStrings } from '../../i18n'

export const S = defineStrings('stage', {
  ja: {
    roomLaneEmpty: 'スマホで札を上に投げると、ここに並びます',
    // lane
    nowEmpty: '最初の1曲が、この部屋の空気をつくる',
    upNext: 'まもなく',
    waiting: '次の曲を待っています',
    myTurnIn: 'あなたの番まであと{n}曲',
    myTurnNow: 'あなたの番',
    myTurnShort: 'あと{n}曲',
    laneAria: '予約列',
    dropHere: 'ここに入ります',
    queueCount: '予約 {n}曲',
    etaSongs: 'あと{n}曲',
    'tag.navi': 'ナビのおすすめ',
    'tag.request': 'リクエスト',
    'tag.duet': 'デュエット',
    'tag.finale': '締めの1曲',
    'tag.visa': '越境',
    'tag.insert': '差し込み',
    'tag.room': '部屋から',
    glass: 'ドリンクが届く目安',
    glassIn: '{n}曲後に届く目安',
    flowLabel: '今夜の流れ',
    flowForecast: 'ナビの見立て',
    flowUp: 'アガりそう',
    flowDown: 'しっとりしそう',
    flowFlat: '流れはそのまま',
    // floor
    orbArriving: '向かってる…',
    orbSinging: '歌ってる',
    orbAgree: '賛成の光',
    // mood
    moodLabel: '今の空気',
    moodTap: '空気ミキサーを開く',
    mixHint: '読みを合わせる？',
    // sing tab
    stageTitle: 'ステージ',
    nowPlaying: 'いま歌っている曲',
    nobodySinging: 'まだ誰も歌っていません',
    startsSoon: 'まもなく始まります',
    yourTurn: 'あなたの番',
    yourTurnLead: 'スポットライトはあなたに。',
    finish: '歌い終わった（デモ）',
    scoreLabel: '採点（デモ）',
    scorePts: '{n}点',
    bestNew: '今夜の自己ベスト',
    bestFirst: '今夜はじめての採点',
    bestGap: '今夜の自己ベストまであと{n}点',
    bestSame: '今夜の自己ベストに並んだ',
    scoreNote: 'くらべるのは自分の記録だけ',
    voiceNudge: '今夜の声の札が届いています',
    voiceGo: '探すで見る',
    queueTitle: '予約列',
    playOrder: '演奏順',
    moveUp: '前へ',
    moveDown: '後ろへ',
    cancel: '取り消す',
    cancelAgain: 'もう一度で取り消し',
    queueEmpty: 'まだ予約はありません',
    mineNone: 'あなたの曲はまだ入っていません',
    findSong: '曲を探す',
    penTitle: 'ペンライト',
    penHint: 'タップでペンライトを振る',
    penSub: 'どこをタップしても音は外れません',
    penFor: '{member}に光を送ろう',
    putDown: 'スマホを置いて聴く',
    exit: '退室する',
    history: 'さっきまで',
    crystal: '拍手の結晶',
    // standby
    standbyLabel: 'ステージ待機',
    standbyNone: 'いまは予約がありません',
    standbyRelax: 'スマホを置いて、歌を聴こう',
    standbyGather: 'そろそろ出番。光が集まってきた',
    standbyNow: 'あなたの番です',
    toStage: 'ステージへ',
    backToFind: '探すに戻る',
    tapToReturn: 'タップして戻る',
    // room screen
    roomSearch: 'この端末で探す',
    roomLock: '記録・声・持ち込みはスマホで開く',
    askTitle: 'この曲、知ってる？',
    askNote: '答えた人の分だけ数えます',
    allKnow: 'この部屋の全員が知ってる',
    shiftTitle: '流れを変える提案',
    shiftBody: '次にこの1曲を挟もう',
    shiftWaiting: 'みんなの賛成の光を待っています',
    finaleTitle: '締めの1曲',
    finaleBody: 'この部屋で絶対に上がる1曲に灯りを',
    showTitle: 'いま部屋に見せている1曲',
    members: 'この部屋',
    air: '空気',
    constellation: '今夜の光座',
    orders: '注文',
    ordersCount: '{n}件',
    'order.sending': '送信中',
    'order.accepted': '受付済み',
    'order.preparing': '準備中',
    'order.delivered': 'お届け済み',
    ordersNone: '注文はスマホから',
    joinQr: 'スマホで参加（QR・インストール不要・ログイン不要）',
    qrNote: 'QRは表示イメージです（デモ）',
    // shift card
    shiftKind: '空気の変わり目',
    ride: '流れに乗る',
    change: '流れを変える',
    naviPick: 'ナビのおすすめ',
    insertNext: '次に挟む',
    next: '次',
    tonightHeat: '今夜の熱の流れ',
    noHistory: 'まだ1曲も終わっていません',
    agreeNote: 'みんなの賛成がそろったら、次に入ります',
    why: 'なぜこの札？',
    whyRule: 'ルール: {rule}',
    hypothesis: '点線はナビの見立て（仮説）',
  },
  en: {
    roomLaneEmpty: 'Throw a card up on your phone and it lines up here',
    nowEmpty: 'The first song sets the air in this room',
    upNext: 'Up next',
    waiting: 'Waiting for the next song',
    myTurnIn: '{n} songs until your turn',
    myTurnNow: 'Your turn',
    myTurnShort: '{n} to go',
    laneAria: 'Song queue',
    dropHere: 'Drops in here',
    queueCount: '{n} queued',
    etaSongs: 'in {n}',
    'tag.navi': 'Navi pick',
    'tag.request': 'Request',
    'tag.duet': 'Duet',
    'tag.finale': 'Closing song',
    'tag.visa': 'Crossing',
    'tag.insert': 'Slotted in',
    'tag.room': 'From the room',
    glass: 'Drinks arrive about here',
    glassIn: 'Arrives in about {n} songs',
    flowLabel: 'Tonight’s flow',
    flowForecast: "Navi's read",
    flowUp: 'will lift',
    flowDown: 'will mellow',
    flowFlat: 'keeps the flow',
    orbArriving: 'On the way…',
    orbSinging: 'Singing',
    orbAgree: 'Agrees',
    moodLabel: 'The air now',
    moodTap: 'Open the mood mixer',
    mixHint: 'Tune the read?',
    stageTitle: 'Stage',
    nowPlaying: 'Singing now',
    nobodySinging: 'Nobody is singing yet',
    startsSoon: 'Starting soon',
    yourTurn: 'Your turn',
    yourTurnLead: 'The spotlight is on you.',
    finish: 'I finished (demo)',
    scoreLabel: 'Score (demo)',
    scorePts: '{n} pts',
    bestNew: 'Your best tonight',
    bestFirst: 'Your first score tonight',
    bestGap: '{n} pts to your best tonight',
    bestSame: 'Matched your best tonight',
    scoreNote: 'Only compared with yourself',
    voiceNudge: 'Your voice card for tonight is here',
    voiceGo: 'See it in Find',
    queueTitle: 'Queue',
    playOrder: 'Play order',
    moveUp: 'Earlier',
    moveDown: 'Later',
    cancel: 'Cancel',
    cancelAgain: 'Tap again to cancel',
    queueEmpty: 'Nothing queued yet',
    mineNone: 'None of your songs are queued yet',
    findSong: 'Find a song',
    penTitle: 'Penlight',
    penHint: 'Tap to wave a penlight',
    penSub: 'Tap anywhere, it always stays in tune',
    penFor: 'Send light to {member}',
    putDown: 'Put the phone down and listen',
    exit: 'Leave the room',
    history: 'Just now',
    crystal: 'Applause crystal',
    standbyLabel: 'Stage standby',
    standbyNone: 'Nothing queued for you right now',
    standbyRelax: 'Put the phone down and enjoy the song',
    standbyGather: 'You are up soon. The light is gathering',
    standbyNow: 'It’s your turn',
    toStage: 'To the stage',
    backToFind: 'Back to Find',
    tapToReturn: 'Tap to go back',
    roomSearch: 'Search on this screen',
    roomLock: 'Collection, voice and brought songs open on your phone',
    askTitle: 'Do you know this song?',
    askNote: 'Only answers are counted',
    allKnow: 'Everyone in this room knows it',
    shiftTitle: 'A proposal to change the flow',
    shiftBody: 'Slot this one in next',
    shiftWaiting: 'Waiting for everyone’s light',
    finaleTitle: 'Closing song',
    finaleBody: 'Light a lantern for the one that lifts this room',
    showTitle: 'A song shared with the room',
    members: 'In this room',
    air: 'The air',
    constellation: 'Tonight’s light-sign',
    orders: 'Orders',
    ordersCount: '{n}',
    'order.sending': 'Sending',
    'order.accepted': 'Received',
    'order.preparing': 'Preparing',
    'order.delivered': 'Delivered',
    ordersNone: 'Order from your phone',
    joinQr: 'Join on your phone (QR · no install · no login)',
    qrNote: 'Illustrative QR (demo)',
    shiftKind: 'Turning point',
    ride: 'Ride the flow',
    change: 'Change the flow',
    naviPick: 'Navi pick',
    insertNext: 'Slot in next',
    next: 'Next',
    tonightHeat: 'Tonight’s heat',
    noHistory: 'No song has finished yet',
    agreeNote: 'It goes in next once everyone agrees',
    why: 'Why this card?',
    whyRule: 'Rule: {rule}',
    hypothesis: 'Dotted line = Navi’s read (hypothesis)',
  },
  zhHant: {
    roomLaneEmpty: '在手機上把卡片往上滑，就會排到這裡',
    nowEmpty: '第一首歌，決定這個包廂的氣氛',
    upNext: '即將開始',
    waiting: '等待下一首',
    myTurnIn: '再{n}首輪到你',
    myTurnNow: '輪到你了',
    myTurnShort: '再{n}首',
    laneAria: '點歌列表',
    dropHere: '從這裡加入',
    queueCount: '已點 {n} 首',
    etaSongs: '再{n}首',
    'tag.navi': '導航推薦',
    'tag.request': '點播',
    'tag.duet': '對唱',
    'tag.finale': '壓軸曲',
    'tag.visa': '跨境',
    'tag.insert': '插播',
    'tag.room': '來自包廂',
    glass: '飲料大約在這裡送達',
    glassIn: '大約{n}首後送達',
    flowLabel: '今晚的氣氛',
    flowForecast: '導航的判斷',
    flowUp: '會嗨起來',
    flowDown: '會變抒情',
    flowFlat: '維持現在的氣氛',
    orbArriving: '正在路上…',
    orbSinging: '正在唱',
    orbAgree: '贊成',
    moodLabel: '現在的氣氛',
    moodTap: '打開氣氛混音器',
    mixHint: '要調整判斷嗎？',
    stageTitle: '舞台',
    nowPlaying: '正在唱的歌',
    nobodySinging: '還沒有人開唱',
    startsSoon: '即將開始',
    yourTurn: '輪到你了',
    yourTurnLead: '聚光燈打在你身上。',
    finish: '唱完了（示意）',
    scoreLabel: '評分（示意）',
    scorePts: '{n}分',
    bestNew: '今晚的個人最佳',
    bestFirst: '今晚第一次評分',
    bestGap: '距離今晚個人最佳還差{n}分',
    bestSame: '追平今晚的個人最佳',
    scoreNote: '只和自己的紀錄比較',
    voiceNudge: '今晚的聲音卡片到了',
    voiceGo: '到「找歌」查看',
    queueTitle: '點歌列表',
    playOrder: '演唱順序',
    moveUp: '往前',
    moveDown: '往後',
    cancel: '取消',
    cancelAgain: '再按一次取消',
    queueEmpty: '還沒有人點歌',
    mineNone: '你還沒有點歌',
    findSong: '找歌',
    penTitle: '螢光棒',
    penHint: '點一下揮動螢光棒',
    penSub: '點哪裡都不會走音',
    penFor: '為{member}送上光芒',
    putDown: '放下手機，好好聽',
    exit: '離開包廂',
    history: '剛才',
    crystal: '掌聲結晶',
    standbyLabel: '舞台待機',
    standbyNone: '目前沒有你的點歌',
    standbyRelax: '放下手機，好好聽歌',
    standbyGather: '快輪到你了，光正在聚集',
    standbyNow: '輪到你了',
    toStage: '上台',
    backToFind: '回到找歌',
    tapToReturn: '點一下返回',
    roomSearch: '在這台螢幕找歌',
    roomLock: '紀錄、聲音、自帶歌曲請在手機上開啟',
    askTitle: '這首歌，你會唱嗎？',
    askNote: '只計算有回答的人',
    allKnow: '這個包廂的每個人都會唱',
    shiftTitle: '改變氣氛的提案',
    shiftBody: '下一首插播這首吧',
    shiftWaiting: '等待大家的贊成之光',
    finaleTitle: '壓軸曲',
    finaleBody: '為最能炒熱包廂的一首點燈',
    showTitle: '正在分享給包廂的一首',
    members: '這個包廂',
    air: '氣氛',
    constellation: '今晚的光座',
    orders: '點餐',
    ordersCount: '{n}筆',
    'order.sending': '傳送中',
    'order.accepted': '已受理',
    'order.preparing': '準備中',
    'order.delivered': '已送達',
    ordersNone: '請用手機點餐',
    joinQr: '用手機加入（QR・免安裝・免登入）',
    qrNote: 'QR碼為示意圖（示意）',
    shiftKind: '氣氛轉折點',
    ride: '順著氣氛',
    change: '改變氣氛',
    naviPick: '導航推薦',
    insertNext: '插到下一首',
    next: '下一首',
    tonightHeat: '今晚的熱度',
    noHistory: '還沒有唱完的歌',
    agreeNote: '大家都贊成後就插到下一首',
    why: '為什麼是這張卡？',
    whyRule: '規則: {rule}',
    hypothesis: '虛線是導航的判斷（假設）',
  },
  zhHans: {
    roomLaneEmpty: '在手机上把卡片往上滑，就会排到这里',
    nowEmpty: '第一首歌，决定这个包厢的气氛',
    upNext: '即将开始',
    waiting: '等待下一首',
    myTurnIn: '再{n}首轮到你',
    myTurnNow: '轮到你了',
    myTurnShort: '再{n}首',
    laneAria: '点歌列表',
    dropHere: '从这里加入',
    queueCount: '已点 {n} 首',
    etaSongs: '再{n}首',
    'tag.navi': '导航推荐',
    'tag.request': '点播',
    'tag.duet': '对唱',
    'tag.finale': '压轴曲',
    'tag.visa': '跨境',
    'tag.insert': '插播',
    'tag.room': '来自包厢',
    glass: '饮料大约在这里送达',
    glassIn: '大约{n}首后送达',
    flowLabel: '今晚的气氛',
    flowForecast: '导航的判断',
    flowUp: '会嗨起来',
    flowDown: '会变抒情',
    flowFlat: '保持现在的气氛',
    orbArriving: '正在路上…',
    orbSinging: '正在唱',
    orbAgree: '赞成',
    moodLabel: '现在的气氛',
    moodTap: '打开气氛混音器',
    mixHint: '要调整判断吗？',
    stageTitle: '舞台',
    nowPlaying: '正在唱的歌',
    nobodySinging: '还没有人开唱',
    startsSoon: '即将开始',
    yourTurn: '轮到你了',
    yourTurnLead: '聚光灯打在你身上。',
    finish: '唱完了（示意）',
    scoreLabel: '评分（示意）',
    scorePts: '{n}分',
    bestNew: '今晚的个人最佳',
    bestFirst: '今晚第一次评分',
    bestGap: '距离今晚个人最佳还差{n}分',
    bestSame: '追平今晚的个人最佳',
    scoreNote: '只和自己的记录比较',
    voiceNudge: '今晚的声音卡片到了',
    voiceGo: '到「找歌」查看',
    queueTitle: '点歌列表',
    playOrder: '演唱顺序',
    moveUp: '往前',
    moveDown: '往后',
    cancel: '取消',
    cancelAgain: '再按一次取消',
    queueEmpty: '还没有人点歌',
    mineNone: '你还没有点歌',
    findSong: '找歌',
    penTitle: '荧光棒',
    penHint: '点一下挥动荧光棒',
    penSub: '点哪里都不会跑调',
    penFor: '为{member}送上光芒',
    putDown: '放下手机，好好听',
    exit: '离开包厢',
    history: '刚才',
    crystal: '掌声结晶',
    standbyLabel: '舞台待机',
    standbyNone: '目前没有你的点歌',
    standbyRelax: '放下手机，好好听歌',
    standbyGather: '快轮到你了，光正在聚集',
    standbyNow: '轮到你了',
    toStage: '上台',
    backToFind: '回到找歌',
    tapToReturn: '点一下返回',
    roomSearch: '在这台屏幕找歌',
    roomLock: '记录、声音、自带歌曲请在手机上打开',
    askTitle: '这首歌，你会唱吗？',
    askNote: '只计算有回答的人',
    allKnow: '这个包厢的每个人都会唱',
    shiftTitle: '改变气氛的提案',
    shiftBody: '下一首插播这首吧',
    shiftWaiting: '等待大家的赞成之光',
    finaleTitle: '压轴曲',
    finaleBody: '为最能炒热包厢的一首点灯',
    showTitle: '正在分享给包厢的一首',
    members: '这个包厢',
    air: '气氛',
    constellation: '今晚的光座',
    orders: '点餐',
    ordersCount: '{n}笔',
    'order.sending': '发送中',
    'order.accepted': '已受理',
    'order.preparing': '准备中',
    'order.delivered': '已送达',
    ordersNone: '请用手机点餐',
    joinQr: '用手机加入（二维码・免安装・免登录）',
    qrNote: '二维码为示意图（示意）',
    shiftKind: '气氛转折点',
    ride: '顺着气氛',
    change: '改变气氛',
    naviPick: '导航推荐',
    insertNext: '插到下一首',
    next: '下一首',
    tonightHeat: '今晚的热度',
    noHistory: '还没有唱完的歌',
    agreeNote: '大家都赞成后就插到下一首',
    why: '为什么是这张卡？',
    whyRule: '规则: {rule}',
    hypothesis: '虚线是导航的判断（假设）',
  },
  ko: {
    roomLaneEmpty: '폰에서 카드를 위로 던지면 여기에 줄을 서요',
    nowEmpty: '첫 곡이 이 방의 분위기를 만들어요',
    upNext: '곧 시작',
    waiting: '다음 곡을 기다리는 중',
    myTurnIn: '{n}곡 뒤에 내 차례',
    myTurnNow: '내 차례',
    myTurnShort: '{n}곡 뒤',
    laneAria: '예약 목록',
    dropHere: '여기로 들어가요',
    queueCount: '예약 {n}곡',
    etaSongs: '{n}곡 뒤',
    'tag.navi': '내비 추천',
    'tag.request': '리퀘스트',
    'tag.duet': '듀엣',
    'tag.finale': '마지막 곡',
    'tag.visa': '크로싱',
    'tag.insert': '끼워 넣기',
    'tag.room': '방에서',
    glass: '음료가 도착할 즈음',
    glassIn: '약 {n}곡 뒤 도착',
    flowLabel: '오늘 밤의 흐름',
    flowForecast: '내비의 예측',
    flowUp: '분위기가 오를 듯',
    flowDown: '차분해질 듯',
    flowFlat: '지금 흐름 그대로',
    orbArriving: '오는 중…',
    orbSinging: '노래 중',
    orbAgree: '찬성',
    moodLabel: '지금 분위기',
    moodTap: '분위기 믹서 열기',
    mixHint: '읽기를 맞춰 볼까요?',
    stageTitle: '스테이지',
    nowPlaying: '지금 부르는 곡',
    nobodySinging: '아직 아무도 부르지 않았어요',
    startsSoon: '곧 시작해요',
    yourTurn: '내 차례',
    yourTurnLead: '스포트라이트는 당신에게.',
    finish: '다 불렀어요 (데모)',
    scoreLabel: '채점 (데모)',
    scorePts: '{n}점',
    bestNew: '오늘 밤 나의 최고점',
    bestFirst: '오늘 밤 첫 채점',
    bestGap: '오늘 밤 최고점까지 {n}점',
    bestSame: '오늘 밤 최고점과 같아요',
    scoreNote: '나 자신과만 비교해요',
    voiceNudge: '오늘 밤의 목소리 카드가 도착했어요',
    voiceGo: '찾기에서 보기',
    queueTitle: '예약 목록',
    playOrder: '부르는 순서',
    moveUp: '앞으로',
    moveDown: '뒤로',
    cancel: '취소',
    cancelAgain: '한 번 더 누르면 취소',
    queueEmpty: '아직 예약이 없어요',
    mineNone: '아직 내 곡이 없어요',
    findSong: '곡 찾기',
    penTitle: '펜라이트',
    penHint: '탭해서 펜라이트 흔들기',
    penSub: '어디를 눌러도 음이 틀리지 않아요',
    penFor: '{member}에게 빛을 보내요',
    putDown: '폰 내려놓고 듣기',
    exit: '퇴실하기',
    history: '방금 전',
    crystal: '박수의 결정',
    standbyLabel: '스테이지 대기',
    standbyNone: '지금은 내 예약이 없어요',
    standbyRelax: '폰을 내려놓고 노래를 들어요',
    standbyGather: '곧 내 차례. 빛이 모이고 있어요',
    standbyNow: '내 차례예요',
    toStage: '스테이지로',
    backToFind: '찾기로 돌아가기',
    tapToReturn: '탭해서 돌아가기',
    roomSearch: '이 화면에서 찾기',
    roomLock: '기록·목소리·가져온 곡은 폰에서 열려요',
    askTitle: '이 곡, 알아요?',
    askNote: '답한 사람만 세어요',
    allKnow: '이 방의 모두가 알아요',
    shiftTitle: '흐름을 바꾸는 제안',
    shiftBody: '다음에 이 곡을 넣어요',
    shiftWaiting: '모두의 찬성 빛을 기다리는 중',
    finaleTitle: '마지막 곡',
    finaleBody: '이 방을 확실히 띄울 한 곡에 불을 밝혀요',
    showTitle: '지금 방에 보여 주는 곡',
    members: '이 방',
    air: '분위기',
    constellation: '오늘 밤의 빛자리',
    orders: '주문',
    ordersCount: '{n}건',
    'order.sending': '전송 중',
    'order.accepted': '접수됨',
    'order.preparing': '준비 중',
    'order.delivered': '전달 완료',
    ordersNone: '주문은 폰에서',
    joinQr: '폰으로 참여 (QR·설치 불필요·로그인 불필요)',
    qrNote: 'QR은 표시용 이미지예요 (데모)',
    shiftKind: '분위기의 전환점',
    ride: '흐름을 타기',
    change: '흐름을 바꾸기',
    naviPick: '내비 추천',
    insertNext: '다음에 넣기',
    next: '다음',
    tonightHeat: '오늘 밤의 열기',
    noHistory: '아직 끝난 곡이 없어요',
    agreeNote: '모두 찬성하면 다음 곡으로 들어가요',
    why: '왜 이 카드일까?',
    whyRule: '규칙: {rule}',
    hypothesis: '점선은 내비의 예측 (가설)',
  },
})

export type StageKey = Parameters<typeof S.t>[0]
