// M8 strings (namespace "search"): the search bar and sheet, the air mixer and the language
// sheet. Every key exists in all five locales with the same {variables} (checked by the i18n
// coverage test).
import { defineStrings } from '../../i18n'

export const S = defineStrings('search', {
  ja: {
    // bar
    'bar.placeholder': '曲名・歌手・ローマ字で探す',
    'bar.open': '曲を探す',
    'bar.mixer': '空気ミキサーを開く',
    // sheet
    'sheet.title': '曲を探す',
    'input.placeholder': '原題・ローマ字・現地の文字、どれでも',
    'input.clear': '入力を消す',
    'try.label': 'どの文字でも',
    'filters.evidence': '根拠',
    'filters.hypothesis': 'ナビの見立て',
    'filters.hypothesisNote': '仮説',
    'filters.clear': '解除',
    decade: '{y}年代',
    count: '{n}曲',
    'order.popular': 'よく知られている順',
    'order.match': '近い順',
    'none.title': 'ぴったりの曲が見つかりません',
    'none.hint': '原題・ローマ字・現地の文字でも探せます',
    'none.unfilter': '絞り込みを外すと{n}曲',
    'row.reserve': '予約',
    reservedN: '予約済み #{n}',
    'row.playing': '演奏中',
    'row.keep': '気になる',
    'row.kept': 'ボールに貼りました',
    'row.notReservable': '配信準備中（デモ）',
    'row.matched': '{field}で一致',
    'field.title': '原題',
    'field.artist': '歌手名',
    'field.romaji': 'ローマ字',
    'field.en': '英語',
    'field.zhHant': '繁体字',
    'field.zhHans': '簡体字',
    'field.ko': '韓国語',
    'ball.label': 'あなたのボール',
    'ball.faces': '{n}面',
    'area.label': '未踏のエリア',
    'area.name': '{tempo} × {genre}',
    'area.hint': '予約か気になるで、ここに最初の光が灯ります',
    'area.lit': 'このエリアに最初の光が灯った',
    'room.note': '部屋の画面から予約した曲には「部屋から」の札がつきます',
    // mixer
    'mixer.title': '空気ミキサー',
    'mixer.lead': '指で空気を置いて、離すと手札が配り直されます',
    'mixer.who': '誰と？',
    'who.friends': '友だち',
    'who.family': '家族',
    'who.work': '職場',
    'who.date': 'デート',
    'who.solo': 'ひとり',
    'axis.mellow': 'しっとり',
    'axis.hype': 'アガる',
    'axis.known': '知ってる',
    'axis.fresh': '新しい出会い',
    'zone.mellowKnown': '懐かしのしっとり',
    'zone.midKnown': 'みんなで口ずさむ',
    'zone.hypeKnown': '全員で叫べる定番',
    'zone.mellowMid': 'じっくり聴かせる',
    'zone.midMid': 'ちょうどいい塩梅',
    'zone.hypeMid': 'ノれる曲で温める',
    'zone.mellowFresh': 'しっとり新しい出会い',
    'zone.midFresh': 'まだ知らない名曲',
    'zone.hypeFresh': 'アガる新顔',
    'mixer.now': 'いま',
    'mixer.release': '離すと配り直し',
    'mixer.note': 'ナビの見立て（仮説）として選曲の重みに使います',
    'mixer.pad': '空気のパッド',
    'mixer.padHelp': '左右でしっとりとアガる、上下で知ってると新しい出会い。矢印キーとEnterでも操作できます',
    // language
    'lang.title': '言語',
    'lang.note': '曲名はいつも原題といっしょに。検索はどの文字でも',
    'lang.current': '表示中',
  },
  en: {
    'bar.placeholder': 'Title, artist or romaji',
    'bar.open': 'Search songs',
    'bar.mixer': 'Open the air mixer',
    'sheet.title': 'Search songs',
    'input.placeholder': 'Original title, romaji or your own script',
    'input.clear': 'Clear',
    'try.label': 'Any script',
    'filters.evidence': 'Facts',
    'filters.hypothesis': "Navi's read",
    'filters.hypothesisNote': 'hypothesis',
    'filters.clear': 'Clear',
    decade: '{y}s',
    count: '{n} songs',
    'order.popular': 'Best known first',
    'order.match': 'Best match first',
    'none.title': 'No match yet',
    'none.hint': 'Try the original title, romaji or your own script',
    'none.unfilter': 'Without filters: {n} songs',
    'row.reserve': 'Reserve',
    reservedN: 'Reserved #{n}',
    'row.playing': 'Playing now',
    'row.keep': 'Keep',
    'row.kept': 'On your ball',
    'row.notReservable': 'Not yet available here (demo)',
    'row.matched': 'Matched in {field}',
    'field.title': 'the original title',
    'field.artist': 'the artist',
    'field.romaji': 'romaji',
    'field.en': 'English',
    'field.zhHant': 'Traditional Chinese',
    'field.zhHans': 'Simplified Chinese',
    'field.ko': 'Korean',
    'ball.label': 'Your ball',
    'ball.faces': '{n} faces',
    'area.label': 'Unexplored area',
    'area.name': '{tempo} × {genre}',
    'area.hint': 'Reserve or keep one to light this area for the first time',
    'area.lit': 'The first light in this area',
    'room.note': 'Songs reserved from the room screen carry a "from the room" tag',
    'mixer.title': 'Air mixer',
    'mixer.lead': 'Place the mood with a finger. Let go and the cards are dealt again',
    'mixer.who': 'Who with?',
    'who.friends': 'Friends',
    'who.family': 'Family',
    'who.work': 'Work',
    'who.date': 'Date',
    'who.solo': 'Solo',
    'axis.mellow': 'Mellow',
    'axis.hype': 'Hype',
    'axis.known': 'Known',
    'axis.fresh': 'New finds',
    'zone.mellowKnown': 'Familiar and gentle',
    'zone.midKnown': 'Everyone hums along',
    'zone.hypeKnown': 'Anthems everyone shouts',
    'zone.mellowMid': 'Slow and heartfelt',
    'zone.midMid': 'Just right',
    'zone.hypeMid': 'Warm up with a groove',
    'zone.mellowFresh': 'Quiet discoveries',
    'zone.midFresh': 'Hidden gems',
    'zone.hypeFresh': 'Fresh bangers',
    'mixer.now': 'Now',
    'mixer.release': 'Let go to deal',
    'mixer.note': "Used as Navi's read (a hypothesis) to weight the picks",
    'mixer.pad': 'Mood pad',
    'mixer.padHelp': 'Left–right: mellow to hype. Down–up: known to new finds. Arrow keys and Enter work too',
    'lang.title': 'Language',
    'lang.note': 'Original titles always stay visible. Search works in any script',
    'lang.current': 'Current',
  },
  zhHant: {
    'bar.placeholder': '曲名・歌手・羅馬拼音',
    'bar.open': '搜尋歌曲',
    'bar.mixer': '打開氣氛混音器',
    'sheet.title': '搜尋歌曲',
    'input.placeholder': '原曲名、羅馬拼音或中文都可以',
    'input.clear': '清除',
    'try.label': '任何文字',
    'filters.evidence': '依據',
    'filters.hypothesis': '導航的推測',
    'filters.hypothesisNote': '假設',
    'filters.clear': '清除',
    decade: '{y}年代',
    count: '{n}首',
    'order.popular': '依知名度',
    'order.match': '依相符程度',
    'none.title': '找不到相符的歌曲',
    'none.hint': '也可以用原曲名、羅馬拼音或中文搜尋',
    'none.unfilter': '取消篩選有{n}首',
    'row.reserve': '點歌',
    reservedN: '已點歌 #{n}',
    'row.playing': '演唱中',
    'row.keep': '收藏',
    'row.kept': '已貼在你的球上',
    'row.notReservable': '本店準備中（示意）',
    'row.matched': '符合{field}',
    'field.title': '原曲名',
    'field.artist': '歌手名',
    'field.romaji': '羅馬拼音',
    'field.en': '英文',
    'field.zhHant': '繁體中文',
    'field.zhHans': '簡體中文',
    'field.ko': '韓文',
    'ball.label': '你的球',
    'ball.faces': '{n}面',
    'area.label': '未探索的區域',
    'area.name': '{tempo} × {genre}',
    'area.hint': '點歌或收藏一首，這裡就會亮起第一道光',
    'area.lit': '這個區域亮起了第一道光',
    'room.note': '從包廂畫面點的歌會標上「來自包廂」',
    'mixer.title': '氣氛混音器',
    'mixer.lead': '用手指放下氣氛，放開就會重新發牌',
    'mixer.who': '和誰？',
    'who.friends': '朋友',
    'who.family': '家人',
    'who.work': '同事',
    'who.date': '約會',
    'who.solo': '一個人',
    'axis.mellow': '抒情',
    'axis.hype': '嗨翻',
    'axis.known': '熟悉的歌',
    'axis.fresh': '新發現',
    'zone.mellowKnown': '熟悉的抒情',
    'zone.midKnown': '大家一起哼',
    'zone.hypeKnown': '大家都會吼的經典',
    'zone.mellowMid': '慢慢唱給你聽',
    'zone.midMid': '剛剛好',
    'zone.hypeMid': '用律動熱場',
    'zone.mellowFresh': '抒情的新發現',
    'zone.midFresh': '還不知道的好歌',
    'zone.hypeFresh': '嗨翻的新歌',
    'mixer.now': '現在',
    'mixer.release': '放開就重發',
    'mixer.note': '作為導航的推測（假設）用於選曲權重',
    'mixer.pad': '氣氛觸控板',
    'mixer.padHelp': '左右是抒情到嗨翻，上下是熟悉到新發現。也可以用方向鍵和Enter操作',
    'lang.title': '語言',
    'lang.note': '曲名一律附上原曲名，任何文字都能搜尋',
    'lang.current': '使用中',
  },
  zhHans: {
    'bar.placeholder': '曲名・歌手・罗马拼音',
    'bar.open': '搜索歌曲',
    'bar.mixer': '打开气氛混音器',
    'sheet.title': '搜索歌曲',
    'input.placeholder': '原曲名、罗马拼音或中文都可以',
    'input.clear': '清除',
    'try.label': '任何文字',
    'filters.evidence': '依据',
    'filters.hypothesis': '导航的推测',
    'filters.hypothesisNote': '假设',
    'filters.clear': '清除',
    decade: '{y}年代',
    count: '{n}首',
    'order.popular': '按知名度',
    'order.match': '按匹配度',
    'none.title': '没有找到相符的歌曲',
    'none.hint': '也可以用原曲名、罗马拼音或中文搜索',
    'none.unfilter': '取消筛选有{n}首',
    'row.reserve': '点歌',
    reservedN: '已点歌 #{n}',
    'row.playing': '演唱中',
    'row.keep': '收藏',
    'row.kept': '已贴在你的球上',
    'row.notReservable': '本店准备中（示意）',
    'row.matched': '符合{field}',
    'field.title': '原曲名',
    'field.artist': '歌手名',
    'field.romaji': '罗马拼音',
    'field.en': '英文',
    'field.zhHant': '繁体中文',
    'field.zhHans': '简体中文',
    'field.ko': '韩文',
    'ball.label': '你的球',
    'ball.faces': '{n}面',
    'area.label': '未探索的区域',
    'area.name': '{tempo} × {genre}',
    'area.hint': '点歌或收藏一首，这里就会亮起第一道光',
    'area.lit': '这个区域亮起了第一道光',
    'room.note': '从包厢画面点的歌会标上“来自包厢”',
    'mixer.title': '气氛混音器',
    'mixer.lead': '用手指放下气氛，松开就会重新发牌',
    'mixer.who': '和谁？',
    'who.friends': '朋友',
    'who.family': '家人',
    'who.work': '同事',
    'who.date': '约会',
    'who.solo': '一个人',
    'axis.mellow': '抒情',
    'axis.hype': '嗨翻',
    'axis.known': '熟悉的歌',
    'axis.fresh': '新发现',
    'zone.mellowKnown': '熟悉的抒情',
    'zone.midKnown': '大家一起哼',
    'zone.hypeKnown': '大家都会吼的经典',
    'zone.mellowMid': '慢慢唱给你听',
    'zone.midMid': '刚刚好',
    'zone.hypeMid': '用律动热场',
    'zone.mellowFresh': '抒情的新发现',
    'zone.midFresh': '还不知道的好歌',
    'zone.hypeFresh': '嗨翻的新歌',
    'mixer.now': '现在',
    'mixer.release': '松开就重发',
    'mixer.note': '作为导航的推测（假设）用于选曲权重',
    'mixer.pad': '气氛触控板',
    'mixer.padHelp': '左右是抒情到嗨翻，上下是熟悉到新发现。也可以用方向键和Enter操作',
    'lang.title': '语言',
    'lang.note': '曲名一律附上原曲名，任何文字都能搜索',
    'lang.current': '使用中',
  },
  ko: {
    'bar.placeholder': '곡명·가수·로마자로 찾기',
    'bar.open': '노래 찾기',
    'bar.mixer': '분위기 믹서 열기',
    'sheet.title': '노래 찾기',
    'input.placeholder': '원제, 로마자, 한글 모두 OK',
    'input.clear': '지우기',
    'try.label': '어떤 문자로도',
    'filters.evidence': '근거',
    'filters.hypothesis': '내비의 추측',
    'filters.hypothesisNote': '가설',
    'filters.clear': '해제',
    decade: '{y}년대',
    count: '{n}곡',
    'order.popular': '많이 알려진 순',
    'order.match': '잘 맞는 순',
    'none.title': '딱 맞는 곡이 아직 없어요',
    'none.hint': '원제, 로마자, 한글로도 찾을 수 있어요',
    'none.unfilter': '필터를 해제하면 {n}곡',
    'row.reserve': '예약',
    reservedN: '예약됨 #{n}',
    'row.playing': '지금 재생 중',
    'row.keep': '찜하기',
    'row.kept': '내 볼에 붙였어요',
    'row.notReservable': '이 매장은 준비 중 (데모)',
    'row.matched': '{field} 일치',
    'field.title': '원제',
    'field.artist': '가수명',
    'field.romaji': '로마자',
    'field.en': '영어',
    'field.zhHant': '번체',
    'field.zhHans': '간체',
    'field.ko': '한국어',
    'ball.label': '내 볼',
    'ball.faces': '{n}면',
    'area.label': '미개척 영역',
    'area.name': '{tempo} × {genre}',
    'area.hint': '예약하거나 찜하면 이곳에 첫 빛이 켜져요',
    'area.lit': '이 영역에 첫 빛이 켜졌어요',
    'room.note': '룸 화면에서 예약한 곡에는 "룸에서" 표시가 붙어요',
    'mixer.title': '분위기 믹서',
    'mixer.lead': '손가락으로 분위기를 놓고, 떼면 카드를 다시 나눠요',
    'mixer.who': '누구랑?',
    'who.friends': '친구',
    'who.family': '가족',
    'who.work': '직장',
    'who.date': '데이트',
    'who.solo': '혼자',
    'axis.mellow': '잔잔하게',
    'axis.hype': '신나게',
    'axis.known': '아는 곡',
    'axis.fresh': '새로운 만남',
    'zone.mellowKnown': '익숙하고 잔잔하게',
    'zone.midKnown': '다 같이 흥얼흥얼',
    'zone.hypeKnown': '다 같이 외치는 명곡',
    'zone.mellowMid': '차분하게 들려주기',
    'zone.midMid': '딱 좋은 느낌',
    'zone.hypeMid': '그루브로 달구기',
    'zone.mellowFresh': '잔잔한 새 발견',
    'zone.midFresh': '아직 모르는 명곡',
    'zone.hypeFresh': '신나는 새 얼굴',
    'mixer.now': '지금',
    'mixer.release': '떼면 다시 나눠요',
    'mixer.note': '내비의 추측(가설)으로 선곡 가중치에 써요',
    'mixer.pad': '분위기 패드',
    'mixer.padHelp': '좌우는 잔잔하게에서 신나게, 상하는 아는 곡에서 새로운 만남. 방향키와 Enter로도 조작할 수 있어요',
    'lang.title': '언어',
    'lang.note': '곡명은 항상 원제와 함께. 검색은 어떤 문자로도',
    'lang.current': '사용 중',
  },
})
