// M9 record-wrap strings (namespace "record"): the collection screen, face and night sheets,
// the wall constellation, tonight's recap (wrap) and the optional survey. Every key exists in
// all five locales with the same {variables}. Night names ("金曜の琥珀ハモリ座") are generated
// per weekday × base colour × symbol so a stored name re-resolves in any language.
// Never streaks, scarcity or "does not know" (SPEC D-15, E-12).
import { defineStrings, type Locale } from '../../i18n'

type Dict = Record<string, string>

const ja: Dict = {
  'screen.aria': '記録',
  'hero.title': 'あなたのミラーボール',
  'hero.lit': '面が点灯',
  'hero.of': '全{total}曲のボール',
  'hero.hint': '指で回す・光る面をタップで詳細',
  'hero.empty': '札を右に払うと、最初の面が貼られます',
  'hero.tonight': '今夜 +{n}',
  'bye.title': 'またね',
  'bye.body': '今夜の光は、このボールに刻まれました。次の来店は「おかえり」から始まります。',
  'bye.linked': 'マイうたに持ち帰りました（デモ）',
  'bye.local': 'この端末に残しました',

  'faces.title': '面の内訳',
  'faces.total': '{n}面',
  'state.sketch': 'スケッチ',
  'state.neon': 'ネオン',
  'state.mirror': 'ミラー',
  'state.prism': 'プリズム',
  'how.sketch': '気になる・持ち込み',
  'how.neon': '予約した',
  'how.mirror': '歌った',
  'how.prism': '全員が知ってる曲を歌った',
  'marks.title': '刻印の見方',
  'mark.key': 'キー',
  'mark.stitch': '縫い目',
  'mark.duet': '2色',
  'mark.seal': '封蝋',
  'mark.visa': '査証',
  'mark.navi': '金の点',
  'mark.gold': '金縁',
  'mark.twin': '2つの点',
  'markHow.key': 'キーを指定して予約した',
  'markHow.stitch': '持ち込みから保存した',
  'markHow.duet': 'デュエットで歌った',
  'markHow.seal': 'リクエストに応えて歌った',
  'markHow.visa': '越境の札から予約した',
  'markHow.navi': 'ナビのおすすめ札で予約した',
  'markHow.gold': '締めの1曲で歌った・100点（デモ）',
  'markHow.twin': '二重星を秘密のままにした（あなたにだけ見える）',

  'sleep.title': '寝ている面',
  'sleep.body': '最後に歌ってから60日以上。見た目も中身も、何も失われません。',
  'sleep.last': '前回 {date}',
  'sleep.polish': '磨き直す',

  'tonight.title': '今夜の光座',
  'tonight.sub': 'ボールが今夜、壁に投げた光',

  'gaps.title': 'まだ暗いエリア',
  'gaps.body': '開くと、そのエリアで絞り込んだ検索へ。予約すると初めて面が灯ります',
  'gaps.area': '{tempo} × {genre}',
  'gaps.n': '{n}曲',
  'gaps.open': '開く',
  'gaps.none': 'すべてのエリアに光が灯りました',
  'tempo.fast': '北',
  'tempo.mid': '赤道',
  'tempo.slow': '南',

  'pins.title': 'ピン',
  'pins.body': '取り方はすべて公開。期限もレア度もありません',
  'pins.got': '{n} / 10',
  'pins.at': '{date} に取得',
  'pin.spark': '口火',
  'pin.allKnow': '全員ソング',
  'pin.airRead': '空気読み',
  'pin.crossing': '越境',
  'pin.harmony': 'ハーモニー',
  'pin.answer': '応えた',
  'pin.importer': '持ち込み',
  'pin.polish': '磨き直し',
  'pin.hundred': '100点',
  'pin.faces30': '30面',
  'pinHow.spark': 'その夜の最初の予約をした',
  'pinHow.allKnow': '全員が知っていた曲を歌った',
  'pinHow.airRead': '空気の変わり目で差し込んだ曲のあと、熱が上がった',
  'pinHow.crossing': '越境の札の曲を歌った',
  'pinHow.harmony': 'デュエットで歌った',
  'pinHow.answer': 'リクエストに応えて歌った',
  'pinHow.importer': '持ち込み候補を3曲マイうたに保存した',
  'pinHow.polish': '寝ている面を歌い直した',
  'pinHow.hundred': '採点（デモ）で100点を出した',
  'pinHow.faces30': 'ボールの点灯面が30枚になった',

  'cal.title': 'カレンダー',
  'cal.body': 'スタンプを押した夜が並びます。タップでその夜のページへ',
  'cal.prev': '前の月',
  'cal.next': '次の月',
  'cal.today': '今日',
  'cal.press': '長押し',

  'nights.title': '夜のページ',
  'nights.demo': 'デモ用データ',
  'nights.tonight': '今夜',
  'nights.faces': '面 +{n}',
  'nights.sung': '{n}曲',

  'voice.title': '声の記録',
  'voice.note': '声は曲や日によって変わります',
  'voice.was': '今回の声は{type}',
  'voice.power': '迫力',
  'voice.care': '丁寧さ',
  'voice.bright': '明るさ',

  'saved.title': 'マイうた',
  'saved.body': '保存した曲は、次の来店の最初の手札に入ります',
  'saved.from.import': '持ち込み',
  'saved.from.face': 'ボール',
  'saved.from.wrap': '今夜',
  'saved.reserve': '予約',

  'set.title': '設定',
  'set.lang': '言語',
  'set.sound': '効果音',
  'set.on': 'オン',
  'set.off': 'オフ',
  'set.link': 'マイうた連携',
  'set.linked': '持ち帰り中（デモ・擬似ログイン）',
  'set.local': 'この端末だけ',
  'set.wipe': 'この端末のデータを消去',
  'set.wipeAsk': '面・ピン・夜のページ・マイうたを、この端末から消去します。元には戻せません。',
  'set.wipeYes': '消去する',
  'set.wipeNo': 'やめる',
  'set.wiped': 'この端末のデータを消去しました',

  'face.first': '初めて貼った夜',
  'face.sung': '歌った回数',
  'face.sungN': '{n}回',
  'face.key': '推奨キー',
  'face.keyDown': '−{n}',
  'face.keyUp': '+{n}',
  'face.keyOrig': '原曲キー',
  'face.keyNone': '声チェック後に',
  'face.keyFromVoice': '声の記録から（仮説）',
  'face.keyFromReserve': '予約したキー',
  'face.marks': 'この面の刻印',
  'face.noMarks': 'まだ刻印はありません',
  'face.again': 'また予約',
  'face.queued': '予約済み #{n}',
  'face.playing': 'いま演奏中',
  'face.sleeping': '眠っている面（前回 {date}）',
  'face.rubHint': '面を指で3回こすって、磨き直す',
  'face.polished': '光り直しました。次に歌うとピン「磨き直し」',
  'face.ask': '誰かに歌ってほしい',
  'face.askWho': '誰に届けますか？',
  'face.askSent': '{member}に届きました',
  'face.askNote': '返事は表示しません。歌ってくれたら予約列に出ます',
  'face.noFace': 'この曲の面は、まだ暗いまま',
  'face.nobody': 'いまは届けられる人がいません',

  'night.date': '{date}の夜',
  'night.faces': 'この夜に貼った面',
  'night.mine': 'あなたが歌った曲',
  'night.none': 'この夜は、まだ歌った記録がありません',
  'night.play': 'メロディを聴く',
  'night.notes': '{n}音',

  'wrap.title': '今夜のまとめ',
  'wrap.skip': 'とばす',
  'wrap.tap': 'タップで次へ',
  'wrap.p1': '今夜の面',
  'wrap.p2': '今夜の声',
  'wrap.p3': 'みんなの共通曲',
  'wrap.p4': '今夜の光座',
  'wrap.p5': 'スタンプ',
  'wrap.facesHead': '今夜、{n}枚の面が灯った',
  'wrap.facesNone': '今夜は、眺めて楽しむ夜',
  'wrap.facesSub': 'ボールに、今夜の光が貼られました',
  'wrap.voiceType': '今回の声は{type}',
  'wrap.voiceNone': '今夜は声を測りませんでした',
  'wrap.voiceNoneSub': '次の夜は、3秒ハミングか3つの質問で',
  'wrap.claps': 'もらった拍手の光',
  'wrap.clapsNone': 'ペンライトの光は、歌った人に届きます',
  'wrap.sang': '今夜あなたが歌った曲',
  'wrap.commonHead': '{n}人全員が知ってた曲',
  'wrap.commonNone': '全員がそろう曲は、次の夜に',
  'wrap.commonNoneSub': '「部屋に聞く」で、共通曲が見つかります',
  'wrap.nameLead': '今夜の光座に、名前がつきました',
  'wrap.play': 'もう一度聴く',
  'wrap.melody': '今夜のメロディ・{n}音',
  'wrap.noMelody': '面が変わるたびに、旋律が1音ずつ伸びます',
  'wrap.stampHead': '今日の枠を長押しして、スタンプを押す',
  'wrap.stampDone': 'スタンプを押しました',
  'wrap.save': 'マイうたに持ち帰る',
  'wrap.saveSub': '今夜の{n}曲と続きを（デモ）',
  'wrap.nosave': 'この端末だけに残す',
  'wrap.nosaveSub': 'ボールはこの端末で育つ',

  'sv.title': '5つの質問（任意）',
  'sv.lead': '答えなくても大丈夫。試作の改善にだけ使います',
  'sv.q1': '曲は見つけやすかった？',
  'sv.q2': '意外な発見はあった？',
  'sv.q3': '選ぶのは楽しかった？',
  'sv.q4': '次も使いたい？',
  'sv.q5': 'そう感じた理由（いくつでも）',
  'sv.lo': 'あまり',
  'sv.hi': 'とても',
  'sv.why.cards': '札をめくるのが楽しい',
  'sv.why.know': '全員が知ってる曲が分かる',
  'sv.why.ball': 'ボールが育つ',
  'sv.why.voice': '声の札',
  'sv.why.lang': '自分の言語で使える',
  'sv.why.lane': '予約列が見やすい',
  'sv.why.order': '注文がかんたん',
  'sv.send': '送る',
  'sv.skip': '答えずに閉じる',
  'sv.thanks': 'ありがとう。次の夜に活かします',

  'wc.aria': '壁の光座：{n}点',
  'wc.empty': '最初の曲が終わると、ここに光が灯ります',
  'wc.m.shift': '転換点',
  'wc.m.toast': '乾杯',
  'wc.m.navi': 'ナビの札',
  'wc.m.allKnow': '全員',
  'wc.m.join': '合流',
}

const en: Dict = {
  'screen.aria': 'Collection',
  'hero.title': 'Your mirror ball',
  'hero.lit': 'faces lit',
  'hero.of': 'a ball of {total} songs',
  'hero.hint': 'Spin it with a finger · tap a lit face for details',
  'hero.empty': 'Flick a card right to stick your first face on',
  'hero.tonight': 'Tonight +{n}',
  'bye.title': 'See you',
  'bye.body': 'Tonight’s light stays on this ball. Your next visit starts with “welcome back”.',
  'bye.linked': 'Taken home to My Songs (demo)',
  'bye.local': 'Kept on this device',

  'faces.title': 'Faces',
  'faces.total': '{n} faces',
  'state.sketch': 'Sketch',
  'state.neon': 'Neon',
  'state.mirror': 'Mirror',
  'state.prism': 'Prism',
  'how.sketch': 'Kept or brought along',
  'how.neon': 'Reserved',
  'how.mirror': 'Sang it',
  'how.prism': 'Sang a song everyone knew',
  'marks.title': 'What the marks mean',
  'mark.key': 'Key',
  'mark.stitch': 'Stitch',
  'mark.duet': 'Two-tone',
  'mark.seal': 'Wax seal',
  'mark.visa': 'Visa',
  'mark.navi': 'Gold dot',
  'mark.gold': 'Gold rim',
  'mark.twin': 'Twin dots',
  'markHow.key': 'Reserved with a key change',
  'markHow.stitch': 'Saved from your brought-along songs',
  'markHow.duet': 'Sang it as a duet',
  'markHow.seal': 'Sang it on request',
  'markHow.visa': 'Reserved from a crossing card',
  'markHow.navi': 'Reserved with the navi’s pick tag',
  'markHow.gold': 'Sang the closing song, or scored 100 (demo)',
  'markHow.twin': 'Kept a twin star secret (only you see this)',

  'sleep.title': 'Sleeping faces',
  'sleep.body': 'Not sung for 60+ days. Nothing fades and nothing is lost.',
  'sleep.last': 'last {date}',
  'sleep.polish': 'Polish',

  'tonight.title': 'Tonight’s wall of light',
  'tonight.sub': 'The light your ball threw on the wall tonight',

  'gaps.title': 'Still-dark areas',
  'gaps.body': 'Open one to search inside it. Reserve there and its first face lights up',
  'gaps.area': '{tempo} × {genre}',
  'gaps.n': '{n} songs',
  'gaps.open': 'Open',
  'gaps.none': 'Every area has a light now',
  'tempo.fast': 'North',
  'tempo.mid': 'Equator',
  'tempo.slow': 'South',

  'pins.title': 'Pins',
  'pins.body': 'Every condition is public. No deadlines, no rarity',
  'pins.got': '{n} / 10',
  'pins.at': 'earned {date}',
  'pin.spark': 'Spark',
  'pin.allKnow': 'Everyone’s Song',
  'pin.airRead': 'Mood Reader',
  'pin.crossing': 'Border Crosser',
  'pin.harmony': 'Harmony',
  'pin.answer': 'Answered',
  'pin.importer': 'Brought Along',
  'pin.polish': 'Polished',
  'pin.hundred': '100 Points',
  'pin.faces30': '30 Faces',
  'pinHow.spark': 'Made the first reservation of the night',
  'pinHow.allKnow': 'Sang a song everyone in the room knew',
  'pinHow.airRead': 'The room warmed up after a song you slotted in at a turning point',
  'pinHow.crossing': 'Sang a song from a crossing card',
  'pinHow.harmony': 'Sang a duet',
  'pinHow.answer': 'Sang a song someone requested',
  'pinHow.importer': 'Saved 3 brought-along songs to My Songs',
  'pinHow.polish': 'Sang a sleeping face again',
  'pinHow.hundred': 'Scored 100 in the demo score',
  'pinHow.faces30': 'Lit 30 faces on your ball',

  'cal.title': 'Calendar',
  'cal.body': 'Stamped nights line up here. Tap one to open that night',
  'cal.prev': 'Previous month',
  'cal.next': 'Next month',
  'cal.today': 'Today',
  'cal.press': 'Hold',

  'nights.title': 'Night pages',
  'nights.demo': 'Demo data',
  'nights.tonight': 'Tonight',
  'nights.faces': '+{n} faces',
  'nights.sung': '{n} songs',

  'voice.title': 'Voice log',
  'voice.note': 'Your voice changes with the song and the day',
  'voice.was': 'This time: {type}',
  'voice.power': 'Power',
  'voice.care': 'Care',
  'voice.bright': 'Brightness',

  'saved.title': 'My Songs',
  'saved.body': 'Saved songs join the first hand of your next visit',
  'saved.from.import': 'Brought along',
  'saved.from.face': 'From the ball',
  'saved.from.wrap': 'Tonight',
  'saved.reserve': 'Reserve',

  'set.title': 'Settings',
  'set.lang': 'Language',
  'set.sound': 'Sound effects',
  'set.on': 'On',
  'set.off': 'Off',
  'set.link': 'My Songs link',
  'set.linked': 'Taking it home (demo sign-in)',
  'set.local': 'This device only',
  'set.wipe': 'Clear this device’s data',
  'set.wipeAsk': 'Faces, pins, night pages and My Songs will be erased from this device. This cannot be undone.',
  'set.wipeYes': 'Erase',
  'set.wipeNo': 'Cancel',
  'set.wiped': 'This device’s data was cleared',

  'face.first': 'First night',
  'face.sung': 'Times sung',
  'face.sungN': '{n}×',
  'face.key': 'Suggested key',
  'face.keyDown': '−{n}',
  'face.keyUp': '+{n}',
  'face.keyOrig': 'Original key',
  'face.keyNone': 'After a voice check',
  'face.keyFromVoice': 'From your voice log (hypothesis)',
  'face.keyFromReserve': 'The key you reserved',
  'face.marks': 'Marks on this face',
  'face.noMarks': 'No marks yet',
  'face.again': 'Reserve again',
  'face.queued': 'Reserved #{n}',
  'face.playing': 'Playing now',
  'face.sleeping': 'A sleeping face (last sung {date})',
  'face.rubHint': 'Rub the face three times to polish it',
  'face.polished': 'Shining again. Sing it next time for the “Polished” pin',
  'face.ask': 'I’d love someone to sing this',
  'face.askWho': 'Who should get it?',
  'face.askSent': 'Sent to {member}',
  'face.askNote': 'No reply is shown. If they sing it, it appears in the queue',
  'face.noFace': 'This song’s face is still dark',
  'face.nobody': 'Nobody to send it to right now',

  'night.date': 'The night of {date}',
  'night.faces': 'Faces from this night',
  'night.mine': 'Songs you sang',
  'night.none': 'No songs sung on this night yet',
  'night.play': 'Play the melody',
  'night.notes': '{n} notes',

  'wrap.title': 'Tonight’s recap',
  'wrap.skip': 'Skip',
  'wrap.tap': 'Tap for next',
  'wrap.p1': 'Tonight’s faces',
  'wrap.p2': 'Tonight’s voice',
  'wrap.p3': 'Songs everyone knew',
  'wrap.p4': 'Tonight’s wall of light',
  'wrap.p5': 'Stamp',
  'wrap.facesHead': '{n} faces lit up tonight',
  'wrap.facesNone': 'A night for watching and listening',
  'wrap.facesSub': 'Tonight’s light is now part of your ball',
  'wrap.voiceType': 'This time your voice was {type}',
  'wrap.voiceNone': 'No voice check tonight',
  'wrap.voiceNoneSub': 'Next time: a 3-second hum or three questions',
  'wrap.claps': 'Applause light you received',
  'wrap.clapsNone': 'Penlight glow goes to whoever is singing',
  'wrap.sang': 'Songs you sang tonight',
  'wrap.commonHead': 'Songs all {n} of you knew',
  'wrap.commonNone': 'A song everyone knows — next night',
  'wrap.commonNoneSub': '“Ask the room” finds your shared songs',
  'wrap.nameLead': 'Tonight’s wall of light has a name',
  'wrap.play': 'Play again',
  'wrap.melody': 'Tonight’s melody · {n} notes',
  'wrap.noMelody': 'Every face that changes adds one note to the tune',
  'wrap.stampHead': 'Press and hold today to stamp it',
  'wrap.stampDone': 'Stamped',
  'wrap.save': 'Take it home to My Songs',
  'wrap.saveSub': 'Tonight’s {n} songs and where you left off (demo)',
  'wrap.nosave': 'Keep it on this device',
  'wrap.nosaveSub': 'Your ball keeps growing on this device',

  'sv.title': 'Five questions (optional)',
  'sv.lead': 'Skipping is fine. Answers only help improve this prototype',
  'sv.q1': 'Was it easy to find songs?',
  'sv.q2': 'Did you discover something unexpected?',
  'sv.q3': 'Was choosing fun?',
  'sv.q4': 'Would you use it again?',
  'sv.q5': 'Why do you feel that way? (pick any)',
  'sv.lo': 'Not really',
  'sv.hi': 'Very',
  'sv.why.cards': 'Flipping cards is fun',
  'sv.why.know': 'I see what everyone knows',
  'sv.why.ball': 'The ball grows',
  'sv.why.voice': 'The voice card',
  'sv.why.lang': 'Works in my language',
  'sv.why.lane': 'The queue is easy to see',
  'sv.why.order': 'Ordering is easy',
  'sv.send': 'Send',
  'sv.skip': 'Close without answering',
  'sv.thanks': 'Thank you. We’ll put it to use next night',

  'wc.aria': 'Wall of light: {n} points',
  'wc.empty': 'When the first song ends, a light appears here',
  'wc.m.shift': 'Turning point',
  'wc.m.toast': 'Toast',
  'wc.m.navi': 'Navi’s pick',
  'wc.m.allKnow': 'Everyone',
  'wc.m.join': 'Joined',
}

const zhHant: Dict = {
  'screen.aria': '紀錄',
  'hero.title': '你的鏡面球',
  'hero.lit': '面已點亮',
  'hero.of': '共{total}首歌的球',
  'hero.hint': '用手指轉動・點亮起的面看詳情',
  'hero.empty': '把卡片往右滑，就會貼上第一面',
  'hero.tonight': '今晚 +{n}',
  'bye.title': '下次見',
  'bye.body': '今晚的光留在這顆球上了。下次來店會從「歡迎回來」開始。',
  'bye.linked': '已帶回我的歌單（示意）',
  'bye.local': '已保留在這台裝置',

  'faces.title': '面的組成',
  'faces.total': '{n}面',
  'state.sketch': '素描',
  'state.neon': '霓虹',
  'state.mirror': '鏡面',
  'state.prism': '稜鏡',
  'how.sketch': '收藏・帶來',
  'how.neon': '點了歌',
  'how.mirror': '唱過了',
  'how.prism': '唱了全員都會的歌',
  'marks.title': '刻印說明',
  'mark.key': '調性',
  'mark.stitch': '縫線',
  'mark.duet': '雙色',
  'mark.seal': '封蠟',
  'mark.visa': '簽證',
  'mark.navi': '金點',
  'mark.gold': '金框',
  'mark.twin': '雙點',
  'markHow.key': '指定調性點歌',
  'markHow.stitch': '從帶來的歌中儲存',
  'markHow.duet': '以對唱方式演唱',
  'markHow.seal': '回應點播演唱',
  'markHow.visa': '從越境卡片點歌',
  'markHow.navi': '以導航推薦標籤點歌',
  'markHow.gold': '唱了壓軸曲，或拿到100分（示意）',
  'markHow.twin': '讓雙星保持秘密（只有你看得到）',

  'sleep.title': '沉睡的面',
  'sleep.body': '超過60天沒唱。外觀和內容都不會失去任何東西。',
  'sleep.last': '上次 {date}',
  'sleep.polish': '重新擦亮',

  'tonight.title': '今晚的光座',
  'tonight.sub': '球今晚投射在牆上的光',

  'gaps.title': '還沒點亮的區域',
  'gaps.body': '打開就會以該區域篩選搜尋。點歌後第一面就會亮起',
  'gaps.area': '{tempo} × {genre}',
  'gaps.n': '{n}首',
  'gaps.open': '打開',
  'gaps.none': '所有區域都亮起來了',
  'tempo.fast': '北',
  'tempo.mid': '赤道',
  'tempo.slow': '南',

  'pins.title': '徽章',
  'pins.body': '取得條件全部公開。沒有期限，也沒有稀有度',
  'pins.got': '{n} / 10',
  'pins.at': '{date} 取得',
  'pin.spark': '點火',
  'pin.allKnow': '全員之歌',
  'pin.airRead': '讀空氣',
  'pin.crossing': '越境',
  'pin.harmony': '和聲',
  'pin.answer': '回應',
  'pin.importer': '帶歌入場',
  'pin.polish': '重新擦亮',
  'pin.hundred': '100分',
  'pin.faces30': '30面',
  'pinHow.spark': '點了當晚的第一首歌',
  'pinHow.allKnow': '唱了全員都會的歌',
  'pinHow.airRead': '在氣氛轉折時插播的歌之後，氣氛升溫了',
  'pinHow.crossing': '唱了越境卡片的歌',
  'pinHow.harmony': '唱了一首對唱曲',
  'pinHow.answer': '回應點播唱了歌',
  'pinHow.importer': '把3首帶來的候選歌存進我的歌單',
  'pinHow.polish': '重新唱了沉睡的面',
  'pinHow.hundred': '在評分（示意）中拿到100分',
  'pinHow.faces30': '球上點亮了30面',

  'cal.title': '月曆',
  'cal.body': '蓋了章的夜晚會排在這裡。點一下打開那一晚',
  'cal.prev': '上個月',
  'cal.next': '下個月',
  'cal.today': '今天',
  'cal.press': '長按',

  'nights.title': '夜晚頁面',
  'nights.demo': '示意用資料',
  'nights.tonight': '今晚',
  'nights.faces': '面 +{n}',
  'nights.sung': '{n}首',

  'voice.title': '聲音紀錄',
  'voice.note': '聲音會隨歌曲和日子而改變',
  'voice.was': '這次的聲音是{type}',
  'voice.power': '魄力',
  'voice.care': '細膩',
  'voice.bright': '明亮',

  'saved.title': '我的歌單',
  'saved.body': '儲存的歌會放進下次來店的第一手牌',
  'saved.from.import': '帶來的歌',
  'saved.from.face': '球',
  'saved.from.wrap': '今晚',
  'saved.reserve': '點歌',

  'set.title': '設定',
  'set.lang': '語言',
  'set.sound': '音效',
  'set.on': '開',
  'set.off': '關',
  'set.link': '我的歌單連動',
  'set.linked': '帶回中（示意・模擬登入）',
  'set.local': '只在這台裝置',
  'set.wipe': '清除這台裝置的資料',
  'set.wipeAsk': '將從這台裝置清除面、徽章、夜晚頁面和我的歌單。無法復原。',
  'set.wipeYes': '清除',
  'set.wipeNo': '取消',
  'set.wiped': '已清除這台裝置的資料',

  'face.first': '第一次貼上的夜晚',
  'face.sung': '唱過的次數',
  'face.sungN': '{n}次',
  'face.key': '建議調性',
  'face.keyDown': '−{n}',
  'face.keyUp': '+{n}',
  'face.keyOrig': '原調',
  'face.keyNone': '聲音檢查之後',
  'face.keyFromVoice': '來自聲音紀錄（假設）',
  'face.keyFromReserve': '點歌時的調性',
  'face.marks': '這一面的刻印',
  'face.noMarks': '還沒有刻印',
  'face.again': '再點一次',
  'face.queued': '已點歌 #{n}',
  'face.playing': '正在播放',
  'face.sleeping': '沉睡的面（上次 {date}）',
  'face.rubHint': '用手指擦這一面3次，重新擦亮',
  'face.polished': '重新亮起來了。下次唱就能拿到徽章「重新擦亮」',
  'face.ask': '想請人唱這首',
  'face.askWho': '要送給誰？',
  'face.askSent': '已送達給{member}',
  'face.askNote': '不會顯示回覆。對方唱的話會出現在點歌列',
  'face.noFace': '這首歌的面還是暗的',
  'face.nobody': '現在沒有可以送達的人',

  'night.date': '{date}的夜晚',
  'night.faces': '這一晚貼上的面',
  'night.mine': '你唱的歌',
  'night.none': '這一晚還沒有唱歌的紀錄',
  'night.play': '聽旋律',
  'night.notes': '{n}個音',

  'wrap.title': '今晚的回顧',
  'wrap.skip': '略過',
  'wrap.tap': '點一下看下一頁',
  'wrap.p1': '今晚的面',
  'wrap.p2': '今晚的聲音',
  'wrap.p3': '大家的共同曲',
  'wrap.p4': '今晚的光座',
  'wrap.p5': '蓋章',
  'wrap.facesHead': '今晚亮起了{n}面',
  'wrap.facesNone': '今晚是欣賞的夜晚',
  'wrap.facesSub': '今晚的光已貼在球上',
  'wrap.voiceType': '這次的聲音是{type}',
  'wrap.voiceNone': '今晚沒有檢查聲音',
  'wrap.voiceNoneSub': '下次可以用3秒哼唱或3個問題',
  'wrap.claps': '收到的掌聲之光',
  'wrap.clapsNone': '螢光棒的光會送給正在唱的人',
  'wrap.sang': '今晚你唱的歌',
  'wrap.commonHead': '{n}人全員都會的歌',
  'wrap.commonNone': '全員都會的歌，留到下個夜晚',
  'wrap.commonNoneSub': '用「問問大家」就能找到共同曲',
  'wrap.nameLead': '今晚的光座有了名字',
  'wrap.play': '再聽一次',
  'wrap.melody': '今晚的旋律・{n}個音',
  'wrap.noMelody': '每當面有變化，旋律就多一個音',
  'wrap.stampHead': '長按今天的格子來蓋章',
  'wrap.stampDone': '蓋好章了',
  'wrap.save': '帶回我的歌單',
  'wrap.saveSub': '今晚的{n}首歌和進度（示意）',
  'wrap.nosave': '只留在這台裝置',
  'wrap.nosaveSub': '球會在這台裝置上繼續長大',

  'sv.title': '5個問題（可不回答）',
  'sv.lead': '不回答也沒關係。只用於改善這個試作',
  'sv.q1': '容易找到歌嗎？',
  'sv.q2': '有意外的發現嗎？',
  'sv.q3': '選歌有趣嗎？',
  'sv.q4': '下次還想用嗎？',
  'sv.q5': '這樣覺得的理由（可複選）',
  'sv.lo': '不太',
  'sv.hi': '非常',
  'sv.why.cards': '翻卡片很有趣',
  'sv.why.know': '知道全員都會的歌',
  'sv.why.ball': '球會長大',
  'sv.why.voice': '聲音卡片',
  'sv.why.lang': '能用自己的語言',
  'sv.why.lane': '點歌列很清楚',
  'sv.why.order': '點餐很簡單',
  'sv.send': '送出',
  'sv.skip': '不回答並關閉',
  'sv.thanks': '謝謝。會用在下一個夜晚',

  'wc.aria': '牆上的光座：{n}點',
  'wc.empty': '第一首歌結束後，這裡會亮起光',
  'wc.m.shift': '轉折點',
  'wc.m.toast': '乾杯',
  'wc.m.navi': '導航推薦',
  'wc.m.allKnow': '全員',
  'wc.m.join': '加入',
}

const zhHans: Dict = {
  'screen.aria': '记录',
  'hero.title': '你的镜面球',
  'hero.lit': '面已点亮',
  'hero.of': '共{total}首歌的球',
  'hero.hint': '用手指转动・点亮起的面看详情',
  'hero.empty': '把卡片往右滑，就会贴上第一面',
  'hero.tonight': '今晚 +{n}',
  'bye.title': '下次见',
  'bye.body': '今晚的光留在这颗球上了。下次来店会从“欢迎回来”开始。',
  'bye.linked': '已带回我的歌单（示意）',
  'bye.local': '已保留在这台设备',

  'faces.title': '面的组成',
  'faces.total': '{n}面',
  'state.sketch': '素描',
  'state.neon': '霓虹',
  'state.mirror': '镜面',
  'state.prism': '棱镜',
  'how.sketch': '收藏・带来',
  'how.neon': '点了歌',
  'how.mirror': '唱过了',
  'how.prism': '唱了全员都会的歌',
  'marks.title': '刻印说明',
  'mark.key': '调性',
  'mark.stitch': '缝线',
  'mark.duet': '双色',
  'mark.seal': '封蜡',
  'mark.visa': '签证',
  'mark.navi': '金点',
  'mark.gold': '金框',
  'mark.twin': '双点',
  'markHow.key': '指定调性点歌',
  'markHow.stitch': '从带来的歌中保存',
  'markHow.duet': '以对唱方式演唱',
  'markHow.seal': '回应点播演唱',
  'markHow.visa': '从越境卡片点歌',
  'markHow.navi': '以导航推荐标签点歌',
  'markHow.gold': '唱了压轴曲，或拿到100分（示意）',
  'markHow.twin': '让双星保持秘密（只有你看得到）',

  'sleep.title': '沉睡的面',
  'sleep.body': '超过60天没唱。外观和内容都不会失去任何东西。',
  'sleep.last': '上次 {date}',
  'sleep.polish': '重新擦亮',

  'tonight.title': '今晚的光座',
  'tonight.sub': '球今晚投射在墙上的光',

  'gaps.title': '还没点亮的区域',
  'gaps.body': '打开就会以该区域筛选搜索。点歌后第一面就会亮起',
  'gaps.area': '{tempo} × {genre}',
  'gaps.n': '{n}首',
  'gaps.open': '打开',
  'gaps.none': '所有区域都亮起来了',
  'tempo.fast': '北',
  'tempo.mid': '赤道',
  'tempo.slow': '南',

  'pins.title': '徽章',
  'pins.body': '获得条件全部公开。没有期限，也没有稀有度',
  'pins.got': '{n} / 10',
  'pins.at': '{date} 获得',
  'pin.spark': '点火',
  'pin.allKnow': '全员之歌',
  'pin.airRead': '读空气',
  'pin.crossing': '越境',
  'pin.harmony': '和声',
  'pin.answer': '回应',
  'pin.importer': '带歌入场',
  'pin.polish': '重新擦亮',
  'pin.hundred': '100分',
  'pin.faces30': '30面',
  'pinHow.spark': '点了当晚的第一首歌',
  'pinHow.allKnow': '唱了全员都会的歌',
  'pinHow.airRead': '在气氛转折时插播的歌之后，气氛升温了',
  'pinHow.crossing': '唱了越境卡片的歌',
  'pinHow.harmony': '唱了一首对唱曲',
  'pinHow.answer': '回应点播唱了歌',
  'pinHow.importer': '把3首带来的候选歌存进我的歌单',
  'pinHow.polish': '重新唱了沉睡的面',
  'pinHow.hundred': '在评分（示意）中拿到100分',
  'pinHow.faces30': '球上点亮了30面',

  'cal.title': '日历',
  'cal.body': '盖了章的夜晚会排在这里。点一下打开那一晚',
  'cal.prev': '上个月',
  'cal.next': '下个月',
  'cal.today': '今天',
  'cal.press': '长按',

  'nights.title': '夜晚页面',
  'nights.demo': '示意用数据',
  'nights.tonight': '今晚',
  'nights.faces': '面 +{n}',
  'nights.sung': '{n}首',

  'voice.title': '声音记录',
  'voice.note': '声音会随歌曲和日子而改变',
  'voice.was': '这次的声音是{type}',
  'voice.power': '魄力',
  'voice.care': '细腻',
  'voice.bright': '明亮',

  'saved.title': '我的歌单',
  'saved.body': '保存的歌会放进下次来店的第一手牌',
  'saved.from.import': '带来的歌',
  'saved.from.face': '球',
  'saved.from.wrap': '今晚',
  'saved.reserve': '点歌',

  'set.title': '设置',
  'set.lang': '语言',
  'set.sound': '音效',
  'set.on': '开',
  'set.off': '关',
  'set.link': '我的歌单联动',
  'set.linked': '带回中（示意・模拟登录）',
  'set.local': '只在这台设备',
  'set.wipe': '清除这台设备的数据',
  'set.wipeAsk': '将从这台设备清除面、徽章、夜晚页面和我的歌单。无法恢复。',
  'set.wipeYes': '清除',
  'set.wipeNo': '取消',
  'set.wiped': '已清除这台设备的数据',

  'face.first': '第一次贴上的夜晚',
  'face.sung': '唱过的次数',
  'face.sungN': '{n}次',
  'face.key': '建议调性',
  'face.keyDown': '−{n}',
  'face.keyUp': '+{n}',
  'face.keyOrig': '原调',
  'face.keyNone': '声音检查之后',
  'face.keyFromVoice': '来自声音记录（假设）',
  'face.keyFromReserve': '点歌时的调性',
  'face.marks': '这一面的刻印',
  'face.noMarks': '还没有刻印',
  'face.again': '再点一次',
  'face.queued': '已点歌 #{n}',
  'face.playing': '正在播放',
  'face.sleeping': '沉睡的面（上次 {date}）',
  'face.rubHint': '用手指擦这一面3次，重新擦亮',
  'face.polished': '重新亮起来了。下次唱就能拿到徽章“重新擦亮”',
  'face.ask': '想请人唱这首',
  'face.askWho': '要送给谁？',
  'face.askSent': '已送达给{member}',
  'face.askNote': '不会显示回复。对方唱的话会出现在点歌列',
  'face.noFace': '这首歌的面还是暗的',
  'face.nobody': '现在没有可以送达的人',

  'night.date': '{date}的夜晚',
  'night.faces': '这一晚贴上的面',
  'night.mine': '你唱的歌',
  'night.none': '这一晚还没有唱歌的记录',
  'night.play': '听旋律',
  'night.notes': '{n}个音',

  'wrap.title': '今晚的回顾',
  'wrap.skip': '跳过',
  'wrap.tap': '点一下看下一页',
  'wrap.p1': '今晚的面',
  'wrap.p2': '今晚的声音',
  'wrap.p3': '大家的共同曲',
  'wrap.p4': '今晚的光座',
  'wrap.p5': '盖章',
  'wrap.facesHead': '今晚亮起了{n}面',
  'wrap.facesNone': '今晚是欣赏的夜晚',
  'wrap.facesSub': '今晚的光已贴在球上',
  'wrap.voiceType': '这次的声音是{type}',
  'wrap.voiceNone': '今晚没有检查声音',
  'wrap.voiceNoneSub': '下次可以用3秒哼唱或3个问题',
  'wrap.claps': '收到的掌声之光',
  'wrap.clapsNone': '荧光棒的光会送给正在唱的人',
  'wrap.sang': '今晚你唱的歌',
  'wrap.commonHead': '{n}人全员都会的歌',
  'wrap.commonNone': '全员都会的歌，留到下个夜晚',
  'wrap.commonNoneSub': '用“问问大家”就能找到共同曲',
  'wrap.nameLead': '今晚的光座有了名字',
  'wrap.play': '再听一次',
  'wrap.melody': '今晚的旋律・{n}个音',
  'wrap.noMelody': '每当面有变化，旋律就多一个音',
  'wrap.stampHead': '长按今天的格子来盖章',
  'wrap.stampDone': '盖好章了',
  'wrap.save': '带回我的歌单',
  'wrap.saveSub': '今晚的{n}首歌和进度（示意）',
  'wrap.nosave': '只留在这台设备',
  'wrap.nosaveSub': '球会在这台设备上继续长大',

  'sv.title': '5个问题（可不回答）',
  'sv.lead': '不回答也没关系。只用于改善这个试作',
  'sv.q1': '容易找到歌吗？',
  'sv.q2': '有意外的发现吗？',
  'sv.q3': '选歌有趣吗？',
  'sv.q4': '下次还想用吗？',
  'sv.q5': '这样觉得的理由（可多选）',
  'sv.lo': '不太',
  'sv.hi': '非常',
  'sv.why.cards': '翻卡片很有趣',
  'sv.why.know': '知道全员都会的歌',
  'sv.why.ball': '球会长大',
  'sv.why.voice': '声音卡片',
  'sv.why.lang': '能用自己的语言',
  'sv.why.lane': '点歌列很清楚',
  'sv.why.order': '点餐很简单',
  'sv.send': '发送',
  'sv.skip': '不回答并关闭',
  'sv.thanks': '谢谢。会用在下一个夜晚',

  'wc.aria': '墙上的光座：{n}点',
  'wc.empty': '第一首歌结束后，这里会亮起光',
  'wc.m.shift': '转折点',
  'wc.m.toast': '干杯',
  'wc.m.navi': '导航推荐',
  'wc.m.allKnow': '全员',
  'wc.m.join': '加入',
}

const ko: Dict = {
  'screen.aria': '기록',
  'hero.title': '나의 미러볼',
  'hero.lit': '면 점등',
  'hero.of': '전 {total}곡의 볼',
  'hero.hint': '손가락으로 돌리기 · 빛나는 면을 탭하면 상세',
  'hero.empty': '카드를 오른쪽으로 넘기면 첫 면이 붙어요',
  'hero.tonight': '오늘 밤 +{n}',
  'bye.title': '또 만나요',
  'bye.body': '오늘 밤의 빛은 이 볼에 남았어요. 다음 방문은 “어서 와”로 시작해요.',
  'bye.linked': '마이 노래로 가져갔어요 (데모)',
  'bye.local': '이 기기에 남겼어요',

  'faces.title': '면 구성',
  'faces.total': '{n}면',
  'state.sketch': '스케치',
  'state.neon': '네온',
  'state.mirror': '미러',
  'state.prism': '프리즘',
  'how.sketch': '찜·가져옴',
  'how.neon': '예약했다',
  'how.mirror': '불렀다',
  'how.prism': '모두가 아는 노래를 불렀다',
  'marks.title': '각인 보는 법',
  'mark.key': '키',
  'mark.stitch': '바느질',
  'mark.duet': '투톤',
  'mark.seal': '봉랍',
  'mark.visa': '비자',
  'mark.navi': '금색 점',
  'mark.gold': '금테',
  'mark.twin': '쌍점',
  'markHow.key': '키를 지정해 예약했다',
  'markHow.stitch': '가져온 노래에서 저장했다',
  'markHow.duet': '듀엣으로 불렀다',
  'markHow.seal': '리퀘스트에 응해 불렀다',
  'markHow.visa': '국경 카드에서 예약했다',
  'markHow.navi': '내비 추천 태그로 예약했다',
  'markHow.gold': '마지막 곡을 불렀거나 100점 (데모)',
  'markHow.twin': '쌍둥이 별을 비밀로 했다 (나만 보여요)',

  'sleep.title': '잠든 면',
  'sleep.body': '마지막으로 부른 지 60일 이상. 모습도 내용도 아무것도 사라지지 않아요.',
  'sleep.last': '지난번 {date}',
  'sleep.polish': '다시 닦기',

  'tonight.title': '오늘 밤의 빛자리',
  'tonight.sub': '오늘 밤 볼이 벽에 던진 빛',

  'gaps.title': '아직 어두운 영역',
  'gaps.body': '열면 그 영역으로 좁힌 검색으로. 예약하면 첫 면이 켜져요',
  'gaps.area': '{tempo} × {genre}',
  'gaps.n': '{n}곡',
  'gaps.open': '열기',
  'gaps.none': '모든 영역에 빛이 켜졌어요',
  'tempo.fast': '북쪽',
  'tempo.mid': '적도',
  'tempo.slow': '남쪽',

  'pins.title': '핀',
  'pins.body': '얻는 방법은 모두 공개. 기한도 희귀도도 없어요',
  'pins.got': '{n} / 10',
  'pins.at': '{date} 획득',
  'pin.spark': '불씨',
  'pin.allKnow': '모두의 노래',
  'pin.airRead': '분위기 읽기',
  'pin.crossing': '국경 넘기',
  'pin.harmony': '하모니',
  'pin.answer': '응답',
  'pin.importer': '가져온 노래',
  'pin.polish': '다시 닦기',
  'pin.hundred': '100점',
  'pin.faces30': '30면',
  'pinHow.spark': '그날 밤 첫 예약을 했다',
  'pinHow.allKnow': '모두가 아는 노래를 불렀다',
  'pinHow.airRead': '분위기 전환점에 끼워 넣은 곡 뒤에 분위기가 올라갔다',
  'pinHow.crossing': '국경 카드의 노래를 불렀다',
  'pinHow.harmony': '듀엣으로 불렀다',
  'pinHow.answer': '리퀘스트에 응해 불렀다',
  'pinHow.importer': '가져온 후보곡 3곡을 마이 노래에 저장했다',
  'pinHow.polish': '잠든 면을 다시 불렀다',
  'pinHow.hundred': '채점(데모)에서 100점을 받았다',
  'pinHow.faces30': '볼에 불 켜진 면이 30장이 되었다',

  'cal.title': '캘린더',
  'cal.body': '스탬프를 찍은 밤이 여기에 모여요. 탭하면 그 밤의 페이지로',
  'cal.prev': '이전 달',
  'cal.next': '다음 달',
  'cal.today': '오늘',
  'cal.press': '길게 누르기',

  'nights.title': '밤의 페이지',
  'nights.demo': '데모용 데이터',
  'nights.tonight': '오늘 밤',
  'nights.faces': '면 +{n}',
  'nights.sung': '{n}곡',

  'voice.title': '목소리 기록',
  'voice.note': '목소리는 곡이나 날에 따라 달라져요',
  'voice.was': '이번 목소리는 {type}',
  'voice.power': '박력',
  'voice.care': '섬세함',
  'voice.bright': '밝음',

  'saved.title': '마이 노래',
  'saved.body': '저장한 곡은 다음 방문의 첫 패에 들어가요',
  'saved.from.import': '가져온 노래',
  'saved.from.face': '볼',
  'saved.from.wrap': '오늘 밤',
  'saved.reserve': '예약',

  'set.title': '설정',
  'set.lang': '언어',
  'set.sound': '효과음',
  'set.on': '켜기',
  'set.off': '끄기',
  'set.link': '마이 노래 연동',
  'set.linked': '가져가는 중 (데모·가상 로그인)',
  'set.local': '이 기기에만',
  'set.wipe': '이 기기의 데이터 지우기',
  'set.wipeAsk': '면·핀·밤의 페이지·마이 노래를 이 기기에서 지웁니다. 되돌릴 수 없어요.',
  'set.wipeYes': '지우기',
  'set.wipeNo': '그만두기',
  'set.wiped': '이 기기의 데이터를 지웠어요',

  'face.first': '처음 붙인 밤',
  'face.sung': '부른 횟수',
  'face.sungN': '{n}회',
  'face.key': '추천 키',
  'face.keyDown': '−{n}',
  'face.keyUp': '+{n}',
  'face.keyOrig': '원키',
  'face.keyNone': '목소리 체크 후에',
  'face.keyFromVoice': '목소리 기록에서 (가설)',
  'face.keyFromReserve': '예약한 키',
  'face.marks': '이 면의 각인',
  'face.noMarks': '아직 각인이 없어요',
  'face.again': '다시 예약',
  'face.queued': '예약됨 #{n}',
  'face.playing': '지금 연주 중',
  'face.sleeping': '잠든 면 (지난번 {date})',
  'face.rubHint': '면을 손가락으로 3번 문질러 다시 닦기',
  'face.polished': '다시 빛나요. 다음에 부르면 핀 “다시 닦기”',
  'face.ask': '누가 불러 줬으면',
  'face.askWho': '누구에게 보낼까요?',
  'face.askSent': '{member}에게 전달했어요',
  'face.askNote': '답장은 표시하지 않아요. 불러 주면 예약 목록에 나와요',
  'face.noFace': '이 곡의 면은 아직 어두워요',
  'face.nobody': '지금은 보낼 사람이 없어요',

  'night.date': '{date}의 밤',
  'night.faces': '이 밤에 붙인 면',
  'night.mine': '내가 부른 곡',
  'night.none': '이 밤에는 아직 부른 기록이 없어요',
  'night.play': '멜로디 듣기',
  'night.notes': '{n}음',

  'wrap.title': '오늘 밤 정리',
  'wrap.skip': '건너뛰기',
  'wrap.tap': '탭해서 다음',
  'wrap.p1': '오늘 밤의 면',
  'wrap.p2': '오늘 밤의 목소리',
  'wrap.p3': '모두의 공통곡',
  'wrap.p4': '오늘 밤의 빛자리',
  'wrap.p5': '스탬프',
  'wrap.facesHead': '오늘 밤 {n}면이 켜졌어요',
  'wrap.facesNone': '오늘 밤은 바라보며 즐긴 밤',
  'wrap.facesSub': '오늘 밤의 빛이 볼에 붙었어요',
  'wrap.voiceType': '이번 목소리는 {type}',
  'wrap.voiceNone': '오늘 밤은 목소리를 재지 않았어요',
  'wrap.voiceNoneSub': '다음 밤에는 3초 허밍이나 3가지 질문으로',
  'wrap.claps': '받은 박수의 빛',
  'wrap.clapsNone': '응원봉 빛은 노래하는 사람에게 전해져요',
  'wrap.sang': '오늘 밤 내가 부른 곡',
  'wrap.commonHead': '{n}명 모두가 알았던 곡',
  'wrap.commonNone': '모두가 아는 곡은 다음 밤에',
  'wrap.commonNoneSub': '“모두에게 묻기”로 공통곡을 찾을 수 있어요',
  'wrap.nameLead': '오늘 밤의 빛자리에 이름이 생겼어요',
  'wrap.play': '다시 듣기',
  'wrap.melody': '오늘 밤의 멜로디 · {n}음',
  'wrap.noMelody': '면이 바뀔 때마다 선율이 한 음씩 늘어나요',
  'wrap.stampHead': '오늘 칸을 길게 눌러 스탬프 찍기',
  'wrap.stampDone': '스탬프를 찍었어요',
  'wrap.save': '마이 노래로 가져가기',
  'wrap.saveSub': '오늘 밤의 {n}곡과 이어서 (데모)',
  'wrap.nosave': '이 기기에만 남기기',
  'wrap.nosaveSub': '볼은 이 기기에서 자라요',

  'sv.title': '5가지 질문 (선택)',
  'sv.lead': '답하지 않아도 괜찮아요. 시제품 개선에만 써요',
  'sv.q1': '곡은 찾기 쉬웠나요?',
  'sv.q2': '뜻밖의 발견이 있었나요?',
  'sv.q3': '고르는 게 즐거웠나요?',
  'sv.q4': '다음에도 쓰고 싶나요?',
  'sv.q5': '그렇게 느낀 이유 (여러 개 가능)',
  'sv.lo': '별로',
  'sv.hi': '매우',
  'sv.why.cards': '카드 넘기는 게 즐겁다',
  'sv.why.know': '모두가 아는 곡을 알 수 있다',
  'sv.why.ball': '볼이 자란다',
  'sv.why.voice': '목소리 카드',
  'sv.why.lang': '내 언어로 쓸 수 있다',
  'sv.why.lane': '예약 목록이 보기 쉽다',
  'sv.why.order': '주문이 쉽다',
  'sv.send': '보내기',
  'sv.skip': '답하지 않고 닫기',
  'sv.thanks': '고마워요. 다음 밤에 살릴게요',

  'wc.aria': '벽의 빛자리: {n}점',
  'wc.empty': '첫 곡이 끝나면 여기에 빛이 켜져요',
  'wc.m.shift': '전환점',
  'wc.m.toast': '건배',
  'wc.m.navi': '내비 추천',
  'wc.m.allKnow': '모두',
  'wc.m.join': '합류',
}

// ---------------------------------------------------------------- night names (SPEC D-7)

export const NIGHT_COLORS = ['quiet', 'mellow', 'warm', 'hot'] as const
export type NightColor = (typeof NIGHT_COLORS)[number]
export const NIGHT_SYMBOLS = ['harmony', 'finale', 'allKnow', 'crossing', 'airRead', 'spark'] as const
export type NightSymbol = (typeof NIGHT_SYMBOLS)[number]

type NameParts = { wd: string[]; color: Record<NightColor, string>; sym: Record<NightSymbol, string>; fmt: (w: string, c: string, s: string) => string }

const ZH_WD = ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六']
const NAME_PARTS: Record<Locale, NameParts> = {
  ja: {
    wd: ['日曜', '月曜', '火曜', '水曜', '木曜', '金曜', '土曜'],
    color: { quiet: '瑠璃', mellow: '菫', warm: '珊瑚', hot: '琥珀' },
    sym: { harmony: 'ハモリ', finale: '締め', allKnow: '全員', crossing: '越境', airRead: '読み', spark: '口火' },
    fmt: (w, c, s) => `${w}の${c}${s}座`,
  },
  en: {
    wd: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    color: { quiet: 'Lapis', mellow: 'Violet', warm: 'Coral', hot: 'Amber' },
    sym: { harmony: 'Harmony', finale: 'Finale', allKnow: 'Singalong', crossing: 'Crossing', airRead: 'Vibe', spark: 'Spark' },
    fmt: (w, c, s) => `${w}'s ${c} ${s}`,
  },
  zhHant: {
    wd: ZH_WD,
    color: { quiet: '琉璃', mellow: '堇紫', warm: '珊瑚', hot: '琥珀' },
    sym: { harmony: '和聲', finale: '壓軸', allKnow: '合唱', crossing: '越境', airRead: '默契', spark: '火花' },
    fmt: (w, c, s) => `${w}的${c}${s}座`,
  },
  zhHans: {
    wd: ZH_WD,
    color: { quiet: '琉璃', mellow: '堇紫', warm: '珊瑚', hot: '琥珀' },
    sym: { harmony: '和声', finale: '压轴', allKnow: '合唱', crossing: '越境', airRead: '默契', spark: '火花' },
    fmt: (w, c, s) => `${w}的${c}${s}座`,
  },
  ko: {
    wd: ['일요일', '월요일', '화요일', '수요일', '목요일', '금요일', '토요일'],
    color: { quiet: '청금색', mellow: '제비꽃색', warm: '산호색', hot: '호박색' },
    sym: { harmony: '하모니', finale: '피날레', allKnow: '떼창', crossing: '여권', airRead: '눈치', spark: '불씨' },
    fmt: (w, c, s) => `${w}의 ${c} ${s}자리`,
  },
}

/** "nn.<weekday>.<colour>.<symbol>" — one key per combination, so a stored TextRef re-resolves. */
export const nightNameKey = (weekday: number, color: NightColor, symbol: NightSymbol) => `nn.${weekday}.${color}.${symbol}`

function withNames(l: Locale, d: Dict): Dict {
  const p = NAME_PARTS[l]
  const out: Dict = { ...d }
  for (let w = 0; w < 7; w++) for (const c of NIGHT_COLORS) for (const s of NIGHT_SYMBOLS) out[nightNameKey(w, c, s)] = p.fmt(p.wd[w], p.color[c], p.sym[s])
  return out
}

export const R = defineStrings<string>('record', {
  ja: withNames('ja', ja),
  en: withNames('en', en),
  zhHant: withNames('zhHant', zhHant),
  zhHans: withNames('zhHans', zhHans),
  ko: withNames('ko', ko),
})

/** Raw dictionaries (unit tests check coverage and wording). */
export const RECORD_DICTS: Record<Locale, Dict> = {
  ja: withNames('ja', ja),
  en: withNames('en', en),
  zhHant: withNames('zhHant', zhHant),
  zhHans: withNames('zhHans', zhHans),
  ko: withNames('ko', ko),
}
