// #/help, #/help/<section> ヘルプ (docs/SPEC.md F19, F17 AC2, F1 AC4, §4.4, §9).
// One section is shown at a time; the in-page nav links to #/help/<section> so every section is
// deep-linkable (the app remounts the screen per section and scrolls to the top).
import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { writeClipboard } from '../../app/platform';
import { APP_NAME_EN, APP_NAME_JA, APP_VERSION, DISCLAIMER_JA, NOT_DRM_JA } from '../../core/constants';
import type { HelpSection } from '../../core/route';
import { DEMO_CODES, DEMO_RETURN_CODE_NOTE } from '../../demo/demoCodes';
import { useSettings, useUi } from '../context';
import { displayTitle } from '../format';
import { hrefFor } from '../router';
import { useTrySamples } from './libraryShared';
import './Help.css';

const SECTIONS: ReadonlyArray<{ id: HelpSection; label: string; icon: string }> = [
  { id: 'usage', label: '使い方', icon: '📖' },
  { id: 'demo-codes', label: 'サンプルの合言葉', icon: '🔑' },
  { id: 'ios', label: 'iOSでの注意', icon: '📱' },
  { id: 'creators', label: 'サークル向けガイド', icon: '🛠️' },
  { id: 'privacy', label: 'プライバシー', icon: '🛡️' },
  { id: 'about', label: 'このアプリについて', icon: 'ℹ️' },
];

/**
 * Third-party notices, generated by scripts/gen-licenses.ts into public/licenses.txt: a same-origin static
 * file next to index.html (relative, so it works under any GitHub Pages subpath) and precached for offline use.
 */
export const LICENSES_HREF = './licenses.txt';

export const STORE_TEMPLATE_JA =
  '【クリア特典】作中の“合言葉”を無料のスマホ用Webアプリ「しおり帳」に入れると、あとがき・後日談が読めます（ネタバレ防止ヒント・実績チェック付き／アカウント不要）';

export function HelpScreen({ section }: { section?: HelpSection }): ReactNode {
  const current = SECTIONS.find((s) => s.id === section) ?? SECTIONS[0]!;
  const index = SECTIONS.indexOf(current);
  const prev = SECTIONS[index - 1];
  const next = SECTIONS[index + 1];
  const headingRef = useRef<HTMLHeadingElement>(null);

  // Opened on a specific section (from the nav or a link): start reading there.
  useEffect(() => {
    if (section !== undefined) headingRef.current?.focus({ preventScroll: true });
  }, [section]);

  return (
    <main className="screen hlp">
      <h1 className="hlp-title">ヘルプ</h1>
      <nav className="hlp-nav" aria-label="ヘルプの項目">
        <ul className="hlp-nav-list">
          {SECTIONS.map((s) => (
            <li key={s.id}>
              <a
                className="hlp-nav-link"
                href={hrefFor({ name: 'help', section: s.id })}
                aria-current={s.id === current.id ? 'page' : undefined}
              >
                <span aria-hidden="true" className="hlp-nav-icon">
                  {s.icon}
                </span>
                <span>{s.label}</span>
              </a>
            </li>
          ))}
        </ul>
      </nav>

      <article className="card hlp-body" aria-labelledby="hlp-section-title">
        <h2 id="hlp-section-title" ref={headingRef} tabIndex={-1} className="hlp-h2">
          <span aria-hidden="true">{current.icon} </span>
          {current.label}
        </h2>
        <SectionBody id={current.id} />
      </article>

      <nav className="hlp-pager" aria-label="前後の項目">
        {prev ? (
          <a className="btn hlp-pager-link" href={hrefFor({ name: 'help', section: prev.id })}>
            <span aria-hidden="true">‹ </span>
            {prev.label}
          </a>
        ) : (
          <span />
        )}
        {next ? (
          <a className="btn hlp-pager-link is-next" href={hrefFor({ name: 'help', section: next.id })}>
            {next.label}
            <span aria-hidden="true"> ›</span>
          </a>
        ) : null}
      </nav>
    </main>
  );
}

function SectionBody({ id }: { id: HelpSection }): ReactNode {
  switch (id) {
    case 'usage':
      return <Usage />;
    case 'demo-codes':
      return <DemoCodes />;
    case 'ios':
      return <Ios />;
    case 'creators':
      return <Creators />;
    case 'privacy':
      return <Privacy />;
    case 'about':
      return <About />;
  }
}

function useCopy(): (text: string, what?: string) => Promise<void> {
  const ui = useUi();
  return async (text, what = 'コピー') => {
    const ok = await writeClipboard(text);
    ui.toast(ok ? `${what}しました` : 'コピーできませんでした。長押しして選択してください', { tone: ok ? 'ok' : 'danger' });
  };
}

// ───────────────────────── 使い方 ─────────────────────────

function Usage(): ReactNode {
  return (
    <div className="hlp-content">
      <p>しおり帳は、遊んでいる作品の進み具合やプレイ記録を、この端末の中だけに残しておける手帖です。</p>
      <ol className="hlp-steps">
        <li>
          <h3 className="hlp-h3">本棚に作品を追加</h3>
          <p>
            本棚の「＋ 追加」から、作品に付いている「しおりファイル」（shiori.json）を読み込みます。ファイルがない作品も、エンディングの数などを入れるだけの「かんたんしおり」や「記録だけ付ける」で追加できます。
          </p>
        </li>
        <li>
          <h3 className="hlp-h3">作品ページ</h3>
          <p>
            作品をタップすると、進捗・おまけ・記録・メモのタブがあります。「▶ 始める」「■ 終える」でプレイ時間や「次にやること」を残すと、次に開いたときに「前回の続き」が表示されます。
          </p>
        </li>
        <li>
          <h3 className="hlp-h3">進捗とヒント</h3>
          <p>
            達成した項目はタップしてチェックします。ヒントは「示唆 → 方向 → 答え」の3段階で、長押しするたびに1段ずつ開きます。ネタバレを含みそうな文はぼかしてあり、タップしたときだけ表示されます。ヒントを見ずに達成すると「ノーヒント」のバッジがつきます。
          </p>
        </li>
        <li>
          <h3 className="hlp-h3">合言葉</h3>
          <p>
            ゲームのエンディングなどで表示された合言葉を、画面下の「合言葉」から入れます。QRコードなら、スマホのカメラで読み取るだけです。しおりファイルをまだ読み込んでいない作品の合言葉は「保留」にしておけます。
          </p>
        </li>
        <li>
          <h3 className="hlp-h3">おまけ</h3>
          <p>条件の合言葉がそろうと封筒がひらき、手紙やあとがきなどが読めます。作品ページの「おまけ」タブからいつでも読み返せます。</p>
        </li>
      </ol>

      <h3 className="hlp-h3">すぐに隠す</h3>
      <p>
        画面上の「隠す」（パソコンではEscキー）で、ふつうの「メモ」画面に切り替わります。戻るときは「メモ」の見出しを1秒ほど長押しします（PINを設定していれば、続けてPINを入力）。ほかのアプリに切り替えたときの画面も、無地で覆われます。
      </p>

      <h3 className="hlp-h3">バックアップ</h3>
      <p>
        記録はこの端末の中だけにあります。機種変更やもしもに備えて、設定の「データ」→「バックアップを書き出す」で保存しておきましょう。パスフレーズで暗号化もできます。
      </p>

      <div className="hlp-actions">
        <a className="btn btn-primary" href={hrefFor({ name: 'code' })}>
          合言葉を入れる
        </a>
        <a className="btn" href={hrefFor({ name: 'settings' })}>
          設定を開く
        </a>
      </div>
    </div>
  );
}

// ───────────────────────── サンプルの合言葉 ─────────────────────────

function DemoCodes(): ReactNode {
  const { settings } = useSettings();
  const trySamples = useTrySamples();
  const copy = useCopy();
  const [busy, setBusy] = useState(false);

  const onSamples = async () => {
    setBusy(true);
    await trySamples();
    setBusy(false);
  };

  return (
    <div className="hlp-content">
      <p>
        サンプルは、しおり帳の流れを試すための架空の作品です。まず「サンプルを試す」で本棚に追加してから、下の合言葉を「合言葉」画面に入れてみてください。
      </p>
      <div className="hlp-actions">
        <button type="button" className="btn" onClick={() => void onSamples()} disabled={busy} aria-busy={busy || undefined}>
          サンプルを試す
        </button>
        <a className="btn btn-primary" href={hrefFor({ name: 'code' })}>
          合言葉を入れる
        </a>
      </div>

      <table className="hlp-table">
        <caption className="visually-hidden">サンプルの合言葉の一覧</caption>
        <thead>
          <tr>
            <th scope="col">作品</th>
            <th scope="col">項目</th>
            <th scope="col">合言葉</th>
            <th scope="col">出てくる場所</th>
          </tr>
        </thead>
        <tbody>
          {DEMO_CODES.map((c) => (
            <tr key={`${c.workId}-${c.display}`} className={c.kind === 'return' ? 'is-return' : undefined}>
              <td data-label="作品">
                <span className="hlp-cell">{displayTitle({ alias: c.alias, title: c.workTitle }, settings)}</span>
              </td>
              <td data-label="項目">
                <span className="hlp-cell">
                  {c.goalLabel}
                  {c.kind === 'return' ? <span className="badge badge-warn hlp-badge">返し合言葉</span> : null}
                </span>
              </td>
              <td data-label="合言葉">
                <span className="hlp-cell hlp-code-cell">
                  <span className="hlp-code mono">{c.display}</span>
                  <button
                    type="button"
                    className="btn btn-sm hlp-copy"
                    onClick={() => void copy(c.display, '合言葉をコピー')}
                    aria-label={`${c.display} をコピー`}
                  >
                    コピー
                  </button>
                </span>
              </td>
              <td data-label="出てくる場所" className="hlp-where">
                <span className="hlp-cell">{c.where}</span>
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <h3 className="hlp-h3">PC画面シミュレータ</h3>
      <p>
        サンプルA（星読みの図書館）のゲーム画面を、この端末の中で再現したものです。エンディングに合言葉とQRコードが表示され、「この端末で入力する」でそのまま試せます。
      </p>
      <p className="hlp-callout">{DEMO_RETURN_CODE_NOTE}</p>
      <div className="hlp-actions">
        <a className="btn" href={hrefFor({ name: 'demoPc' })}>
          PC画面シミュレータを開く
        </a>
      </div>
    </div>
  );
}

// ───────────────────────── iOSでの注意 ─────────────────────────

function Ios(): ReactNode {
  return (
    <div className="hlp-content">
      <h3 className="hlp-h3">Safariとホーム画面では保存場所が別々です</h3>
      <p>
        iPhone・iPadでは、Safariで開いたしおり帳と、ホーム画面に追加したしおり帳は、データの保存場所が別々です。片方で入れた作品や合言葉は、もう片方には表示されません。
      </p>
      <p>
        使う場所はどちらかに決めておくのがおすすめです。ホーム画面に追加するには、Safariの共有ボタンから「ホーム画面に追加」を選びます。
      </p>

      <h3 className="hlp-h3">データが消えることがあります</h3>
      <p>
        しばらく使わなかったときや端末の空き容量が少ないとき、ブラウザがデータを消すことがあります。設定の「データ」で「保存を長持ちさせる」を押し、ときどきバックアップを書き出しておいてください。
      </p>

      <h3 className="hlp-h3">QRコードと合言葉</h3>
      <p>
        カメラでQRコードを読み取ると、Safariでしおり帳が開きます。ホーム画面のしおり帳で使う場合は、表示された合言葉をコピーして、ホーム画面のしおり帳の「合言葉」に貼り付けてください。
      </p>
      <p>しおりファイルをまだ読み込んでいない作品の合言葉は「保留」として残り、しおりファイルを読み込んだときに自動で試されます。</p>

      <h3 className="hlp-h3">バックアップの保存先</h3>
      <p>
        書き出したバックアップは「ファイル」アプリなどに保存されます。機種変更のときは、新しい端末でそのファイルを「バックアップから復元」で読み込みます。
      </p>
    </div>
  );
}

// ───────────────────────── サークル向けガイド ─────────────────────────

const ENGINE_SNIPPETS: ReadonlyArray<{ engine: string; how: string; code?: string }> = [
  { engine: 'RPGツクールMV/MZ', how: '「文章の表示」に書きます（必要ならピクチャでQR画像も表示）。', code: 'しおり帳の合言葉：\\C[3]ST4-RMA-P1X\\C[0]' },
  { engine: 'ティラノスクリプト', how: 'シナリオに書きます。QR画像は [image] で表示できます。', code: 'しおり帳の合言葉：ST4-RMA-P1X[p]\n[image layer=1 storage="shiori_end-a.png"]' },
  { engine: 'WOLF RPGエディター', how: '「文章表示」で色を変えて表示します。', code: 'しおり帳の合言葉：\\c[2]ST4-RMA-P1X' },
  { engine: "Ren'Py", how: 'セリフとして表示します。', code: '"しおり帳の合言葉：{b}ST4-RMA-P1X{/b}"' },
  { engine: 'Unity など', how: 'テキスト要素に合言葉を表示するだけで使えます。' },
  { engine: '音声作品', how: 'おまけトラックの最後で読み上げるか、台本の最後のページに載せます。', code: 'しおり帳の合言葉は、ほたる、かえで、つばめ、こだま、すずめ、です' },
  { engine: 'CG集・漫画', how: '最後のページに合言葉（とQRコード）を載せます。' },
];

function Creators(): ReactNode {
  const copy = useCopy();
  return (
    <div className="hlp-content">
      <p>
        作品に「しおりファイル」（shiori.json）を1つ同梱するだけで、プレイヤーはネタバレしない段階ヒントや、合言葉でひらくおまけを楽しめます。サーバーやアカウントは不要です。
      </p>

      <ol className="hlp-steps">
        <li>
          <h3 className="hlp-h3">工房で作る</h3>
          <p>
            設定の「サークル工房を開く」から、作品情報・章・目標・ヒント・おまけを入力します。合言葉の目標には、合言葉が自動で作られます（英数字9文字か、ひらがな5語）。
          </p>
        </li>
        <li>
          <h3 className="hlp-h3">点検</h3>
          <p>「点検」で、ネタバレの漏れや入力ミスがないか確かめます。エラーがなくなるまで直してください。「プレイヤー画面で試す」で実際の見え方も確認できます。</p>
        </li>
        <li>
          <h3 className="hlp-h3">書き出し</h3>
          <p>「書き出し」で配布用のセット（zip）を作ります。</p>
          <ul className="hlp-list">
            <li>
              <b>同梱用_PUBLIC</b>：shiori.json と はじめに.txt。作品と一緒に配布します。
            </li>
            <li>
              <b>非公開_ゲームに埋め込む</b>：合言葉の一覧、QRコード画像、エンジン別の表示例。配布しないでください。
            </li>
            <li>
              <b>非公開_控え</b>：工房のデータの控え（合言葉を含みます）。
            </li>
            <li>告知文テンプレート.txt と README_最初に読んでください.txt</li>
          </ul>
        </li>
        <li>
          <h3 className="hlp-h3">同梱する</h3>
          <p>
            shiori.json と はじめに.txt を作品のzipに入れます（新作でも、発売済み作品の更新でも使えます）。合言葉は、プレイヤーが達成した場面（エンディングなど）で表示してください。プラグインは不要です。
          </p>
        </li>
      </ol>

      <h3 className="hlp-h3">エンジン別の表示例</h3>
      <dl className="hlp-snippets">
        {ENGINE_SNIPPETS.map((s) => (
          <div key={s.engine} className="hlp-snippet">
            <dt className="hlp-snippet-engine">{s.engine}</dt>
            <dd className="hlp-snippet-body">
              <p>{s.how}</p>
              {s.code ? (
                <pre className="hlp-pre">
                  <code>{s.code}</code>
                </pre>
              ) : null}
            </dd>
          </div>
        ))}
      </dl>

      <h3 className="hlp-h3">作品ページの紹介文の例</h3>
      <blockquote className="hlp-quote">{STORE_TEMPLATE_JA}</blockquote>
      <div className="hlp-actions">
        <button type="button" className="btn btn-sm" onClick={() => void copy(STORE_TEMPLATE_JA, '紹介文をコピー')}>
          紹介文をコピー
        </button>
      </div>

      <h3 className="hlp-h3">大切なこと</h3>
      <ul className="hlp-list">
        <li>
          <b>合言葉はネタバレ防止のしくみでDRMではありません。</b>
          {NOT_DRM_JA}有料の本編や、見られて困る内容はおまけに入れないでください。
        </li>
        <li>ヒントと予告文（ティーザー）は、しおりファイルを開けば誰でも読めます。</li>
        <li>発売後に合言葉を作り直すと、すでに入力したプレイヤーのおまけが開かなくなります。</li>
        <li>
          作品内でアプリ名・URL・QRコードを案内する前に、DLsiteの作品登録ルール（外部ツールやURLの記載について）を必ず確認してください。合言葉の文字列だけでも使えます。
        </li>
        <li>「返し合言葉」のおまけを使うと、プレイヤーがゲームに入力して隠し要素を開ける仕掛けも作れます（名前入力などで比較）。</li>
      </ul>

      <div className="hlp-actions">
        <a className="btn btn-primary" href={hrefFor({ name: 'studio' })}>
          サークル工房を開く
        </a>
      </div>
    </div>
  );
}

// ───────────────────────── プライバシー ─────────────────────────

function Privacy(): ReactNode {
  return (
    <div className="hlp-content">
      <h3 className="hlp-h3">外に送らないアプリです</h3>
      <ul className="hlp-list">
        <li>サーバーもアカウントもありません。登録やログインは不要です。</li>
        <li>アクセス解析・広告・外部サービスへの通信はありません（アプリ本体の読み込みを除きます）。</li>
        <li>DLsiteの作品ページは、あなたがボタンを押して確認したときだけ開きます。おしのびモードでは初めから表示しません。</li>
      </ul>

      <h3 className="hlp-h3">保存されるもの</h3>
      <p>
        本棚の作品（タイトル・表示名）、読み込んだしおりファイル、進捗、開いたヒント、プレイ記録、メモ、入力した合言葉、設定。これらはすべて、この端末のブラウザの中（IndexedDB）に保存されます。
      </p>
      <p>
        このほか、合言葉の受け渡し、本棚の絞り込みと並び順、「隠す」の状態を、タブを閉じると消える一時的な保存場所（sessionStorage）に置きます。
      </p>

      <h3 className="hlp-h3">PINについて</h3>
      <p>PINは画面ロックです。保存データそのものは暗号化されません。PINそのものは保存せず、確かめるための値だけを保存します。</p>

      <h3 className="hlp-h3">バックアップ</h3>
      <p>
        書き出したバックアップファイルには、作品名やメモが含まれます。ファイル名は目立たない名前（shiori-backup-日付.json）で、パスフレーズを付けると暗号化されます。PINと年齢確認は含まれません。
      </p>

      <h3 className="hlp-h3">閲覧履歴</h3>
      <p>
        QRコードで開いたアドレスは、ブラウザの履歴に残ることがあります。アドレスに含まれるのは、作品のID（作者が付けた識別子）と合言葉だけです。アプリは開いてすぐにアドレスを書き換えますが、気になる場合はブラウザの履歴から削除してください。
      </p>

      <h3 className="hlp-h3">年齢確認</h3>
      <p>最初の年齢確認は自己申告です。設定からいつでも取り消せます。</p>
    </div>
  );
}

// ───────────────────────── このアプリについて ─────────────────────────

function About(): ReactNode {
  return (
    <div className="hlp-content">
      <p className="hlp-about-name">
        {APP_NAME_JA}
        <span className="hlp-about-en">{APP_NAME_EN}</span>
        <span className="badge">v{APP_VERSION}</span>
      </p>
      <p className="hlp-callout">{DISCLAIMER_JA}</p>
      <ul className="hlp-list">
        <li>{NOT_DRM_JA}</li>
        <li>データはこの端末の中だけに保存されます。</li>
        <li>しおりファイルの内容は、作品の作者（サークル）またはプレイヤー自身が作ったものです。しおり帳は内容を確認・保証しません。</li>
        <li>アプリ本体とサンプルの内容は、全年齢向けの架空のものです。</li>
        <li>年齢確認は自己申告です。</li>
      </ul>
      <h3 className="hlp-h3">ライセンス</h3>
      <p>
        React（React DOM・Scheduler を含む）、zod、idb、fflate、qrcode-generator、Workbox、Vite などのオープンソースソフトウェアを利用しています。それぞれの著作権表示とライセンス（MIT、ISC、Apache License 2.0）の全文は、次のページで確認できます。
      </p>
      <div className="hlp-actions">
        <a className="btn" href={LICENSES_HREF} target="_blank" rel="noopener noreferrer">
          ライセンスの全文を見る
          <span className="visually-hidden">（新しいタブで開きます）</span>
        </a>
      </div>
    </div>
  );
}
