"""Calendar / time-of-day ("seasonality") strategies on H1 bars.

All bars are stamped in broker SERVER time (New York + 7h, bars labelled by OPEN
time).  Every rule here is expressed in a *local* clock of the market that causes
the effect and converted exactly through UTC, so daylight-saving changes in New
York, London and (never-DST) Tokyo are all handled:

    server = NY + 7h            (GMT+2 in US winter, GMT+3 in US summer)
    JST    = UTC + 9h           -> JST = server + 7h (US winter) / + 6h (US summer)
    London = UTC (+1h in BST)   -> the 16:00 London fix is 18:00 server except for
                                   the 2-3 weeks a year when US and UK DST differ

Tokyo fix (仲値) is set at 09:55 JST = 02:55 server (US winter) / 03:55 server
(US summer).  With H1 bars the position opened at the open of the H1 bar starting
at `entry_hour` local and is closed at the open of the H1 bar starting at
`exit_hour` local (i.e. exit_hour=10 JST closes 5 minutes after the fix).
Optional `exit_early_min` / `entry_early_min` add an extra exit / entry decision that
many minutes before exit_hour / entry_hour; they only have an effect with minute-bar
execution (with H1 execution they map onto the regular bar and change nothing).

Selected configuration of the research (scripts/research_seasonality.py, chosen on
IS 2005-2014 only; verdict "marginal", see reports/seasonality.md):
    SeasonalWindow(tz="JST", entry_hour=10, exit_hour=15, ccy="JPY", ccy_dir=+1,
                   days="gotobi", stop_atr=0.5, atr_n=14, entry_early_min=5)
    on USDJPY with minute-bar execution = sell USDJPY at the 09:55 JST Tokyo fix on
    gotobi days, stop 0.5 x D1 ATR(14), close at 15:00 JST.

Decisions are made on CLOSED bars only: the decision row of bar t (open time t,
close time t+1h) is executed by the engine at the open of the next bar, so an
entry at local hh:00 is signalled on the bar that CLOSES at hh:00.  The protective
stop is `stop_atr` x ATR(atr_n) of the last CLOSED D1 bar and is always set.
Every position is flat outside its holding window (exit flags on every other bar),
so no trade can survive a data gap or the weekend.

Calendars (implementable in MQL5 with a date table / simple rules):
  * Japanese business day: Mon-Fri, not a Japanese public holiday, not a bank
    holiday (Dec 31, Jan 1-3).  Public holidays are generated by rule (fixed dates,
    Happy-Monday rules, equinox formula, substitute and citizens' holidays, the
    2019 enthronement and 2020/21 Olympic special dates).
  * Gotobi (五十日): for each target day 5, 10, 15, 20, 25 and the last calendar day
    of the month, the last Japanese business day on or before it.
  * Month end (London): last Mon-Fri of the calendar month in London time.
"""
from __future__ import annotations

import calendar
from datetime import date, timedelta
from functools import lru_cache

import numpy as np
import pandas as pd

from .. import indicators as I
from ..engine import TF_DURATION
from .base import Strategy, empty_decisions

SERVER_OFFSET = pd.Timedelta(hours=7)
TZ = {"JST": "Asia/Tokyo", "LDN": "Europe/London", "NY": "America/New_York"}


# ------------------------------------------------------------------ time helpers
def server_to_utc(idx: pd.DatetimeIndex) -> pd.DatetimeIndex:
    """Server time (naive, NY+7h) -> tz-aware UTC.  FX has no bars in the hours
    where NY local time is ambiguous / non-existent (Sunday 01:00-03:00 NY)."""
    ny = pd.DatetimeIndex(idx) - SERVER_OFFSET
    return ny.tz_localize("America/New_York", ambiguous="NaT",
                          nonexistent="NaT").tz_convert("UTC")


def to_local(idx: pd.DatetimeIndex, tz: str) -> pd.DatetimeIndex:
    """Server time -> naive local wall-clock time in `tz` (JST / LDN / NY / SRV)."""
    if tz == "SRV":
        return pd.DatetimeIndex(idx)
    return server_to_utc(idx).tz_convert(TZ[tz]).tz_localize(None)


def align_closed(htf: pd.Series, htf_tf: str, ltf_index: pd.DatetimeIndex,
                 ltf_tf: str) -> np.ndarray:
    """Value of the last higher-timeframe bar that has CLOSED by the close of each
    lower-timeframe bar (both indexed by bar open time)."""
    htf_close = (htf.index + TF_DURATION[htf_tf]).values
    ltf_close = (ltf_index + TF_DURATION[ltf_tf]).values
    pos = np.searchsorted(htf_close, ltf_close, side="right") - 1
    vals = htf.to_numpy(dtype=float)
    out = np.full(len(ltf_index), np.nan)
    ok = pos >= 0
    out[ok] = vals[pos[ok]]
    return out


# ------------------------------------------------------------ Japanese calendar
def _nth_monday(y: int, m: int, n: int) -> date:
    d = date(y, m, 1)
    first = d + timedelta(days=(0 - d.weekday()) % 7)
    return first + timedelta(weeks=n - 1)


def _vernal(y: int) -> date:
    return date(y, 3, int(20.8431 + 0.242194 * (y - 1980) - int((y - 1980) / 4)))


def _autumnal(y: int) -> date:
    return date(y, 9, int(23.2488 + 0.242194 * (y - 1980) - int((y - 1980) / 4)))


@lru_cache(maxsize=None)
def jp_public_holidays(y: int) -> frozenset:
    """Japanese national holidays of year y (verified 2004-2030 against python-holidays and
    jpholiday; 2000-2003 differ because of older Happy-Monday / substitute rules)."""
    h = {date(y, 1, 1), _nth_monday(y, 1, 2), date(y, 2, 11), _vernal(y), date(y, 4, 29),
         date(y, 5, 3), date(y, 5, 4), date(y, 5, 5), _autumnal(y), date(y, 11, 3),
         date(y, 11, 23)}
    if y <= 2018:
        h.add(date(y, 12, 23))
    if y >= 2020:
        h.add(date(y, 2, 23))
    if y == 2020:
        h |= {date(2020, 7, 23), date(2020, 7, 24), date(2020, 8, 10)}
    elif y == 2021:
        h |= {date(2021, 7, 22), date(2021, 7, 23), date(2021, 8, 8)}
    else:
        h.add(_nth_monday(y, 7, 3))                 # Marine Day
        h.add(_nth_monday(y, 10, 2))                # Sports Day
        if y >= 2016:
            h.add(date(y, 8, 11))                   # Mountain Day
    h.add(_nth_monday(y, 9, 3))                     # Respect for the Aged Day
    if y == 2019:
        h |= {date(2019, 4, 30), date(2019, 5, 1), date(2019, 5, 2), date(2019, 10, 22)}
    # citizens' holiday: a weekday sandwiched between two holidays
    for d in list(h):
        mid = d + timedelta(days=1)
        if mid not in h and (mid + timedelta(days=1)) in h and mid.weekday() != 6:
            h.add(mid)
    # substitute holiday: a holiday on Sunday moves to the next non-holiday day
    for d in sorted(h):
        if d.weekday() == 6:
            s = d + timedelta(days=1)
            while s in h:
                s += timedelta(days=1)
            h.add(s)
    return frozenset(h)


def jp_business_day(d: date) -> bool:
    if d.weekday() >= 5:
        return False
    if (d.month, d.day) in ((12, 31), (1, 1), (1, 2), (1, 3)):
        return False
    return d not in jp_public_holidays(d.year)


@lru_cache(maxsize=None)
def gotobi_set(y0: int = 2000, y1: int = 2030) -> frozenset:
    """Gotobi business days: last JP business day on/before 5,10,15,20,25,month-end."""
    out = set()
    for y in range(y0, y1 + 1):
        for m in range(1, 13):
            last = calendar.monthrange(y, m)[1]
            for t in (5, 10, 15, 20, 25, last):
                d = date(y, m, t)
                while not jp_business_day(d):
                    d -= timedelta(days=1)
                out.add(d)
    return frozenset(out)


def _day_flags(local_dates: pd.DatetimeIndex, days: str) -> np.ndarray:
    """Boolean day filter evaluated on local calendar dates."""
    if days == "all":
        return np.ones(len(local_dates), bool)
    uniq = pd.DatetimeIndex(local_dates.unique()).dropna()
    if days in ("gotobi", "non_gotobi", "jp_bday"):
        g = gotobi_set()
        m = {}
        for d in uniq:
            dd = d.date()
            if days == "jp_bday":
                m[d] = jp_business_day(dd)
            elif days == "gotobi":
                m[d] = dd in g
            else:
                m[d] = jp_business_day(dd) and dd not in g
    elif days in ("month_end", "not_month_end"):
        m = {}
        for d in uniq:
            dd = d.date()
            last = date(dd.year, dd.month, calendar.monthrange(dd.year, dd.month)[1])
            while last.weekday() >= 5:
                last -= timedelta(days=1)
            me = dd == last
            m[d] = me if days == "month_end" else (not me and dd.weekday() < 5)
    else:
        raise ValueError(days)
    return pd.Series(local_dates).map(m).fillna(False).to_numpy(bool)


def ccy_direction(symbol_base: str, symbol_quote: str, ccy: str, ccy_dir: int) -> int:
    """Pair direction that buys (ccy_dir=+1) or sells (-1) currency `ccy` (0 = n/a)."""
    if symbol_base == ccy:
        return int(ccy_dir)
    if symbol_quote == ccy:
        return -int(ccy_dir)
    return 0


# ------------------------------------------------------------------ strategies
class SeasonalWindow(Strategy):
    """Hold a fixed-direction position between two local clock times on chosen days.

    tz          clock the rule is written in: JST, LDN, NY or SRV
    entry_hour  open the position at the open of the H1 bar starting entry_hour:00
    exit_hour   close it at the open of the H1 bar starting exit_hour:00
                (wraps past midnight if exit_hour <= entry_hour)
    ccy/ccy_dir buy (+1) or sell (-1) currency `ccy` (e.g. ccy="JPY", ccy_dir=-1 is
                long USDJPY / EURJPY); pairs without `ccy` never trade
    days        all | gotobi | non_gotobi | jp_bday | month_end | not_month_end,
                evaluated on the LOCAL date at entry
    weekdays    optional tuple of local weekdays (0=Mon) allowed at entry
    stop_atr    protective stop = stop_atr x ATR(atr_n) of the last closed D1 bar
    min_server_hour  never enter before this server hour (rollover spreads)
    exit_early_min   extra exit exit_early_min minutes before exit_hour (M1 exec only)
    entry_early_min  extra entry entry_early_min minutes before entry_hour (M1 exec only)
    """
    name = "seasonal_window"
    tf = "H1"

    def __init__(self, tz="JST", entry_hour=8, exit_hour=10, ccy="JPY", ccy_dir=-1,
                 days="gotobi", weekdays=None, stop_atr=0.5, atr_n=14, min_server_hour=1,
                 exit_early_min=0, entry_early_min=0, tf="H1"):
        self.tz, self.entry_hour, self.exit_hour = tz, int(entry_hour), int(exit_hour)
        self.ccy, self.ccy_dir, self.days = ccy, int(ccy_dir), days
        self.weekdays = tuple(weekdays) if weekdays is not None else None
        self.stop_atr, self.atr_n = float(stop_atr), int(atr_n)
        self.min_server_hour, self.exit_early_min = int(min_server_hour), int(exit_early_min)
        self.entry_early_min, self.tf = int(entry_early_min), tf
        if self.entry_hour == self.exit_hour:
            raise ValueError("entry_hour == exit_hour")

    def _hold_len(self) -> int:
        return (self.exit_hour - self.entry_hour) % 24

    def window_masks(self, idx: pd.DatetimeIndex):
        """(entry_signal, in_hold, local_close) on the H1 index (by bar CLOSE time)."""
        close_srv = idx + pd.Timedelta(hours=1)
        loc = to_local(close_srv, self.tz)
        hr = np.asarray(loc.hour)
        valid = ~pd.isna(loc)
        # hours (by close) after entry_hour inside the window: entry_hour .. exit_hour-1
        k = (hr - self.entry_hour) % 24
        in_hold = valid & (k < self._hold_len())
        entry = valid & (hr == self.entry_hour) & (np.asarray(loc.minute) == 0)
        entry &= np.asarray(close_srv.hour) >= self.min_server_hour
        entry &= _day_flags(loc.normalize(), self.days)
        if self.weekdays is not None:
            entry &= np.isin(np.asarray(loc.dayofweek), self.weekdays)
        return entry, in_hold, loc

    def decisions(self, ctx) -> pd.DataFrame:
        b = ctx.bars("H1")
        d1 = ctx.bars("D1")
        idx = b.index
        d = empty_decisions(idx)
        dr = ccy_direction(ctx.inst.base, ctx.inst.quote, self.ccy, self.ccy_dir)
        d["_dir"] = dr                  # helper columns (ignored by the engine) used by
        d["_hold"] = False              # SeasonalCombo to merge holding windows
        if dr == 0:
            return d
        atr = align_closed(I.atr(d1, self.atr_n), "D1", idx, "H1")
        entry, in_hold, _ = self.window_masks(idx)
        stop = self.stop_atr * atr
        entry &= np.isfinite(stop) & (stop > 0)
        d["long_entry"] = entry & (dr > 0)
        d["short_entry"] = entry & (dr < 0)
        d["stop_dist"] = np.where(entry, stop, np.nan)
        d["exit_long"] = ~in_hold
        d["exit_short"] = ~in_hold
        d["_hold"] = in_hold
        extra = []
        if self.exit_early_min > 0:
            # extra rows whose (fictional) close is exit_early_min before the exit bar
            # open; with H1 execution they map onto the regular exit bar (no effect).
            last_hold = in_hold & ~np.r_[in_hold[1:], False]      # bar closing at exit-1h
            t = idx[last_hold] + pd.Timedelta(hours=1) - pd.Timedelta(minutes=self.exit_early_min)
            x = empty_decisions(t)
            x["exit_long"] = True
            x["exit_short"] = True
            x["_dir"] = dr
            x["_hold"] = False
            extra.append(x)
        if self.entry_early_min > 0:
            # copy of each entry row acting entry_early_min before entry_hour:00.  The
            # entry decision uses only the calendar and the last CLOSED D1 ATR, so acting
            # a few minutes earlier uses no additional information.  With H1 execution
            # the copy maps onto the regular entry bar (no effect).
            e = d[entry].copy()
            e.index = e.index - pd.Timedelta(minutes=self.entry_early_min)
            e["exit_long"] = False
            e["exit_short"] = False
            e["_hold"] = True
            extra.append(e)
        if extra:
            d = pd.concat([d, *extra]).sort_index(kind="stable")
        return d


class FixReversal(Strategy):
    """Fade the move into a benchmark fix.

    At the close of the H1 bar ending at fix_hour:00 local, measure
    r = close - open(fix_hour - look hours).  If r > min_move_atr x ATR, sell at the
    next open (fix_hour:00); if r < -min_move_atr x ATR, buy.  Exit at exit_hour:00
    local.  Pairs must contain `ccy` (default USD) unless ccy is None.
    """
    name = "fix_reversal"
    tf = "H1"

    def __init__(self, tz="LDN", fix_hour=16, look=2, exit_hour=18, days="month_end",
                 min_move_atr=0.0, stop_atr=0.5, atr_n=14, ccy="USD", weekdays=None,
                 min_server_hour=1, follow=False, tf="H1"):
        self.tz, self.fix_hour, self.look, self.exit_hour = tz, int(fix_hour), int(look), int(exit_hour)
        self.days, self.min_move_atr = days, float(min_move_atr)
        self.stop_atr, self.atr_n, self.ccy = float(stop_atr), int(atr_n), ccy
        self.weekdays = tuple(weekdays) if weekdays is not None else None
        self.min_server_hour, self.follow, self.tf = int(min_server_hour), bool(follow), tf

    def decisions(self, ctx) -> pd.DataFrame:
        b = ctx.bars("H1")
        d1 = ctx.bars("D1")
        idx = b.index
        d = empty_decisions(idx)
        if self.ccy is not None and self.ccy not in (ctx.inst.base, ctx.inst.quote):
            return d
        win = SeasonalWindow(tz=self.tz, entry_hour=self.fix_hour, exit_hour=self.exit_hour,
                             days=self.days, weekdays=self.weekdays,
                             min_server_hour=self.min_server_hour)
        entry, in_hold, loc = win.window_masks(idx)
        # open of the bar that opened `look` hours before the fix, located by local
        # clock on the same local date (bars <= t only)
        open_loc = to_local(idx, self.tz)
        start_key = pd.Series(np.asarray(b["open"]), index=open_loc)
        start_key = start_key[~start_key.index.isna()]
        start_key = start_key[~start_key.index.duplicated(keep="first")]
        want = loc - pd.Timedelta(hours=self.look)            # local open time of 1st bar
        o0 = start_key.reindex(want).to_numpy()
        r = b["close"].to_numpy() - o0
        atr = align_closed(I.atr(d1, self.atr_n), "D1", idx, "H1")
        thr = self.min_move_atr * atr
        ok = entry & np.isfinite(r) & np.isfinite(atr) & (atr > 0)
        up = ok & (r > thr) & (r != 0)
        dn = ok & (r < -thr) & (r != 0)
        if self.follow:
            up, dn = dn, up
        d["long_entry"] = dn
        d["short_entry"] = up
        d["stop_dist"] = np.where(up | dn, self.stop_atr * atr, np.nan)
        d["exit_long"] = ~in_hold
        d["exit_short"] = ~in_hold
        d["_dir"] = 0                   # either direction
        d["_hold"] = in_hold
        return d


class SeasonalCombo(Strategy):
    """Union of several seasonal strategies on one symbol.

    Rows of all parts are merged on the union of their indices.  The first part
    that signals an entry on a row wins.  A long (short) position is held while any
    long-direction (short-direction) part is inside its holding window; everywhere
    else the matching exit flag is set, so a pre-fix long whose window ends at the
    same moment a post-fix short window starts is closed and reversed on that row.
    """
    name = "seasonal_combo"
    tf = "H1"

    def __init__(self, parts):
        self.parts = list(parts)

    def params(self):
        return {"parts": [f"{p.name}:{p.params()}" for p in self.parts]}

    def decisions(self, ctx):
        frames = [p.decisions(ctx) for p in self.parts]
        idx = frames[0].index
        for f in frames[1:]:
            idx = idx.union(f.index)
        d = empty_decisions(idx)
        taken = np.zeros(len(idx), bool)
        hold_long = np.zeros(len(idx), bool)
        hold_short = np.zeros(len(idx), bool)
        for f in frames:
            f = f[~f.index.duplicated(keep="last")]
            dr = int(f["_dir"].iloc[0]) if len(f) else 0
            hold = f["_hold"].astype(float).reindex(idx).ffill().fillna(0).to_numpy() > 0
            f = f.reindex(idx)
            le = f["long_entry"].fillna(False).to_numpy(bool)
            se = f["short_entry"].fillna(False).to_numpy(bool)
            new = (le | se) & ~taken
            d.loc[new, "long_entry"] = le[new]
            d.loc[new, "short_entry"] = se[new]
            d.loc[new, "stop_dist"] = f["stop_dist"].to_numpy()[new]
            taken |= new
            if dr >= 0:
                hold_long |= hold
            if dr <= 0:
                hold_short |= hold
        d["exit_long"] = ~hold_long
        d["exit_short"] = ~hold_short
        return d


class WeekendGap(Strategy):
    """Fade the weekend gap on Monday.

    The first H1 bar of the week (server Monday 00:00) opens with a gap
    g = open - previous Friday close.  To avoid rollover spreads the decision is
    taken on that bar's close (01:00 server): if |g| > min_gap_atr x ATR and the
    01:00 price has not yet crossed back through Friday's close, trade toward
    Friday's close at the 01:00 open with take-profit at Friday's close and the
    protective ATR stop.  Anything still open exits at exit_server_hour:00 Monday.
    """
    name = "weekend_gap"
    tf = "H1"

    def __init__(self, min_gap_atr=0.25, exit_server_hour=12, stop_atr=0.5, atr_n=14,
                 use_tp=True, tf="H1"):
        self.min_gap_atr, self.exit_server_hour = float(min_gap_atr), int(exit_server_hour)
        self.stop_atr, self.atr_n, self.use_tp, self.tf = float(stop_atr), int(atr_n), bool(use_tp), tf

    def decisions(self, ctx) -> pd.DataFrame:
        b = ctx.bars("H1")
        d1 = ctx.bars("D1")
        idx = b.index
        d = empty_decisions(idx)
        prev_close = b["close"].shift(1).to_numpy()
        gap_before = np.r_[np.inf, np.diff(idx.values).astype("timedelta64[h]").astype(float)]
        first = (idx.dayofweek == 0) & (idx.hour == 0) & (gap_before > 24)
        g = b["open"].to_numpy() - prev_close
        c = b["close"].to_numpy()
        atr = align_closed(I.atr(d1, self.atr_n), "D1", idx, "H1")
        ok = first & np.isfinite(g) & np.isfinite(atr) & (np.abs(g) > self.min_gap_atr * atr)
        up = ok & (g > 0) & (c > prev_close)       # still above Friday close -> sell
        dn = ok & (g < 0) & (c < prev_close)
        d["short_entry"] = up
        d["long_entry"] = dn
        d["stop_dist"] = np.where(up | dn, self.stop_atr * atr, np.nan)
        if self.use_tp:
            d["tp_dist"] = np.where(up | dn, np.abs(c - prev_close), np.nan)
        close_h = (idx + pd.Timedelta(hours=1))
        in_hold = (idx.dayofweek == 0) & (np.asarray(close_h.hour) >= 1) & \
                  (np.asarray(close_h.hour) < self.exit_server_hour)
        d["exit_long"] = ~in_hold
        d["exit_short"] = ~in_hold
        d["_dir"] = 0
        d["_hold"] = in_hold
        return d
