// M7 voice strings (namespace "voice"): the voice card (C-8 ⑤) and the voice check sheet (S5).
// Playful self-discovery, never a verdict: the reading only ever says "this time, the voice was …".
// No skill, personality, age or gender words anywhere (voice.test.ts scans every locale).
import { defineStrings } from '../../i18n'

export const V = defineStrings('voice', {
  ja: {
    // card (before)
    'card.q': '今夜の声を見てみる？',
    'card.mic': '3秒ハミング',
    'card.micSub': '任意',
    'card.quiz': '3つの質問で',
    'card.quizSub': 'タップで答える',
    'card.noRec': '録音は保存しません',
    'primary.measure': '声を見る',
    reserveKey: '{k}で予約',
    reserveOriginal: '原曲キーで予約',
    // sheet header / choose
    label: '今夜の声',
    title: '今夜の声を見てみる？',
    lead: '今回の声の特徴を、3本の光で見てみます',
    'path.mic': '3秒ハミング',
    'path.micOpt': '任意',
    'path.micSub': '好きな高さで「ん〜」と3秒',
    'path.quiz': '3つの質問で',
    'path.quizSub': 'タップで答えるだけ',
    privacy: '録音は保存しません。音の高さと強さを、その場で数えるだけです',
    // the three factors
    'f.power': '迫力',
    'f.care': '丁寧さ',
    'f.bright': '明るさ',
    // listening
    'mic.arming': 'マイクの準備をしています…',
    'mic.hum': 'ハミングしてみて',
    'mic.humSub': 'のばしたり、揺らしたり。好きな高さで',
    'mic.cancel': 'やめる',
    'mic.toQuiz': '3つの質問にする',
    'mic.quiet': '声が届かなかったみたい',
    'mic.quietSub': 'もう少しマイクに近づいて、もう一度どうぞ',
    'mic.retry': 'もう一度',
    'mic.range': '今回出ていた音 {lo}〜{hi}',
    fallback: 'マイクが使えないので、3つの質問で見てみましょう',
    // quiz
    'q.high': '高いところ、どう？',
    'a.high.easy': 'ラクに届く',
    'a.high.normal': 'ほどほど',
    'a.high.hard': '低めが落ち着く',
    'q.chorus': 'サビでは、どう歌う？',
    'a.chorus.belt': '思いきり張る',
    'a.chorus.soft': 'やさしく歌う',
    'a.chorus.between': 'その間くらい',
    'q.style': '好きな歌い方は？',
    'a.style.ride': 'リズムに乗る',
    'a.style.talk': '語るように',
    'a.style.sustain': '長くのばす',
    'quiz.step': '{n} / 3',
    'quiz.back': '戻る',
    // result
    result: '今回の声は{type}',
    'method.mic': 'ハミングから',
    'method.quiz': '3つの答えから',
    'ev.dynamics': '強弱の変化が大きい歌い方でした',
    'ev.steady': '音の高さがぶれずに、まっすぐ伸びていました',
    'ev.core': '声の芯が太く、まっすぐ前に出ていました',
    'ev.bright': '明るく抜ける響きでした',
    'ev.rhythm': 'リズムの刻みが一定で、ノリがありました',
    'ev.wide': '3秒のあいだに、音の高さが大きく動きました',
    'ev.soft': 'やわらかく、落ち着いた響きでした',
    'ev.q.highEasy': '高いところまでラクに届く、という答えでした',
    'ev.q.highHard': '低めが落ち着く、という答えでした',
    'ev.q.belt': 'サビは思いきり張る、という答えでした',
    'ev.q.soft': 'サビはやさしく歌う、という答えでした',
    'ev.q.between': 'サビは張りすぎず、やさしすぎず、という答えでした',
    'ev.q.ride': 'リズムに乗って歌う、という答えでした',
    'ev.q.talk': '語るように歌う、という答えでした',
    'ev.q.sustain': '長く音をのばす歌い方、という答えでした',
    'ev.q.mix': '3つの答えを重ねて見てみました',
    'try.clear': '高い音がのびる曲を試してみませんか',
    'try.power': 'サビで思いきり張れる曲を試してみませんか',
    'try.groove': 'リズムで遊べる曲を試してみませんか',
    'try.emotional': '抑揚をつけられるフレーズがある曲を試してみませんか',
    'song.label': 'この声で歌ってみたい1曲',
    'key.down': 'キーを{n}下げると歌いやすい可能性があります',
    'key.up': 'キーを{n}上げると声が前に出やすい可能性があります',
    'key.orig': '原曲キーで歌いやすい可能性があります',
    'key.origShort': '原曲',
    other: 'ほかの1曲',
    again: 'もう一度',
    note: '声は曲や日によって変わります',
    stamped: '今夜',
    noSong: 'いまは予約できる候補がありません',
    skip: 'タップで先へ',
    hypo: 'ナビの見立て',
  },
  en: {
    'card.q': 'See your voice tonight?',
    'card.mic': '3-sec hum',
    'card.micSub': 'optional',
    'card.quiz': '3 questions',
    'card.quizSub': 'just tap',
    'card.noRec': 'Nothing is recorded',
    'primary.measure': 'See the voice',
    reserveKey: 'Reserve at {k}',
    reserveOriginal: 'Reserve in original key',
    label: 'Tonight’s voice',
    title: 'See your voice tonight?',
    lead: 'Three beams of light show how your voice sounded this time',
    'path.mic': '3-second hum',
    'path.micOpt': 'optional',
    'path.micSub': 'Hum “mmm” at any pitch for 3 seconds',
    'path.quiz': '3 questions',
    'path.quizSub': 'Just tap your answers',
    privacy: 'Nothing is recorded. Only pitch and loudness are counted, right here',
    'f.power': 'Power',
    'f.care': 'Care',
    'f.bright': 'Brightness',
    'mic.arming': 'Getting the mic ready…',
    'mic.hum': 'Hum along',
    'mic.humSub': 'Hold it, wobble it, any pitch you like',
    'mic.cancel': 'Stop',
    'mic.toQuiz': 'Use 3 questions',
    'mic.quiet': 'The voice didn’t reach the mic',
    'mic.quietSub': 'Come a little closer and try again',
    'mic.retry': 'Try again',
    'mic.range': 'Notes this time {lo}–{hi}',
    fallback: 'The mic isn’t available, so let’s look with 3 questions',
    'q.high': 'How do high notes feel?',
    'a.high.easy': 'Easy to reach',
    'a.high.normal': 'Somewhere in between',
    'a.high.hard': 'Lower feels calmer',
    'q.chorus': 'How do you sing the chorus?',
    'a.chorus.belt': 'Belt it out',
    'a.chorus.soft': 'Keep it gentle',
    'a.chorus.between': 'Somewhere between',
    'q.style': 'Your favourite way to sing?',
    'a.style.ride': 'Ride the rhythm',
    'a.style.talk': 'Like telling a story',
    'a.style.sustain': 'Hold long notes',
    'quiz.step': '{n} / 3',
    'quiz.back': 'Back',
    result: 'This time, the voice was {type}',
    'method.mic': 'from the hum',
    'method.quiz': 'from 3 answers',
    'ev.dynamics': 'The loudness moved a lot as you sang',
    'ev.steady': 'The pitch stayed steady and straight',
    'ev.core': 'The sound had a solid core and came forward',
    'ev.bright': 'The sound rang out brightly',
    'ev.rhythm': 'The beat stayed even and bouncy',
    'ev.wide': 'The pitch travelled a long way in 3 seconds',
    'ev.soft': 'The sound was soft and settled',
    'ev.q.highEasy': 'The answer was: high notes are easy to reach',
    'ev.q.highHard': 'The answer was: lower feels calmer',
    'ev.q.belt': 'The answer was: belt out the chorus',
    'ev.q.soft': 'The answer was: keep the chorus gentle',
    'ev.q.between': 'The answer was: a chorus between belting and gentle',
    'ev.q.ride': 'The answer was: ride the rhythm',
    'ev.q.talk': 'The answer was: sing like telling a story',
    'ev.q.sustain': 'The answer was: hold long notes',
    'ev.q.mix': 'All three answers were layered together',
    'try.clear': 'How about a song where the high notes can soar?',
    'try.power': 'How about a song with a chorus to belt out?',
    'try.groove': 'How about a song to play with the rhythm?',
    'try.emotional': 'How about a song with phrases to shape and swell?',
    'song.label': 'One song to try with this voice',
    'key.down': 'Lowering the key by {n} may make it easier to sing',
    'key.up': 'Raising the key by {n} may help the voice come forward',
    'key.orig': 'The original key may be easy to sing',
    'key.origShort': 'orig.',
    other: 'Another song',
    again: 'Again',
    note: 'Voices change with the song and the day',
    stamped: 'Tonight',
    noSong: 'No reservable song to suggest right now',
    skip: 'Tap to skip ahead',
    hypo: 'Navi’s guess',
  },
  zhHant: {
    'card.q': '看看今晚的聲音？',
    'card.mic': '哼唱3秒',
    'card.micSub': '可選',
    'card.quiz': '回答3個問題',
    'card.quizSub': '點一點就好',
    'card.noRec': '不會保存錄音',
    'primary.measure': '看看聲音',
    reserveKey: '以{k}點歌',
    reserveOriginal: '用原調點歌',
    label: '今晚的聲音',
    title: '看看今晚的聲音？',
    lead: '用3道光，看看這次聲音的特色',
    'path.mic': '哼唱3秒',
    'path.micOpt': '可選',
    'path.micSub': '用喜歡的音高「嗯～」3秒',
    'path.quiz': '回答3個問題',
    'path.quizSub': '點選答案就好',
    privacy: '不會保存錄音。只在當下計算音高與音量',
    'f.power': '力度',
    'f.care': '細膩',
    'f.bright': '明亮',
    'mic.arming': '正在準備麥克風…',
    'mic.hum': '哼哼看吧',
    'mic.humSub': '拉長、搖晃都可以，用喜歡的音高',
    'mic.cancel': '停止',
    'mic.toQuiz': '改用3個問題',
    'mic.quiet': '聲音好像沒有傳到麥克風',
    'mic.quietSub': '再靠近麥克風一點，再試一次吧',
    'mic.retry': '再試一次',
    'mic.range': '這次出現的音 {lo}～{hi}',
    fallback: '麥克風無法使用，改用3個問題來看看吧',
    'q.high': '高音的部分，感覺如何？',
    'a.high.easy': '輕鬆就到',
    'a.high.normal': '普普通通',
    'a.high.hard': '低一點比較自在',
    'q.chorus': '副歌時，怎麼唱？',
    'a.chorus.belt': '盡情放聲',
    'a.chorus.soft': '輕柔地唱',
    'a.chorus.between': '介於兩者之間',
    'q.style': '喜歡的唱法是？',
    'a.style.ride': '跟著節奏走',
    'a.style.talk': '像在說故事',
    'a.style.sustain': '長長地延音',
    'quiz.step': '{n} / 3',
    'quiz.back': '返回',
    result: '這次的聲音是{type}',
    'method.mic': '來自哼唱',
    'method.quiz': '來自3個答案',
    'ev.dynamics': '強弱變化很大的唱法',
    'ev.steady': '音高穩定，筆直地延伸',
    'ev.core': '聲音紮實，直直地往前送',
    'ev.bright': '明亮、通透的聲響',
    'ev.rhythm': '節奏穩定，很有律動',
    'ev.wide': '3秒內音高大幅移動',
    'ev.soft': '柔和、沉穩的聲響',
    'ev.q.highEasy': '答案是：高音輕鬆就到',
    'ev.q.highHard': '答案是：低一點比較自在',
    'ev.q.belt': '答案是：副歌盡情放聲',
    'ev.q.soft': '答案是：副歌輕柔地唱',
    'ev.q.between': '答案是：副歌介於放聲與輕柔之間',
    'ev.q.ride': '答案是：跟著節奏唱',
    'ev.q.talk': '答案是：像說故事一樣唱',
    'ev.q.sustain': '答案是：長長地延音',
    'ev.q.mix': '把3個答案疊在一起來看',
    'try.clear': '要不要試試高音能舒展的歌？',
    'try.power': '要不要試試副歌能盡情放聲的歌？',
    'try.groove': '要不要試試能玩節奏的歌？',
    'try.emotional': '要不要試試有抑揚起伏樂句的歌？',
    'song.label': '想用這個聲音試唱的1首',
    'key.down': '降{n}個調可能會比較好唱',
    'key.up': '升{n}個調可能讓聲音更往前',
    'key.orig': '用原調可能就很好唱',
    'key.origShort': '原調',
    other: '換1首',
    again: '再一次',
    note: '聲音會隨歌曲與日子改變',
    stamped: '今晚',
    noSong: '現在沒有可點的候選歌曲',
    skip: '點一下繼續',
    hypo: '導航的推測',
  },
  zhHans: {
    'card.q': '看看今晚的声音？',
    'card.mic': '哼唱3秒',
    'card.micSub': '可选',
    'card.quiz': '回答3个问题',
    'card.quizSub': '点一点就好',
    'card.noRec': '不会保存录音',
    'primary.measure': '看看声音',
    reserveKey: '以{k}点歌',
    reserveOriginal: '用原调点歌',
    label: '今晚的声音',
    title: '看看今晚的声音？',
    lead: '用3道光，看看这次声音的特点',
    'path.mic': '哼唱3秒',
    'path.micOpt': '可选',
    'path.micSub': '用喜欢的音高“嗯～”3秒',
    'path.quiz': '回答3个问题',
    'path.quizSub': '点选答案就好',
    privacy: '不会保存录音。只在当下计算音高与音量',
    'f.power': '力度',
    'f.care': '细腻',
    'f.bright': '明亮',
    'mic.arming': '正在准备麦克风…',
    'mic.hum': '哼哼看吧',
    'mic.humSub': '拉长、摇晃都可以，用喜欢的音高',
    'mic.cancel': '停止',
    'mic.toQuiz': '改用3个问题',
    'mic.quiet': '声音好像没有传到麦克风',
    'mic.quietSub': '再靠近麦克风一点，再试一次吧',
    'mic.retry': '再试一次',
    'mic.range': '这次出现的音 {lo}～{hi}',
    fallback: '麦克风无法使用，改用3个问题来看看吧',
    'q.high': '高音的部分，感觉如何？',
    'a.high.easy': '轻松就到',
    'a.high.normal': '普普通通',
    'a.high.hard': '低一点比较自在',
    'q.chorus': '副歌时，怎么唱？',
    'a.chorus.belt': '尽情放声',
    'a.chorus.soft': '轻柔地唱',
    'a.chorus.between': '介于两者之间',
    'q.style': '喜欢的唱法是？',
    'a.style.ride': '跟着节奏走',
    'a.style.talk': '像在讲故事',
    'a.style.sustain': '长长地延音',
    'quiz.step': '{n} / 3',
    'quiz.back': '返回',
    result: '这次的声音是{type}',
    'method.mic': '来自哼唱',
    'method.quiz': '来自3个答案',
    'ev.dynamics': '强弱变化很大的唱法',
    'ev.steady': '音高稳定，笔直地延伸',
    'ev.core': '声音扎实，直直地往前送',
    'ev.bright': '明亮、通透的声响',
    'ev.rhythm': '节奏稳定，很有律动',
    'ev.wide': '3秒内音高大幅移动',
    'ev.soft': '柔和、沉稳的声响',
    'ev.q.highEasy': '答案是：高音轻松就到',
    'ev.q.highHard': '答案是：低一点比较自在',
    'ev.q.belt': '答案是：副歌尽情放声',
    'ev.q.soft': '答案是：副歌轻柔地唱',
    'ev.q.between': '答案是：副歌介于放声与轻柔之间',
    'ev.q.ride': '答案是：跟着节奏唱',
    'ev.q.talk': '答案是：像讲故事一样唱',
    'ev.q.sustain': '答案是：长长地延音',
    'ev.q.mix': '把3个答案叠在一起来看',
    'try.clear': '要不要试试高音能舒展的歌？',
    'try.power': '要不要试试副歌能尽情放声的歌？',
    'try.groove': '要不要试试能玩节奏的歌？',
    'try.emotional': '要不要试试有抑扬起伏乐句的歌？',
    'song.label': '想用这个声音试唱的1首',
    'key.down': '降{n}个调可能会比较好唱',
    'key.up': '升{n}个调可能让声音更往前',
    'key.orig': '用原调可能就很好唱',
    'key.origShort': '原调',
    other: '换1首',
    again: '再一次',
    note: '声音会随歌曲与日子改变',
    stamped: '今晚',
    noSong: '现在没有可点的候选歌曲',
    skip: '点一下继续',
    hypo: '导航的推测',
  },
  ko: {
    'card.q': '오늘 밤 목소리를 볼까요?',
    'card.mic': '3초 허밍',
    'card.micSub': '선택',
    'card.quiz': '질문 3개로',
    'card.quizSub': '탭으로 답하기',
    'card.noRec': '녹음은 저장하지 않아요',
    'primary.measure': '목소리 보기',
    reserveKey: '{k}로 예약',
    reserveOriginal: '원키로 예약',
    label: '오늘 밤 목소리',
    title: '오늘 밤 목소리를 볼까요?',
    lead: '이번 목소리의 특징을 빛기둥 3개로 보여 드려요',
    'path.mic': '3초 허밍',
    'path.micOpt': '선택',
    'path.micSub': '편한 높이로 “음~” 3초',
    'path.quiz': '질문 3개로',
    'path.quizSub': '탭해서 답하기만 하면 돼요',
    privacy: '녹음은 저장하지 않아요. 음높이와 세기를 그 자리에서 셀 뿐이에요',
    'f.power': '박력',
    'f.care': '섬세함',
    'f.bright': '밝기',
    'mic.arming': '마이크를 준비하고 있어요…',
    'mic.hum': '허밍해 보세요',
    'mic.humSub': '길게, 흔들어서, 편한 높이로',
    'mic.cancel': '그만',
    'mic.toQuiz': '질문 3개로 하기',
    'mic.quiet': '목소리가 마이크에 닿지 않았어요',
    'mic.quietSub': '마이크에 조금 더 가까이, 다시 한 번',
    'mic.retry': '다시 하기',
    'mic.range': '이번에 나온 음 {lo}~{hi}',
    fallback: '마이크를 쓸 수 없어서, 질문 3개로 볼게요',
    'q.high': '높은 음은 어때요?',
    'a.high.easy': '편하게 닿아요',
    'a.high.normal': '적당해요',
    'a.high.hard': '낮은 쪽이 편해요',
    'q.chorus': '후렴에서는 어떻게 불러요?',
    'a.chorus.belt': '시원하게 질러요',
    'a.chorus.soft': '부드럽게 불러요',
    'a.chorus.between': '그 중간쯤',
    'q.style': '좋아하는 창법은?',
    'a.style.ride': '리듬을 타요',
    'a.style.talk': '이야기하듯이',
    'a.style.sustain': '길게 늘여요',
    'quiz.step': '{n} / 3',
    'quiz.back': '뒤로',
    result: '이번 목소리는 {type}',
    'method.mic': '허밍에서',
    'method.quiz': '답 3개에서',
    'ev.dynamics': '강약의 변화가 큰 창법이었어요',
    'ev.steady': '음높이가 흔들림 없이 곧게 뻗었어요',
    'ev.core': '소리의 심지가 굵고 앞으로 나왔어요',
    'ev.bright': '밝고 시원하게 울렸어요',
    'ev.rhythm': '리듬이 고르고 흥이 있었어요',
    'ev.wide': '3초 동안 음높이가 크게 움직였어요',
    'ev.soft': '부드럽고 차분한 울림이었어요',
    'ev.q.highEasy': '높은 음이 편하게 닿는다는 답이었어요',
    'ev.q.highHard': '낮은 쪽이 편하다는 답이었어요',
    'ev.q.belt': '후렴은 시원하게 지른다는 답이었어요',
    'ev.q.soft': '후렴은 부드럽게 부른다는 답이었어요',
    'ev.q.between': '후렴은 그 중간쯤이라는 답이었어요',
    'ev.q.ride': '리듬을 타며 부른다는 답이었어요',
    'ev.q.talk': '이야기하듯 부른다는 답이었어요',
    'ev.q.sustain': '길게 늘여 부른다는 답이었어요',
    'ev.q.mix': '답 3개를 겹쳐서 봤어요',
    'try.clear': '높은 음이 쭉 뻗는 곡을 불러 보면 어때요?',
    'try.power': '후렴에서 시원하게 지를 수 있는 곡은 어때요?',
    'try.groove': '리듬을 가지고 놀 수 있는 곡은 어때요?',
    'try.emotional': '억양을 살릴 수 있는 프레이즈가 있는 곡은 어때요?',
    'song.label': '이 목소리로 불러 보고 싶은 1곡',
    'key.down': '키를 {n} 내리면 부르기 편할 가능성이 있어요',
    'key.up': '키를 {n} 올리면 목소리가 앞으로 나올 가능성이 있어요',
    'key.orig': '원키로 부르기 편할 가능성이 있어요',
    'key.origShort': '원키',
    other: '다른 1곡',
    again: '다시',
    note: '목소리는 곡과 날에 따라 달라져요',
    stamped: '오늘 밤',
    noSong: '지금은 예약할 수 있는 후보가 없어요',
    skip: '탭하면 넘어가요',
    hypo: '내비의 추측',
  },
})

export type VoiceKey = Parameters<typeof V.t>[0]
