// M5 room-sim strings. `room` is user-facing (5 locales, every key, same {vars});
// `presenter` is the internal demo tool (ja + en only, SPEC G-2).
import { defineStrings } from '../../i18n'

export const R = defineStrings('room', {
  ja: {
    // roommates' bubbles: positive only (E-2, E-12)
    'bubble.know0': 'それ知ってる！',
    'bubble.know1': '歌えるやつ！',
    'bubble.know2': 'これ好き！',
    'bubble.know3': 'いい曲きた！',
    'bubble.chorus0': 'サビなら！',
    'bubble.chorus1': 'サビは歌える！',
    'bubble.agree0': '乗った！',
    'bubble.agree1': '流れ変えよう！',
    'bubble.duetYes': '一緒に歌おう！',
    'bubble.reqYes': '任せて！',
    'bubble.twinYes': '実は私も！',
    'bubble.queued0': 'これ入れた！',
    'bubble.queued1': 'これ歌う！',
    'bubble.queued2': '待ってた曲！',
    'bubble.cheer0': '待ってました！',
    'bubble.cheer1': 'いけー！',
    'bubble.clap0': 'いえーい！',
    'bubble.clap1': '拍手〜！',
    'bubble.hello': 'おじゃまします！',
    // invite ticket
    'inv.req.line': '{member}から「あなたの声で聞きたい」',
    'inv.twin.waiting': 'もうひとつの星の返事を待っています',
    'inv.twin.both': '{member}とあなただけが知ってる',
    'inv.twin.notYet': '今はまだ秘密',
    'inv.twin.keep': '秘密のまま',
    'inv.twin.who': 'だれか1人',
    'inv.duet.asking': '{member}に声をかけています',
    'inv.duet.yes': '{member}がOK！',
    'inv.duet.sent': '届きました。返事を待っています',
    'act.sing': '歌う',
    'act.reveal': '明かす',
    'act.waiting': '返事待ち…',
    'act.duetReserve': '一緒に歌う',
    'act.invite': '誘う',
    'act.asking': '声かけ中…',
    'act.vote': 'この曲に1票',
    'act.gathering': '集計中…',
    // finale
    'fin.pick': '灯籠をタップして、1票',
    'fin.gathering': 'みんなの票が灯籠に集まってきます',
    'fin.decided': '決まり！金の枠で最後に入ります',
    'fin.yours': 'あなたの1票',
  },
  en: {
    'bubble.know0': 'I know this one!',
    'bubble.know1': 'I can sing this!',
    'bubble.know2': 'Love this one!',
    'bubble.know3': 'Great pick!',
    'bubble.chorus0': 'The chorus, at least!',
    'bubble.chorus1': 'I can do the chorus!',
    'bubble.agree0': 'I’m in!',
    'bubble.agree1': 'Let’s switch it up!',
    'bubble.duetYes': 'Let’s sing it together!',
    'bubble.reqYes': 'Leave it to me!',
    'bubble.twinYes': 'Me too, actually!',
    'bubble.queued0': 'Queued!',
    'bubble.queued1': 'My pick!',
    'bubble.queued2': 'Can’t wait!',
    'bubble.cheer0': 'This is it!',
    'bubble.cheer1': 'Go, go!',
    'bubble.clap0': 'Woo-hoo!',
    'bubble.clap1': 'Bravo!',
    'bubble.hello': 'Hi, everyone!',
    'inv.req.line': '{member} wants to hear it in your voice',
    'inv.twin.waiting': 'Waiting for the other star',
    'inv.twin.both': 'Only {member} and you know it',
    'inv.twin.notYet': 'Still a secret, for now',
    'inv.twin.keep': 'Keep it secret',
    'inv.twin.who': 'someone',
    'inv.duet.asking': 'Asking {member}…',
    'inv.duet.yes': '{member} is in!',
    'inv.duet.sent': 'Sent — waiting for a reply',
    'act.sing': 'Sing it',
    'act.reveal': 'Reveal',
    'act.waiting': 'Waiting…',
    'act.duetReserve': 'Sing together',
    'act.invite': 'Invite',
    'act.asking': 'Asking…',
    'act.vote': 'Vote for this',
    'act.gathering': 'Counting…',
    'fin.pick': 'Tap a lantern to vote',
    'fin.gathering': 'The room’s votes are drifting in',
    'fin.decided': 'Decided — it closes the night in gold',
    'fin.yours': 'Your vote',
  },
  zhHant: {
    'bubble.know0': '這首我會！',
    'bubble.know1': '我會唱！',
    'bubble.know2': '我喜歡這首！',
    'bubble.know3': '選得好！',
    'bubble.chorus0': '副歌我會！',
    'bubble.chorus1': '副歌可以唱！',
    'bubble.agree0': '贊成！',
    'bubble.agree1': '換個氣氛吧！',
    'bubble.duetYes': '一起唱吧！',
    'bubble.reqYes': '交給我！',
    'bubble.twinYes': '其實我也會！',
    'bubble.queued0': '我點了！',
    'bubble.queued1': '這首我來！',
    'bubble.queued2': '好想唱！',
    'bubble.cheer0': '就等這首！',
    'bubble.cheer1': '衝啊！',
    'bubble.clap0': '耶～！',
    'bubble.clap1': '鼓掌～！',
    'bubble.hello': '大家好！',
    'inv.req.line': '{member}：想聽你親口唱這首',
    'inv.twin.waiting': '正在等待另一顆星的回應',
    'inv.twin.both': '只有{member}和你會這首',
    'inv.twin.notYet': '現在還是秘密',
    'inv.twin.keep': '保持秘密',
    'inv.twin.who': '某一個人',
    'inv.duet.asking': '正在邀請{member}…',
    'inv.duet.yes': '{member}答應了！',
    'inv.duet.sent': '已送達，等待回覆',
    'act.sing': '唱這首',
    'act.reveal': '揭曉',
    'act.waiting': '等待回覆…',
    'act.duetReserve': '一起唱',
    'act.invite': '邀請',
    'act.asking': '邀請中…',
    'act.vote': '投這首一票',
    'act.gathering': '統計中…',
    'fin.pick': '點一盞燈籠投一票',
    'fin.gathering': '大家的票正匯集到燈籠',
    'fin.decided': '決定了！以金色壓軸',
    'fin.yours': '你的一票',
  },
  zhHans: {
    'bubble.know0': '这首我会！',
    'bubble.know1': '我会唱！',
    'bubble.know2': '我喜欢这首！',
    'bubble.know3': '选得好！',
    'bubble.chorus0': '副歌我会！',
    'bubble.chorus1': '副歌可以唱！',
    'bubble.agree0': '赞成！',
    'bubble.agree1': '换个气氛吧！',
    'bubble.duetYes': '一起唱吧！',
    'bubble.reqYes': '交给我！',
    'bubble.twinYes': '其实我也会！',
    'bubble.queued0': '我点了！',
    'bubble.queued1': '这首我来！',
    'bubble.queued2': '好想唱！',
    'bubble.cheer0': '就等这首！',
    'bubble.cheer1': '冲啊！',
    'bubble.clap0': '耶～！',
    'bubble.clap1': '鼓掌～！',
    'bubble.hello': '大家好！',
    'inv.req.line': '{member}：想听你亲口唱这首',
    'inv.twin.waiting': '正在等待另一颗星的回应',
    'inv.twin.both': '只有{member}和你会这首',
    'inv.twin.notYet': '现在还是秘密',
    'inv.twin.keep': '保持秘密',
    'inv.twin.who': '某一个人',
    'inv.duet.asking': '正在邀请{member}…',
    'inv.duet.yes': '{member}答应了！',
    'inv.duet.sent': '已送达，等待回复',
    'act.sing': '唱这首',
    'act.reveal': '揭晓',
    'act.waiting': '等待回复…',
    'act.duetReserve': '一起唱',
    'act.invite': '邀请',
    'act.asking': '邀请中…',
    'act.vote': '投这首一票',
    'act.gathering': '统计中…',
    'fin.pick': '点一盏灯笼投一票',
    'fin.gathering': '大家的票正汇集到灯笼',
    'fin.decided': '决定了！以金色压轴',
    'fin.yours': '你的一票',
  },
  ko: {
    'bubble.know0': '이거 알아!',
    'bubble.know1': '부를 수 있어!',
    'bubble.know2': '이 노래 좋아!',
    'bubble.know3': '선곡 좋다!',
    'bubble.chorus0': '후렴은 알아!',
    'bubble.chorus1': '후렴은 부를 수 있어!',
    'bubble.agree0': '찬성!',
    'bubble.agree1': '분위기 바꾸자!',
    'bubble.duetYes': '같이 부르자!',
    'bubble.reqYes': '맡겨 줘!',
    'bubble.twinYes': '사실 나도!',
    'bubble.queued0': '넣었어!',
    'bubble.queued1': '이건 내 곡!',
    'bubble.queued2': '부르고 싶었어!',
    'bubble.cheer0': '기다렸어!',
    'bubble.cheer1': '가자~!',
    'bubble.clap0': '예이~!',
    'bubble.clap1': '박수~!',
    'bubble.hello': '다들 안녕!',
    'inv.req.line': '{member} 님이 내 목소리로 듣고 싶대요',
    'inv.twin.waiting': '다른 별의 답을 기다리는 중',
    'inv.twin.both': '{member} 님과 나만 아는 곡',
    'inv.twin.notYet': '아직은 비밀',
    'inv.twin.keep': '비밀로 두기',
    'inv.twin.who': '누군가 한 명',
    'inv.duet.asking': '{member} 님에게 묻는 중…',
    'inv.duet.yes': '{member} 님이 OK!',
    'inv.duet.sent': '전달했어요. 답을 기다리는 중',
    'act.sing': '부르기',
    'act.reveal': '밝히기',
    'act.waiting': '기다리는 중…',
    'act.duetReserve': '같이 부르기',
    'act.invite': '초대하기',
    'act.asking': '묻는 중…',
    'act.vote': '이 곡에 한 표',
    'act.gathering': '집계 중…',
    'fin.pick': '등불을 눌러 한 표',
    'fin.gathering': '모두의 표가 등불로 모이고 있어요',
    'fin.decided': '결정! 금빛 마무리 곡으로 들어가요',
    'fin.yours': '내 한 표',
  },
})

export type RoomKey = Parameters<typeof R.t>[0]

/** Presenter tooling: ja + en (other locales fall back to en). */
export const P = defineStrings('presenter', {
  ja: {
    title: '発表者パネル',
    close: '閉じる',
    collapse: 'たたむ',
    expand: 'ひらく',
    script: '台本',
    scriptOn: '台本モード ON',
    scriptOff: '台本モード OFF',
    next: '次のイベント',
    upcoming: '次',
    scriptDone: '台本は最後まで進みました',
    speed: '速度',
    room: '部屋の出来事',
    view: '表示',
    tools: 'デモの道具',
    'step.enter': '入室（フル版の演出）',
    'step.minato-reserve': 'ミナトが1曲予約',
    'step.saki-mellow': 'サキが「Lemon」「ドライフラワー」',
    'step.jun-join': 'ジュンが合流',
    'step.advance-2': '2曲進める（空気の変わり目）',
    'step.my-turn': 'あなたの番',
    'step.my-song-end': '歌い終わる → 声の札',
    'step.coaster': '乾杯コースター',
    'step.exit': '退室 → 今夜のまとめ',
    'step.exit.restore': '退室 → まとめ（{lang}に戻す）',
    auto: '（部屋が自動で）',
    more: 'メニュー',
    open: 'パネルをひらく',
    grip: 'ドラッグで移動・長押しでメニュー',
    forced: '比較・レンズの表示中はたたんでいます',
    'cmd.join': 'ジュン合流',
    'cmd.leave': 'ジュン退出',
    'cmd.advance': '曲を進める',
    'cmd.myturn': 'あなたの番',
    'cmd.finish': '歌い終わる',
    'cmd.hundred': '100点で終える',
    'cmd.request': 'リクエスト便',
    'cmd.twin': '二重星',
    'cmd.coaster': '乾杯',
    'cmd.min15': '残り15分',
    'cmd.exit': '退室',
    'cmd.nextvisit': '次の来店',
    'cmd.seed': '過去の夜を読み込む（デモ用）',
    'cmd.lang': '言語を5秒で一巡',
    'cmd.lens': '企画レンズ',
    'cmd.split': '比較スプリット',
    'cmd.noduck': '音を下げない（デモ）',
    'cmd.entry': '入口画面',
    'cmd.reset': 'リセット',
    'view.auto': '自動',
    'view.phone': 'スマホ',
    'view.room': '部屋',
    'view.dual': '2画面',
    hud: '計測HUD',
    'hud.ttfr': '初予約まで',
    'hud.target': '目標 {s}秒',
    'hud.timing': '計測中',
    'hud.kinds': '札 表示/行動',
    'hud.co': '共起枠',
    'hud.tag': 'タグ枠',
    'hud.allKnow': '全員知ってる率',
    'hud.mo': 'MO 注文/重複防止/退室後',
    'hud.voice': '声→予約',
    'hud.import': '候補→保存',
    'hud.survey': '5設問',
    'hud.search': '検索 回数/空振り',
    'hud.reset': '計測をリセット',
    'hud.note': '滞在時間は指標にしない',
    'meta.left': '残り{m}分',
    'meta.members': '在室 {n}人',
    'live.idle': '待機中',
    'live.queue': '待ち{n}曲',
    'live.heat': '熱（仮説値）',
  },
  en: {
    title: 'Presenter',
    close: 'Close',
    collapse: 'Collapse',
    expand: 'Expand',
    script: 'Script',
    scriptOn: 'Script mode ON',
    scriptOff: 'Script mode OFF',
    next: 'Next event',
    upcoming: 'Next',
    scriptDone: 'Script complete',
    speed: 'Speed',
    room: 'Room events',
    view: 'View',
    tools: 'Demo tools',
    'step.enter': 'Enter (full entrance)',
    'step.minato-reserve': 'Minato reserves a song',
    'step.saki-mellow': 'Saki queues Lemon + Dry Flower',
    'step.jun-join': 'Jun joins',
    'step.advance-2': 'Play two songs (mood shift)',
    'step.my-turn': 'Your turn',
    'step.my-song-end': 'Finish → voice card',
    'step.coaster': 'Toast coaster',
    'step.exit': "Exit → tonight's wrap",
    'step.exit.restore': 'Exit → wrap (back to {lang})',
    auto: '(the room does it)',
    more: 'Menu',
    open: 'Open the panel',
    grip: 'Drag to move · hold for the menu',
    forced: 'Folded while the split / lens is on',
    'cmd.join': 'Jun joins',
    'cmd.leave': 'Jun leaves',
    'cmd.advance': 'Advance song',
    'cmd.myturn': 'My turn',
    'cmd.finish': 'Finish mine',
    'cmd.hundred': 'Finish with 100',
    'cmd.request': 'Request',
    'cmd.twin': 'Twin star',
    'cmd.coaster': 'Toast',
    'cmd.min15': '15 min left',
    'cmd.exit': 'Exit',
    'cmd.nextvisit': 'Next visit',
    'cmd.seed': 'Load past nights (demo)',
    'cmd.lang': 'Cycle languages (5 s)',
    'cmd.lens': 'Planning lens',
    'cmd.split': 'Compare split',
    'cmd.noduck': "Don't duck (demo)",
    'cmd.entry': 'Entry screen',
    'cmd.reset': 'Reset',
    'view.auto': 'Auto',
    'view.phone': 'Phone',
    'view.room': 'Room',
    'view.dual': 'Dual',
    hud: 'Metrics HUD',
    'hud.ttfr': 'Time to first reserve',
    'hud.target': 'target {s}s',
    'hud.timing': 'timing',
    'hud.kinds': 'Cards shown/acted',
    'hud.co': 'Co-occurrence',
    'hud.tag': 'Tag picks',
    'hud.allKnow': 'Everyone-knows rate',
    'hud.mo': 'MO placed/dup/after exit',
    'hud.voice': 'Voice→reserve',
    'hud.import': 'Import→saved',
    'hud.survey': 'Survey',
    'hud.search': 'Search queries/misses',
    'hud.reset': 'Reset metrics',
    'hud.note': 'Dwell time is not a metric',
    'meta.left': '{m} min left',
    'meta.members': '{n} in room',
    'live.idle': 'Idle stage',
    'live.queue': '{n} waiting',
    'live.heat': 'Heat (hypothesis)',
  },
})

export type PresenterKey = Parameters<typeof P.t>[0]
