// Planner-layer strings (企画レンズ・比較スプリット). Internal tools: ja + en only; other locales
// fall back to English (SPEC G-2). Never name a competitor here.
import { defineStrings } from '../../i18n'

export const planner = defineStrings('planner', {
  ja: {
    // lens chrome
    'lens.title': '企画レンズ',
    'lens.sub': '施策 × 勝ち筋 × 検証指標',
    'lens.hint': 'ラベルをタップで詳細',
    'lens.count': '{n}要素',
    'lens.close': '閉じる',
    'lens.legendPolicies': '点灯中の施策',
    'lens.legendWays': '勝ち筋',
    'lens.initiatives': '具体的な取り組み（重要施策より）',
    'lens.here': 'この画面での実装',
    'lens.ways': '勝ち筋',
    'lens.metric': '検証指標',
    'lens.now': '現在の計測値',
    'lens.live': 'LIVE',
    'lens.evidence': '根拠と仮説',
    'lens.future': '将来構想',
    'lens.why': 'なぜこの札？',
    'lens.rule': 'ルール',
    'lens.trigger': 'きっかけ',
    'lens.reason': '理由',
    'lens.metricPrefix': '指標：',
    'lens.join': '・',
    'lens.tonight': '今夜この部屋で動いた施策',
    'lens.onScreen': 'この画面',
    // policies
    'policy.5-1': 'インバウンド',
    'policy.5-2': '探し方',
    'policy.5-3': '連携',
    'policy.5-4': 'アプリ整理',
    'policySum.5-1': '多言語化と各国向けの中身の最適化、OTA連携まで。インバウンドの使いやすさでBOXへの集客につなげる',
    'policySum.5-2': '「探させない利便性」と「探す楽しさ」の両立。楽曲タグDBを基盤に目的の曲との出会いやすさを高める',
    'policySum.5-3': 'サブスク連携の利便性と、うたスキによる顧客接点を両立し、利用価値の向上につなげる',
    'policySum.5-4': '採点・選曲などのアプリを再整理・統合し、WEB化を含めて接点をシンプルに。BOX内のMOも見据える',
    'init.5-1.a': '多言語化を拡充',
    'init.5-1.b': '各国向けコンテンツの最適化（対象国選定、出し分け運用）',
    'init.5-1.c': 'OTA連携による予約・送客導線を構築',
    'init.5-2.a': '楽曲タグDBを構築',
    'init.5-2.b': 'PoCアプリでタグ粒度・設問を検証',
    'init.5-2.c': 'レコメンド項目の磨き込み（「この曲を選んだ人はこれも」の項目精査）',
    'init.5-3.a': 'サブスク連携の内容と実現性を検証',
    'init.5-3.b': 'うたスキの機能拡張を検討',
    'init.5-3.c': 'サブスク側のお気に入りを取り込み、うたスキ利用とサブスク連携を両立',
    'init.5-4.a': '現行アプリの役割・利用実態を棚卸し',
    'init.5-4.b': '統合／WEB化に向けた技術課題を整理',
    'init.5-4.c': 'MO機能の実装に向けた技術課題を整理',
    // ways to win
    'way.dare': '誰',
    'way.tsunagu': '繋',
    'way.yomu': '読',
    'way.hou': '訪',
    'way.ren': '連',
    'way.voice': '声',
    'wayDesc.dare': '誰と一緒か（同席者・関係性）を読む',
    'wayDesc.tsunagu': '選曲時の関連表示（共起）',
    'wayDesc.yomu': '場の空気と世の中を読む',
    'wayDesc.hou': 'インバウンド（多言語から中身まで）',
    'wayDesc.ren': 'サブスク連携・次回へつなぐ',
    'wayDesc.voice': '歌声の持ち味',
    // element names
    'el.lane': 'ステージレーン（予約列）',
    'el.search': '検索バーとシート',
    'el.hero-ball': 'ミラーボール',
    'el.orbs': '床の光（同室者）',
    'el.mood': '気分語・オーロラ',
    'el.mixer': '空気ミキサー',
    'el.card:song': '曲の札・口火',
    'el.card:song.visa': '越境の札',
    'el.card:ask': '知ってる？',
    'el.card:shift': '空気の変わり目',
    'el.card:link': 'つながる',
    'el.card:voice': '今夜の声',
    'el.card:gap': '未踏の面',
    'el.card:invite': '招待チケット',
    'el.card:import': '持ち込み',
    'el.card:coaster': '乾杯コースター',
    'el.card:finale': '締めの1曲',
    'el.card:breather': 'ひと息',
    'el.navi-tag': 'ナビのおすすめ札',
    'el.dock': 'ドックの4入口',
    'el.order': '注文画面',
    'el.record': '記録',
    'el.wrap': '今夜のまとめ',
    'el.entry-ota': '入口・旅のしおり',
    'el.lang': '言語',
    'el.room-view': '部屋の画面',
    // what each element does
    'here.lane': '選曲中も予約列を上端に固定。演奏順 #n と「あなたの番まであと◯曲」を常に見せる',
    'here.search': '原題・ローマ字・現地文字のどれでも1文字目から候補。根拠タグで絞り込み',
    'here.hero-ball': 'レパートリーを1つのボールに。触った曲が面として残り、次回の最初の手札になる',
    'here.orbs': '同室者を床の光で。合流・退出で手札をまるごと読み直す',
    'here.mood': '場の熱を数値ではなくオーロラの色と気分語で見せる',
    'here.mixer': '3つの設問（誰と／知ってる⇄新しい出会い／しっとり⇄アガる）をパッド1枚に',
    'here.card:song': '口火の1曲は入室と同時に部屋へ「知ってる？」を送り、ナビのおすすめ札つきで予約できる',
    'here.card:song.visa': '閲覧言語と同室者の言語に合わせて最初の3枚を出し分ける（運用の見本）',
    'here.card:ask': '部屋の認知を匿名のドットで集計。「知らない」と「未回答」は区別しない',
    'here.card:shift': '同室者の曲の流れ（しっとり2曲・アゲ3曲・ミキサー操作）から次の一手を提案',
    'here.card:link': '「一緒に選ばれている」をタグ推薦とは別枠で出し、ボール上の光の線として残す',
    'here.card:voice': '採点と分析採点を1枚に統合。今回の声と、キー付きで歌いたくなる1曲',
    'here.card:gap': 'ボールの暗いエリア（テンポ×ジャンル）から、絞り込んだ検索へ案内',
    'here.card:invite': 'リクエスト便・二重星・声の相性。断っても送り主には何も届かない',
    'here.card:import': 'サブスクのお気に入りを「候補」として出し、版を選んで明示的に保存',
    'here.card:coaster': '流れを読んで乾杯を提案。重複注文を防ぎ、退室後は締める',
    'here.card:finale': '今夜の共通曲と熱から3候補。部屋の投票で締めの1曲を固定',
    'here.card:breather': '7枚ごとにひと息。いちばん大きいボタンは「スマホを置いて聴く」',
    'here.navi-tag': 'ナビが薦めた曲だと分かる札。外してもナビのせいにできる（エクスキューズ）',
    'here.dock': '6つのチャネル（キョクナビ・うたスキWeb・採点・分析採点・ブラウザ案・MO）を4つの入口に集約',
    'here.order': '注文→店舗受付→重複防止→退室後はブロック',
    'here.record': 'ボール・ピン・カレンダーのスタンプ・マイうた。触った分だけ残る',
    'here.wrap': '今夜のメロディと光座で締め、最後に評価5設問（任意）',
    'here.entry-ota': '多言語の店舗案内→OTA予約→バウチャー→受付→ルーム案内',
    'here.lang': '5言語を再読み込みなしで即時に切り替え。曲名は原題を常に併記',
    'here.room-view': '共有の室内画面。個人の履歴・持ち込み・声は出さない',
    // metrics (H-3)
    'metric.lane': '予約列を見ながら選べたか（設問①の補足）',
    'metric.search': '目的の曲に到達できたか・所要時間・詰まり（4タスク×4言語＝16ケース）',
    'metric.hero-ball': '次回来店での再利用数、継続意思（設問④）',
    'metric.orbs': '同席者の把握',
    'metric.mood': '熱は仮説値として表示',
    'metric.mixer': '設問ごとの離脱、操作から予約までの時間',
    'metric.card:song': '初予約までの秒数（目標180秒以内）',
    'metric.card:song.visa': '言語ごとの最初の3枚の予約率',
    'metric.card:ask': '全員知ってる率、会話のきっかけ（定性）',
    'metric.card:shift': '差し込み後の熱の変化（仮説の検証）',
    'metric.card:link': '共起枠の選択率（タグ枠と別に計測）',
    'metric.card:voice': '声から予約への転換率',
    'metric.card:gap': '意外な発見（設問②）、タグの粒度',
    'metric.card:invite': '受諾率',
    'metric.card:import': '候補から保存への転換率',
    'metric.card:coaster': '注文完了、重複防止の発動、退室後のブロック',
    'metric.card:finale': 'ラストの満足（定性）',
    'metric.card:breather': 'ひと息で「置いて聴く」を選んだ回数',
    'metric.navi-tag': '札つき予約の比率（エクスキューズの効果）',
    'metric.dock': '入口から各機能までのタップ数（6チャネル→4入口）',
    'metric.order': 'MOの3指標（完了・重複防止・退室後ブロック）',
    'metric.record': '継続意思（設問④）',
    'metric.wrap': '評価5設問',
    'metric.entry-ota': '案内→予約→バウチャー→受付→ルーム案内の完了率',
    'metric.lang': '16ケースのマトリクス',
    'metric.room-view': '共有画面のプライバシー境界',
    // short metric names for the tags
    'short.lane': '予約列を見て選べたか',
    'short.search': '到達・時間・詰まり',
    'short.hero-ball': '次回の再利用数',
    'short.orbs': '同席者の把握',
    'short.mood': '熱＝仮説値',
    'short.mixer': '操作→予約の時間',
    'short.card:song': '初予約までの秒数',
    'short.card:song.visa': '最初の3枚の予約率',
    'short.card:ask': '全員知ってる率',
    'short.card:shift': '差し込み後の熱',
    'short.card:link': '共起枠の選択率',
    'short.card:voice': '声→予約',
    'short.card:gap': '意外な発見',
    'short.card:invite': '受諾率',
    'short.card:import': '候補→保存',
    'short.card:coaster': 'MOの状態遷移',
    'short.card:finale': 'ラストの満足',
    'short.card:breather': '置いて聴く',
    'short.navi-tag': '札つき予約の比率',
    'short.dock': 'タップ数 6→4',
    'short.order': 'MOの3指標',
    'short.record': '継続意思',
    'short.wrap': '評価5設問',
    'short.entry-ota': '導線の完了率',
    'short.lang': '16ケース',
    'short.room-view': 'プライバシー境界',
    // measured values
    'val.firstReserve': '{s}秒',
    'val.measuring': '計測中 {s}秒',
    'val.target180': '目標 180秒以内',
    'val.shownActed': '表示 {shown}回・行動 {acted}回',
    'val.lane': '予約 {n}曲（あなた {mine}曲）',
    'val.turn': 'あなたの番まで あと{k}曲',
    'val.search': '検索 {q}回・ヒットなし {miss}回・予約まで平均 {avg}秒',
    'val.heroBall': '点灯 {lit}面・マイうた {saved}曲',
    'val.orbs': '在室 {n}人（QR参加・シミュレーション）',
    'val.heat': '熱 {heat}（仮説値）',
    'val.mixer': 'アガる {hype}・新しい出会い {fresh}（仮説の重み {w}）',
    'val.visa': '越境の札から予約 {n}曲',
    'val.ask': '聞いた {asked}曲・全員知ってた {all}曲',
    'val.shift': '差し込み {n}回・直後の熱の変化 {delta}（仮説値）',
    'val.link': '共起枠 {cp}/{cs}・タグ枠 {tp}/{ts}',
    'val.voice': '声の札から予約 {n}回',
    'val.invite': '届いた {n}件・受けた {acc}件',
    'val.import': '保存 {saved}曲（候補 {cand}曲）',
    'val.mo': '注文 {placed}・重複防止 {dup}・退室後ブロック {after}',
    'val.finale': '投票 {votes}/{n}',
    'val.breather': '置いて聴いた {n}回',
    'val.navi': 'ナビ札つき予約 {navi}／あなたの予約 {mine}',
    'val.dock': '6チャネル → 4入口',
    'val.record': '夜 {nights}・ピン {pins}・マイうた {saved}',
    'val.wrapDone': '5設問：回答済み',
    'val.wrapOpen': '5設問：未回答（任意）',
    'val.ota': '模擬の導線（計測はデモ）',
    'val.lang': '表示中：{locale}',
    'val.private': '部屋の画面に出ている個人の要素 {n}件',
    'val.none': '—',
    // evidence vs hypothesis
    'evi.default': '根拠タグ（ジャンル・年代・テンポ・言語・版）は実線、空気感の仮説タグは点線「ナビの見立て」',
    'evi.mood': '熱 {heat}（仮説値）。曲のエネルギーと知ってる率から推定し、利用者には数値を出さない',
    'evi.mixer': 'ミキサーの重みは仮説（操作後20分は0.5、以後0.2）',
    'evi.card:ask': '根拠：答えた人の回答だけを数える（答えない人もいる前提のシミュレーション）',
    'evi.card:shift': '差し込み後の熱の変化で仮説を検証する（熱は仮説値）',
    'evi.card:link': '共起は「一緒に選ばれている」実績（デモは手作業＋計算）。タグ推薦とは別枠',
    'evi.card:voice': '迫力・丁寧さ・明るさの3因子研究に基づく仮の表現。上手下手・性格は判定しない',
    'evi.hero-ball': '面は実際の出来事（予約・歌唱・全員知ってた）でだけ上がり、下がらない',
    'evi.orbs': '同室者の反応はシミュレーション（在室・知ってる・予約）',
    'evi.card:song.visa': '言語ごとの最初の3枚は運用の見本（仮説）。現地表記は確証のある曲だけ',
    'evi.trend': '「今週よく歌われている」は仮データ',
    // future notes
    'fut.orbs': '顔認証は構想・未実装。試作は QR 参加で代替',
    'fut.card:import': '実際のサブスク連携は未接続（デモデータ）',
    'fut.order': '実際のMOには未接続（模擬）',
    'fut.card:coaster': '実際のMOには未接続（模擬）',
    'fut.entry-ota': 'OTA予約・決済は模擬。実際の予約にはつながらない',
    'fut.record': 'うたスキ連携（ベース版）は擬似ログイン',
    'fut.wrap': 'うたスキ連携（ベース版）は擬似ログイン',
    'fut.card:voice': '録音は保存しない。マイクが使えなければ3つの質問で',
    'fut.mood': '世の中の文脈（トレンド）は仮データ',
    'fut.lang': '4言語×4タスクの16ケースで比較予定',
    'fut.room-view': '室内タブレットとの実接続は未実装（同じ画面内のシミュレーション）',
    'fut.card:invite': '相手のスマホへの送信はシミュレーション',
    'fut.hero-ball': '次回来店の続きはこの端末内（擬似ログインで持ち帰り）',
    // triggers (なぜこの札？)
    'trig.enter': '入室',
    'trig.refill': '補充',
    'trig.reserved': '予約した',
    'trig.memberSongEnded': '同室者の曲が終わった',
    'trig.myTurnEnded': 'あなたの曲が終わった',
    'trig.memberJoined': '合流',
    'trig.memberLeft': '退出',
    'trig.minutes15': '残り15分',
    'trig.moodMixed': '空気ミキサー',
    'trig.passStreak': '3回続けてパス',
    'trig.navMiss': 'ナビの読み違い',
    'trig.request': 'リクエストが届いた',
    'trig.twin': '二重星の条件',
    'trig.coaster': '乾杯の合図',
    'trig.nextVisit': '次の来店',
    // split view
    'split.title': '比較スプリット',
    'split.static': '申告式（従来型）',
    'split.dynamic': '新ナビ',
    'split.situation': 'シチュエーション：{c}',
    'split.fixed': '同行者の種類だけで決まる固定リスト',
    'split.live': '部屋の今を読んだ手札（理由と原因つき）',
    'split.nochange': '変化なし',
    'split.updated': '更新：{cause}',
    'split.waiting': '部屋の出来事で、右だけが読み直される',
    'split.rereadsLabel': '読み直した回数',
    'split.note': '企画用の比較表示（利用者の画面には出ません）',
    'comp.friends': '友人',
    'comp.family': '家族',
    'comp.work': '職場',
    'comp.date': 'デート',
    'comp.solo': 'ひとり',
    'kind.song': '曲',
    'kind.ask': '知ってる？',
    'kind.shift': '空気の変わり目',
    'kind.link': 'つながる',
    'kind.voice': '今夜の声',
    'kind.gap': '未踏の面',
    'kind.invite': '招待',
    'kind.import': '持ち込み',
    'kind.coaster': '乾杯',
    'kind.finale': '締めの1曲',
    'kind.breather': 'ひと息',
  },
  en: {
    'lens.title': 'Planning lens',
    'lens.sub': 'Measures × ways to win × metrics',
    'lens.hint': 'Tap a label for details',
    'lens.count': '{n} elements',
    'lens.close': 'Close',
    'lens.legendPolicies': 'Measures on screen',
    'lens.legendWays': 'Ways to win',
    'lens.initiatives': 'Initiatives (from the key-measures sheet)',
    'lens.here': 'What this element does',
    'lens.ways': 'Ways to win',
    'lens.metric': 'Metric',
    'lens.now': 'Measured now',
    'lens.live': 'LIVE',
    'lens.evidence': 'Evidence vs hypothesis',
    'lens.future': 'Future',
    'lens.why': 'Why this card?',
    'lens.rule': 'Rule',
    'lens.trigger': 'Trigger',
    'lens.reason': 'Reason',
    'lens.metricPrefix': 'Metric: ',
    'lens.join': ' · ',
    'lens.tonight': 'Measures that ran in this room tonight',
    'lens.onScreen': 'On screen',
    'policy.5-1': 'Inbound',
    'policy.5-2': 'Discovery',
    'policy.5-3': 'Integration',
    'policy.5-4': 'App consolidation',
    'policySum.5-1': 'Multilingual UI, content tuned per country and OTA links: the easiest venue for visitors, bringing guests to the box',
    'policySum.5-2': 'No-search convenience and the fun of searching, on a song tag database that makes the right song easier to meet',
    'policySum.5-3': 'Subscription convenience plus a customer touchpoint through the member service, raising the value of every visit',
    'policySum.5-4': 'Reorganise and merge the scoring and song-picking apps, simplify touchpoints (incl. web) and prepare in-room mobile ordering',
    'init.5-1.a': 'Expand multilingual support',
    'init.5-1.b': 'Tune content per country (target countries, per-locale serving)',
    'init.5-1.c': 'Build booking and referral flows with OTAs',
    'init.5-2.a': 'Build the song tag database',
    'init.5-2.b': 'Validate tag granularity and questions in a PoC app',
    'init.5-2.c': 'Refine recommendation items (“people who chose this also chose”)',
    'init.5-3.a': 'Validate what a subscription link can do and how feasible it is',
    'init.5-3.b': 'Consider extending the member service',
    'init.5-3.c': 'Import subscription favourites, keeping both the member service and the link',
    'init.5-4.a': 'Inventory the role and use of today’s apps',
    'init.5-4.b': 'List the technical issues for merging / going web',
    'init.5-4.c': 'List the technical issues for mobile ordering',
    'way.dare': 'Who',
    'way.tsunagu': 'Link',
    'way.yomu': 'Read',
    'way.hou': 'Visit',
    'way.ren': 'Connect',
    'way.voice': 'Voice',
    'wayDesc.dare': 'Read who you are with',
    'wayDesc.tsunagu': 'Related picks while choosing (co-occurrence)',
    'wayDesc.yomu': 'Read the room and the world',
    'wayDesc.hou': 'Inbound, from language to content',
    'wayDesc.ren': 'Subscriptions and the next visit',
    'wayDesc.voice': 'Your voice tonight',
    'el.lane': 'Stage lane (queue)',
    'el.search': 'Search bar and sheet',
    'el.hero-ball': 'Mirror ball',
    'el.orbs': 'Floor lights (roommates)',
    'el.mood': 'Mood word and aurora',
    'el.mixer': 'Air mixer',
    'el.card:song': 'Song card / opener',
    'el.card:song.visa': 'Crossing (visa) card',
    'el.card:ask': 'Do you know it?',
    'el.card:shift': 'Turning point',
    'el.card:link': 'Picked together',
    'el.card:voice': 'Your voice tonight',
    'el.card:gap': 'Unlit area',
    'el.card:invite': 'Invite ticket',
    'el.card:import': 'Bring your songs',
    'el.card:coaster': 'Toast coaster',
    'el.card:finale': 'Closing song',
    'el.card:breather': 'Breather',
    'el.navi-tag': 'Navi-pick tag',
    'el.dock': 'Dock (4 entrances)',
    'el.order': 'Order screen',
    'el.record': 'Collection',
    'el.wrap': 'Tonight’s wrap',
    'el.entry-ota': 'Entry and travel journal',
    'el.lang': 'Language',
    'el.room-view': 'Room screen',
    'here.lane': 'The queue stays pinned while choosing: play order #n and “n songs until your turn”',
    'here.search': 'Original title, romaji or local script, from the first letter; filter by evidence tags',
    'here.hero-ball': 'Your repertoire as one ball: every song you touch stays as a face and returns next visit',
    'here.orbs': 'Roommates as floor lights; a join or leave re-reads the whole hand',
    'here.mood': 'The room’s heat as aurora colour and a word, not a number',
    'here.mixer': 'Three questions (who / known vs new / mellow vs hype) on one pad',
    'here.card:song': 'The opener asks the room “do you know it?” on entry and can be queued with the navi-pick tag',
    'here.card:song.visa': 'The first three cards follow the viewing and roommates’ languages (serving sample)',
    'here.card:ask': 'Anonymous dots count who knows it; “don’t know” and “no answer” look the same',
    'here.card:shift': 'Suggests the next move from the flow (two mellow, three peaks, mixer)',
    'here.card:link': '“Picked together” shown apart from tag picks, kept as a light line on the ball',
    'here.card:voice': 'Scoring and voice analysis in one card: tonight’s voice and a song with a key',
    'here.card:gap': 'Leads from a dark area of the ball (tempo × genre) into a filtered search',
    'here.card:invite': 'Requests, hidden twins and voice pairs; declining never notifies anyone',
    'here.card:import': 'Subscription favourites shown as candidates, saved only when you choose a version',
    'here.card:coaster': 'Suggests a toast from the flow; no duplicate orders; closes at exit',
    'here.card:finale': 'Three candidates from tonight’s shared songs and heat; the room votes',
    'here.card:breather': 'A pause every 7 cards; the biggest button is “Put the phone down and listen”',
    'here.navi-tag': 'Marks a song picked by the navi, so a miss can be the navi’s fault (the excuse)',
    'here.dock': 'Six channels folded into four entrances (find / sing / collection / order)',
    'here.order': 'Order → accepted at the counter → duplicate guard → blocked after exit',
    'here.record': 'Ball, pins, calendar stamps and saved songs: what you touched stays',
    'here.wrap': 'Ends with tonight’s melody and constellation, then five optional questions',
    'here.entry-ota': 'Multilingual venue info → OTA booking → voucher → front desk → room guide',
    'here.lang': 'Five languages switch in place without reload; the original title always shows',
    'here.room-view': 'The shared in-room screen: no personal history, imports or voice',
    'metric.lane': 'Could people choose while watching the queue (Q1 follow-up)',
    'metric.search': 'Reached the song? Time and stumbles (4 tasks × 4 languages = 16 cases)',
    'metric.hero-ball': 'Reuse on the next visit, intent to return (Q4)',
    'metric.orbs': 'Awareness of who is in the room',
    'metric.mood': 'Heat shown as a hypothesis value',
    'metric.mixer': 'Drop-off per question, time from mixing to queueing',
    'metric.card:song': 'Seconds to the first reservation (target ≤ 180 s)',
    'metric.card:song.visa': 'Reservation rate of the first three cards per language',
    'metric.card:ask': 'Share of songs everyone knew; conversation starters (qualitative)',
    'metric.card:shift': 'Heat change after an insert (testing the hypothesis)',
    'metric.card:link': 'Pick rate of co-occurrence, measured apart from tag picks',
    'metric.card:voice': 'Voice → reservation conversion',
    'metric.card:gap': 'Unexpected finds (Q2), tag granularity',
    'metric.card:invite': 'Acceptance rate',
    'metric.card:import': 'Candidate → saved conversion',
    'metric.card:coaster': 'Orders completed, duplicate guard, blocked after exit',
    'metric.card:finale': 'Satisfaction with the ending (qualitative)',
    'metric.card:breather': 'How often “put the phone down” was chosen',
    'metric.navi-tag': 'Share of reservations with the navi tag (the excuse effect)',
    'metric.dock': 'Taps from entrance to feature (6 channels → 4 entrances)',
    'metric.order': 'Three mobile-ordering metrics',
    'metric.record': 'Intent to return (Q4)',
    'metric.wrap': 'Five evaluation questions',
    'metric.entry-ota': 'Completion of info → booking → voucher → desk → room',
    'metric.lang': 'The 16-case matrix',
    'metric.room-view': 'Privacy boundary of the shared screen',
    'short.lane': 'Choose while watching the queue',
    'short.search': 'Reach · time · stumbles',
    'short.hero-ball': 'Reuse next visit',
    'short.orbs': 'Who is here',
    'short.mood': 'Heat = hypothesis',
    'short.mixer': 'Mix → reserve time',
    'short.card:song': 'Seconds to first reserve',
    'short.card:song.visa': 'First-3 reserve rate',
    'short.card:ask': 'Everyone-knows rate',
    'short.card:shift': 'Heat after insert',
    'short.card:link': 'Co-pick rate',
    'short.card:voice': 'Voice → reserve',
    'short.card:gap': 'Unexpected finds',
    'short.card:invite': 'Acceptance',
    'short.card:import': 'Candidate → saved',
    'short.card:coaster': 'Order states',
    'short.card:finale': 'Ending satisfaction',
    'short.card:breather': 'Put down & listen',
    'short.navi-tag': 'Navi-tag share',
    'short.dock': 'Taps 6→4',
    'short.order': '3 ordering metrics',
    'short.record': 'Intent to return',
    'short.wrap': '5 questions',
    'short.entry-ota': 'Flow completion',
    'short.lang': '16 cases',
    'short.room-view': 'Privacy boundary',
    'val.firstReserve': '{s} s',
    'val.measuring': 'measuring {s} s',
    'val.target180': 'target ≤ 180 s',
    'val.shownActed': 'shown {shown} · acted {acted}',
    'val.lane': '{n} queued (yours {mine})',
    'val.turn': '{k} songs until your turn',
    'val.search': '{q} searches · {miss} misses · {avg} s to reserve',
    'val.heroBall': '{lit} faces lit · {saved} saved',
    'val.orbs': '{n} in the room (QR join · simulated)',
    'val.heat': 'heat {heat} (hypothesis)',
    'val.mixer': 'hype {hype} · new {fresh} (weight {w}, hypothesis)',
    'val.visa': '{n} reserved from crossing cards',
    'val.ask': '{asked} asked · {all} known by everyone',
    'val.shift': '{n} inserts · heat change {delta} (hypothesis)',
    'val.link': 'co-pick {cp}/{cs} · tag {tp}/{ts}',
    'val.voice': '{n} reserved from the voice card',
    'val.invite': '{n} received · {acc} accepted',
    'val.import': '{saved} saved ({cand} candidates)',
    'val.mo': '{placed} orders · {dup} duplicates blocked · {after} after exit',
    'val.finale': '{votes}/{n} votes',
    'val.breather': 'put down {n}×',
    'val.navi': '{navi} navi-tagged of your {mine}',
    'val.dock': '6 channels → 4 entrances',
    'val.record': '{nights} nights · {pins} pins · {saved} saved',
    'val.wrapDone': '5 questions: answered',
    'val.wrapOpen': '5 questions: not yet (optional)',
    'val.ota': 'Mock flow (demo metrics)',
    'val.lang': 'Viewing: {locale}',
    'val.private': '{n} personal elements on the room screen',
    'val.none': '—',
    'evi.default': 'Evidence tags (genre, decade, tempo, language, version) are solid; mood hypotheses are dotted “navi’s read”',
    'evi.mood': 'Heat {heat} (hypothesis). Estimated from energy and knowing; never shown to guests as a number',
    'evi.mixer': 'Mixer weights are a hypothesis (0.5 for 20 min after mixing, then 0.2)',
    'evi.card:ask': 'Evidence: only answers are counted (some people never answer, as in the simulation)',
    'evi.card:shift': 'Tested by the heat change after the insert (heat is a hypothesis)',
    'evi.card:link': 'Co-occurrence is what people picked together (demo: curated + computed), apart from tags',
    'evi.card:voice': 'A provisional wording of three impression factors; no skill or personality judgement',
    'evi.hero-ball': 'Faces rise only on real events (queued, sung, everyone knew) and never drop',
    'evi.orbs': 'Roommates’ reactions are simulated (presence, knowing, queueing)',
    'evi.card:song.visa': 'The first three per language are a serving sample (hypothesis); local titles only when verified',
    'evi.trend': '“Sung a lot this week” is sample data',
    'fut.orbs': 'Face recognition is a concept, not built; the prototype uses QR join',
    'fut.card:import': 'No real subscription link yet (demo data)',
    'fut.order': 'Not connected to real ordering (mock)',
    'fut.card:coaster': 'Not connected to real ordering (mock)',
    'fut.entry-ota': 'OTA booking and payment are mocked; nothing is really booked',
    'fut.record': 'The member-service link (base tier) is a pseudo-login',
    'fut.wrap': 'The member-service link (base tier) is a pseudo-login',
    'fut.card:voice': 'Recordings are never kept; without a mic, three questions',
    'fut.mood': 'World context (trends) is sample data',
    'fut.lang': 'To be compared in the 16 cases (4 languages × 4 tasks)',
    'fut.room-view': 'No real link to the room tablet yet (simulated on one screen)',
    'fut.card:invite': 'Sending to other phones is simulated',
    'fut.hero-ball': 'The next-visit continuation lives on this device (pseudo-login to take it home)',
    'trig.enter': 'Entered',
    'trig.refill': 'Refill',
    'trig.reserved': 'You queued',
    'trig.memberSongEnded': 'A roommate’s song ended',
    'trig.myTurnEnded': 'Your song ended',
    'trig.memberJoined': 'Someone joined',
    'trig.memberLeft': 'Someone left',
    'trig.minutes15': '15 minutes left',
    'trig.moodMixed': 'Air mixer',
    'trig.passStreak': 'Three passes',
    'trig.navMiss': 'Navi misread',
    'trig.request': 'A request arrived',
    'trig.twin': 'Hidden twin',
    'trig.coaster': 'Toast cue',
    'trig.nextVisit': 'Next visit',
    'split.title': 'Comparison split',
    'split.static': 'Self-declared (conventional)',
    'split.dynamic': 'New navi',
    'split.situation': 'Situation: {c}',
    'split.fixed': 'A fixed list chosen by companion type only',
    'split.live': 'A hand read from the room right now (reason + cause)',
    'split.nochange': 'No change',
    'split.updated': 'Updated: {cause}',
    'split.waiting': 'When the room changes, only the right side re-reads',
    'split.rereadsLabel': 're-reads',
    'split.note': 'Planning comparison (never shown to guests)',
    'comp.friends': 'Friends',
    'comp.family': 'Family',
    'comp.work': 'Work',
    'comp.date': 'Date',
    'comp.solo': 'Solo',
    'kind.song': 'Song',
    'kind.ask': 'Know it?',
    'kind.shift': 'Turning point',
    'kind.link': 'Picked together',
    'kind.voice': 'Voice',
    'kind.gap': 'Unlit area',
    'kind.invite': 'Invite',
    'kind.import': 'Bring',
    'kind.coaster': 'Toast',
    'kind.finale': 'Closing song',
    'kind.breather': 'Breather',
  },
})

export type PlannerKey = Parameters<typeof planner.t>[0]
