// M3 cards: every user-facing string of the card pile, action bar, undo toast and ghost hand.
// Namespace `cards` (SPEC G-3). Five locales, same keys and {variables} everywhere.
import { defineStrings } from '../../i18n'

export const S = defineStrings('cards', {
  ja: {
    reserve: '予約',
    keep: '気になる',
    pass: 'パス',
    later: 'あとで',
    notNow: '今はいい',
    nextTime: 'また今度',
    ask: '部屋に聞く',
    putDown: 'スマホを置いて聴く',
    oneMore: 'もう1ラウンド',
    undo: '戻す',
    linkReserve: 'つないで予約',
    counting: '開票中…',
    queuedN: '予約済み #{n}',
    finishedDemo: '歌い終わった（デモ）',

    'kind.song': '今の1曲',
    'kind.opener': '口火の1曲',
    'kind.visa': '越境の1曲',
    'kind.ask': '部屋に聞く',
    'kind.welcome': '迎える1曲',
    'kind.shift': '空気の変わり目',
    'kind.link': 'つながる',
    'kind.voice': '今夜の声',
    'kind.gap': '未踏の面',
    'kind.invite': '招待チケット',
    'kind.request': 'リクエスト便',
    'kind.twin': '二重星',
    'kind.duet': '声の相性',
    'kind.import': '持ち込み',
    'kind.coaster': '乾杯コースター',
    'kind.finale': '締めの1曲',
    'kind.breather': 'ひと息',

    askHint: '長押しで部屋に聞く',
    naviToggle: 'ナビのおすすめとして入れる',
    naviOn: 'ナビのおすすめ札つき',
    decade: '{d}年代',
    visaStamp: '越境',

    'hint.up': '予約',
    'hint.keep': 'ボールへ',
    'hint.pass': '今日はパス',
    'hint.asking': '部屋に聞いています',

    'back.why': 'なぜこの札？',
    'back.rule': 'ルール: {rule}',
    'back.evidence': '根拠',
    'back.hypothesis': 'ナビの見立て（仮説）',
    'back.versions': '歌唱版',
    'back.lang': '言語',
    'back.reservable': '予約',
    'back.canReserve': 'この店舗で予約できる',
    'back.cannotReserve': 'この店舗では配信準備中（デモ）',
    'back.key': '推奨キー',
    'back.keyValue': 'キー {k}',
    'back.keyOriginal': '原曲キー',
    'back.energy': '盛り上がり度（仮説）',
    'back.tapBack': 'タップで表に戻る',
    'source.dare': '部屋の人から',
    'source.tsunagu': 'つながりから',
    'source.yomu': '空気の読みから',
    'source.hou': '越境の歌から',
    'source.ren': 'あなたの持ち歌から',
    'source.voice': '今夜の声から',

    'ask.question': 'この曲、知ってる？',
    'ask.welcomeQ': 'みんなで迎えよう。知ってる？',
    'ask.note': '答えた人の分だけ数えます',
    'ask.mine': 'あなたは？',
    'ask.answered': '答えました',
    'ask.all': '全員が知ってる！',
    'ask.done': '開票おわり',

    'link.header': '一緒に選ばれている',
    'link.note': 'タグのおすすめとは別枠',
    'link.from': 'いま入れた曲',
    'link.tap': 'タップで選ぶ',

    'breather.round': 'このラウンド',
    'breather.faces': '面',
    'breather.facesVal': '+{n}',
    'breather.reserved': '予約',
    'breather.reservedVal': '{n}曲',
    'breather.turn': 'あなたの番まで',
    'breather.turnVal': 'あと{n}曲',
    'breather.turnNow': 'いま',
    'breather.turnNone': 'まだ',
    'breather.summary': 'このラウンド：面 +{f}／予約 {r}曲／あなたの番まで あと{t}曲',
    'breather.listen': '誰かが歌っている間は、聴く時間にしよう',

    'toast.reserved': '予約しました #{n}',
    'toast.reservedPlain': '予約しました',
    'toast.kept': 'ボールに貼りました',
    'toast.passed': 'パスしました',
    'toast.inserted': '次に挟みました',
    'toast.why': '理由を残す？（任意）',
    'toast.thanks': '次の読みに活かします',
    'passReason.unknown': '知らない曲',
    'passReason.mood': '今の空気じゃない',
    'passReason.voice': '声に合わなそう',

    'ghost.caption': '上に投げて予約',
    'aria.card': '{kind}の札。上にフリックで{primary}、左でパス、タップで裏返す',
    'aria.deck': '発見の札',
  },
  en: {
    reserve: 'Reserve',
    keep: 'Keep',
    pass: 'Pass',
    later: 'Later',
    notNow: 'Not now',
    nextTime: 'Maybe next time',
    ask: 'Ask the room',
    putDown: 'Put the phone down and listen',
    oneMore: 'One more round',
    undo: 'Undo',
    linkReserve: 'Link & reserve',
    counting: 'Counting…',
    queuedN: 'Reserved #{n}',
    finishedDemo: 'Done singing (demo)',

    'kind.song': 'Song for now',
    'kind.opener': 'First spark',
    'kind.visa': 'Crossing',
    'kind.ask': 'Ask the room',
    'kind.welcome': 'Welcome song',
    'kind.shift': 'Turning point',
    'kind.link': 'Linked',
    'kind.voice': 'Your voice tonight',
    'kind.gap': 'Uncharted faces',
    'kind.invite': 'Invitation',
    'kind.request': 'Request',
    'kind.twin': 'Twin star',
    'kind.duet': 'Voice match',
    'kind.import': 'Brought in',
    'kind.coaster': 'Toast coaster',
    'kind.finale': 'Closing song',
    'kind.breather': 'Breather',

    askHint: 'Long-press to ask the room',
    naviToggle: 'Add as a Navi pick',
    naviOn: 'With a Navi pick tag',
    decade: '{d}s',
    visaStamp: 'Crossing',

    'hint.up': 'Reserve',
    'hint.keep': 'To the ball',
    'hint.pass': 'Pass for today',
    'hint.asking': 'Asking the room',

    'back.why': 'Why this card?',
    'back.rule': 'Rule: {rule}',
    'back.evidence': 'Evidence',
    'back.hypothesis': "Navi's read (hypothesis)",
    'back.versions': 'Versions',
    'back.lang': 'Language',
    'back.reservable': 'Reserve',
    'back.canReserve': 'Available at this venue',
    'back.cannotReserve': 'Not yet available at this venue (demo)',
    'back.key': 'Suggested key',
    'back.keyValue': 'Key {k}',
    'back.keyOriginal': 'Original key',
    'back.energy': 'Energy (hypothesis)',
    'back.tapBack': 'Tap to turn back',
    'source.dare': 'From the people here',
    'source.tsunagu': 'From what goes together',
    'source.yomu': 'From reading the room',
    'source.hou': 'From songs that cross borders',
    'source.ren': 'From your own songs',
    'source.voice': 'From your voice tonight',

    'ask.question': 'Do you know this one?',
    'ask.welcomeQ': 'Welcome them in. Know it?',
    'ask.note': 'Only answers that come in are counted',
    'ask.mine': 'You?',
    'ask.answered': 'Answered',
    'ask.all': 'Everyone knows it!',
    'ask.done': 'Count finished',

    'link.header': 'Picked together',
    'link.note': 'Separate from tag picks',
    'link.from': 'Just reserved',
    'link.tap': 'Tap to choose',

    'breather.round': 'This round',
    'breather.faces': 'Faces',
    'breather.facesVal': '+{n}',
    'breather.reserved': 'Reserved',
    'breather.reservedVal': '{n} songs',
    'breather.turn': 'Your turn in',
    'breather.turnVal': '{n} songs',
    'breather.turnNow': 'Now',
    'breather.turnNone': 'Not yet',
    'breather.summary': 'This round: faces +{f} / reserved {r} / your turn in {t} songs',
    'breather.listen': 'Someone is singing. A good time to just listen',

    'toast.reserved': 'Reserved #{n}',
    'toast.reservedPlain': 'Reserved',
    'toast.kept': 'Added to your ball',
    'toast.passed': 'Passed',
    'toast.inserted': 'Slotted in next',
    'toast.why': 'Leave a reason? (optional)',
    'toast.thanks': 'Noted for the next read',
    'passReason.unknown': "Don't know it",
    'passReason.mood': 'Not the mood',
    'passReason.voice': 'Not my voice',

    'ghost.caption': 'Flick up to reserve',
    'aria.card': '{kind} card. Flick up to {primary}, left to pass, tap to flip',
    'aria.deck': 'Discovery cards',
  },
  zhHant: {
    reserve: '點歌',
    keep: '收藏',
    pass: '略過',
    later: '之後再說',
    notNow: '現在不用',
    nextTime: '下次吧',
    ask: '問問大家',
    putDown: '放下手機，好好聽',
    oneMore: '再來一輪',
    undo: '復原',
    linkReserve: '連起來點歌',
    counting: '開票中…',
    queuedN: '已點歌 #{n}',
    finishedDemo: '唱完了（示意）',

    'kind.song': '此刻的一首',
    'kind.opener': '點火的一首',
    'kind.visa': '越境的一首',
    'kind.ask': '問問大家',
    'kind.welcome': '迎接的一首',
    'kind.shift': '氣氛轉折',
    'kind.link': '串起來',
    'kind.voice': '今晚的聲音',
    'kind.gap': '未探索的面',
    'kind.invite': '邀請票',
    'kind.request': '點播信',
    'kind.twin': '雙星',
    'kind.duet': '聲音契合',
    'kind.import': '帶進來的歌',
    'kind.coaster': '乾杯杯墊',
    'kind.finale': '壓軸曲',
    'kind.breather': '喘口氣',

    askHint: '長按問問大家',
    naviToggle: '作為導航推薦加入',
    naviOn: '附導航推薦標籤',
    decade: '{d}年代',
    visaStamp: '越境',

    'hint.up': '點歌',
    'hint.keep': '貼到球上',
    'hint.pass': '今天略過',
    'hint.asking': '正在問大家',

    'back.why': '為什麼是這張？',
    'back.rule': '規則: {rule}',
    'back.evidence': '依據',
    'back.hypothesis': '導航的推測（假設）',
    'back.versions': '演唱版本',
    'back.lang': '語言',
    'back.reservable': '點歌',
    'back.canReserve': '本店可以點',
    'back.cannotReserve': '本店尚未提供（示意）',
    'back.key': '建議調性',
    'back.keyValue': '調 {k}',
    'back.keyOriginal': '原調',
    'back.energy': '熱度（假設）',
    'back.tapBack': '點一下翻回正面',
    'source.dare': '來自房間裡的人',
    'source.tsunagu': '來自常一起點的歌',
    'source.yomu': '來自對氣氛的解讀',
    'source.hou': '來自跨越國界的歌',
    'source.ren': '來自你自己的歌',
    'source.voice': '來自今晚的聲音',

    'ask.question': '這首歌，你會嗎？',
    'ask.welcomeQ': '一起歡迎吧。你會嗎？',
    'ask.note': '只計算有回答的人',
    'ask.mine': '你呢？',
    'ask.answered': '已回答',
    'ask.all': '大家都會！',
    'ask.done': '開票結束',

    'link.header': '常被一起點的歌',
    'link.note': '與標籤推薦分開',
    'link.from': '剛點的歌',
    'link.tap': '點一下選擇',

    'breather.round': '這一輪',
    'breather.faces': '面',
    'breather.facesVal': '+{n}',
    'breather.reserved': '點歌',
    'breather.reservedVal': '{n}首',
    'breather.turn': '輪到你還有',
    'breather.turnVal': '{n}首',
    'breather.turnNow': '現在',
    'breather.turnNone': '尚未',
    'breather.summary': '這一輪：面 +{f}／點歌 {r}首／再{t}首輪到你',
    'breather.listen': '有人在唱歌，好好聽吧',

    'toast.reserved': '已點歌 #{n}',
    'toast.reservedPlain': '已點歌',
    'toast.kept': '已貼到你的球上',
    'toast.passed': '已略過',
    'toast.inserted': '已插到下一首',
    'toast.why': '留下理由？（可略過）',
    'toast.thanks': '會用在下一次的推測',
    'passReason.unknown': '不認識的歌',
    'passReason.mood': '不是現在的氣氛',
    'passReason.voice': '不適合我的聲音',

    'ghost.caption': '往上丟就能點歌',
    'aria.card': '{kind}卡。往上滑{primary}，往左略過，點一下翻面',
    'aria.deck': '發現卡',
  },
  zhHans: {
    reserve: '点歌',
    keep: '收藏',
    pass: '跳过',
    later: '之后再说',
    notNow: '现在不用',
    nextTime: '下次吧',
    ask: '问问大家',
    putDown: '放下手机，好好听',
    oneMore: '再来一轮',
    undo: '撤销',
    linkReserve: '连起来点歌',
    counting: '开票中…',
    queuedN: '已点歌 #{n}',
    finishedDemo: '唱完了（示意）',

    'kind.song': '此刻的一首',
    'kind.opener': '点火的一首',
    'kind.visa': '越境的一首',
    'kind.ask': '问问大家',
    'kind.welcome': '迎接的一首',
    'kind.shift': '气氛转折',
    'kind.link': '串起来',
    'kind.voice': '今晚的声音',
    'kind.gap': '未探索的面',
    'kind.invite': '邀请票',
    'kind.request': '点播信',
    'kind.twin': '双星',
    'kind.duet': '声音契合',
    'kind.import': '带进来的歌',
    'kind.coaster': '干杯杯垫',
    'kind.finale': '压轴曲',
    'kind.breather': '喘口气',

    askHint: '长按问问大家',
    naviToggle: '作为导航推荐加入',
    naviOn: '附导航推荐标签',
    decade: '{d}年代',
    visaStamp: '越境',

    'hint.up': '点歌',
    'hint.keep': '贴到球上',
    'hint.pass': '今天跳过',
    'hint.asking': '正在问大家',

    'back.why': '为什么是这张？',
    'back.rule': '规则: {rule}',
    'back.evidence': '依据',
    'back.hypothesis': '导航的推测（假设）',
    'back.versions': '演唱版本',
    'back.lang': '语言',
    'back.reservable': '点歌',
    'back.canReserve': '本店可以点',
    'back.cannotReserve': '本店尚未提供（示意）',
    'back.key': '建议调性',
    'back.keyValue': '调 {k}',
    'back.keyOriginal': '原调',
    'back.energy': '热度（假设）',
    'back.tapBack': '点一下翻回正面',
    'source.dare': '来自房间里的人',
    'source.tsunagu': '来自常一起点的歌',
    'source.yomu': '来自对气氛的解读',
    'source.hou': '来自跨越国界的歌',
    'source.ren': '来自你自己的歌',
    'source.voice': '来自今晚的声音',

    'ask.question': '这首歌，你会吗？',
    'ask.welcomeQ': '一起欢迎吧。你会吗？',
    'ask.note': '只计算有回答的人',
    'ask.mine': '你呢？',
    'ask.answered': '已回答',
    'ask.all': '大家都会！',
    'ask.done': '开票结束',

    'link.header': '常被一起点的歌',
    'link.note': '与标签推荐分开',
    'link.from': '刚点的歌',
    'link.tap': '点一下选择',

    'breather.round': '这一轮',
    'breather.faces': '面',
    'breather.facesVal': '+{n}',
    'breather.reserved': '点歌',
    'breather.reservedVal': '{n}首',
    'breather.turn': '轮到你还有',
    'breather.turnVal': '{n}首',
    'breather.turnNow': '现在',
    'breather.turnNone': '尚未',
    'breather.summary': '这一轮：面 +{f}／点歌 {r}首／再{t}首轮到你',
    'breather.listen': '有人在唱歌，好好听吧',

    'toast.reserved': '已点歌 #{n}',
    'toast.reservedPlain': '已点歌',
    'toast.kept': '已贴到你的球上',
    'toast.passed': '已跳过',
    'toast.inserted': '已插到下一首',
    'toast.why': '留下理由？（可跳过）',
    'toast.thanks': '会用在下一次的推测',
    'passReason.unknown': '不认识的歌',
    'passReason.mood': '不是现在的气氛',
    'passReason.voice': '不适合我的声音',

    'ghost.caption': '往上丢就能点歌',
    'aria.card': '{kind}卡。往上滑{primary}，往左跳过，点一下翻面',
    'aria.deck': '发现卡',
  },
  ko: {
    reserve: '예약',
    keep: '찜하기',
    pass: '패스',
    later: '나중에',
    notNow: '지금은 괜찮아요',
    nextTime: '다음에',
    ask: '모두에게 묻기',
    putDown: '폰 내려놓고 듣기',
    oneMore: '한 라운드 더',
    undo: '되돌리기',
    linkReserve: '이어서 예약',
    counting: '집계 중…',
    queuedN: '예약됨 #{n}',
    finishedDemo: '다 불렀어요 (데모)',

    'kind.song': '지금의 한 곡',
    'kind.opener': '첫 불씨',
    'kind.visa': '국경을 넘는 한 곡',
    'kind.ask': '모두에게 묻기',
    'kind.welcome': '환영의 한 곡',
    'kind.shift': '분위기 전환',
    'kind.link': '이어지는 곡',
    'kind.voice': '오늘 밤의 목소리',
    'kind.gap': '미개척 면',
    'kind.invite': '초대 티켓',
    'kind.request': '신청곡',
    'kind.twin': '쌍둥이 별',
    'kind.duet': '목소리 궁합',
    'kind.import': '가져온 곡',
    'kind.coaster': '건배 코스터',
    'kind.finale': '마무리 곡',
    'kind.breather': '한숨 돌리기',

    askHint: '길게 눌러 모두에게 묻기',
    naviToggle: '내비 추천으로 넣기',
    naviOn: '내비 추천 태그 포함',
    decade: '{d}년대',
    visaStamp: '국경 넘기',

    'hint.up': '예약',
    'hint.keep': '볼에 붙이기',
    'hint.pass': '오늘은 패스',
    'hint.asking': '모두에게 묻는 중',

    'back.why': '왜 이 카드일까?',
    'back.rule': '규칙: {rule}',
    'back.evidence': '근거',
    'back.hypothesis': '내비의 추측 (가설)',
    'back.versions': '버전',
    'back.lang': '언어',
    'back.reservable': '예약',
    'back.canReserve': '이 매장에서 예약 가능',
    'back.cannotReserve': '이 매장에서는 준비 중 (데모)',
    'back.key': '추천 키',
    'back.keyValue': '키 {k}',
    'back.keyOriginal': '원키',
    'back.energy': '분위기 지수 (가설)',
    'back.tapBack': '탭하면 앞면으로',
    'source.dare': '방 안의 사람들로부터',
    'source.tsunagu': '함께 고른 곡들로부터',
    'source.yomu': '분위기 읽기로부터',
    'source.hou': '국경을 넘는 노래로부터',
    'source.ren': '당신의 애창곡으로부터',
    'source.voice': '오늘 밤의 목소리로부터',

    'ask.question': '이 곡, 알아요?',
    'ask.welcomeQ': '함께 환영해요. 알아요?',
    'ask.note': '대답한 사람만 셉니다',
    'ask.mine': '당신은?',
    'ask.answered': '대답했어요',
    'ask.all': '모두 알아요!',
    'ask.done': '집계 끝',

    'link.header': '함께 선택된 곡',
    'link.note': '태그 추천과는 별도',
    'link.from': '방금 넣은 곡',
    'link.tap': '탭해서 고르기',

    'breather.round': '이번 라운드',
    'breather.faces': '면',
    'breather.facesVal': '+{n}',
    'breather.reserved': '예약',
    'breather.reservedVal': '{n}곡',
    'breather.turn': '내 차례까지',
    'breather.turnVal': '{n}곡',
    'breather.turnNow': '지금',
    'breather.turnNone': '아직',
    'breather.summary': '이번 라운드: 면 +{f} / 예약 {r}곡 / {t}곡 뒤에 내 차례',
    'breather.listen': '누군가 노래하는 동안은 들어 봐요',

    'toast.reserved': '예약했어요 #{n}',
    'toast.reservedPlain': '예약했어요',
    'toast.kept': '볼에 붙였어요',
    'toast.passed': '패스했어요',
    'toast.inserted': '다음 곡으로 넣었어요',
    'toast.why': '이유를 남길까요? (선택)',
    'toast.thanks': '다음 추천에 반영할게요',
    'passReason.unknown': '모르는 곡',
    'passReason.mood': '지금 분위기가 아님',
    'passReason.voice': '목소리에 안 맞을 듯',

    'ghost.caption': '위로 던져서 예약',
    'aria.card': '{kind} 카드. 위로 밀면 {primary}, 왼쪽은 패스, 탭하면 뒤집기',
    'aria.deck': '발견 카드',
  },
})

export type CardsKey = Parameters<typeof S.t>[0]
