// M3 cards: every user-facing string of the card pile, action bar, undo toast and ghost hand.
// Namespace `cards` (SPEC G-3). Five locales, same keys and {variables} everywhere.
import { defineStrings } from '../../i18n'

export const S = defineStrings('cards', {
  ja: {
    'ask.know': '知ってる',
    'ask.chorus': 'サビだけ',
    keepBall: 'ボールにキープ',
    'budget.note': '出番待ちが{n}曲。次まで温めよう',
    'budget.note.one': '出番待ちが1曲。次まで温めよう',

    'peek.song': 'あなたに1曲',
    'peek.opener': '口火の1曲',
    'peek.visa': '海を越えた1曲',
    'peek.ask': '知ってる？',
    'peek.welcome': 'みんなで迎える',
    'peek.shift': '空気の変わり目',
    'peek.link': 'つながる3曲',
    'peek.voice': '今夜の声',
    'peek.gap': 'まだ暗いエリア',
    'peek.invite': '招待が届いた',
    'peek.request': '便りが届いた',
    'peek.requestFrom': '{name}から便り',
    'peek.twin': 'ふたつの星',
    'peek.duet': '声の相性',
    'peek.import': '持ってきた曲',
    'peek.coaster': '乾杯しよう',
    'peek.finale': '締めの1曲',
    'peek.breather': 'ひと息',

    'back.how': 'しくみ',
    'fine.ask': '答えた人の分だけ数えます。答えない人がいても大丈夫',
    'fine.link': 'タグのおすすめとは別枠。一緒に選ばれてきた曲から',
    'fine.import': 'このスマホだけに表示。自動では保存しません（選んだ曲だけ保存）。連携先は例示のデモデータです',
    'fine.request': '応えると、面に封蝋の刻印。「また今度」は相手に届きません',
    'fine.twin': 'お互いが明かしたときだけ、名前がひらきます',
    'fine.duet': '声の相性は今夜の記録から。本人以外には見えません',
    'fine.voice': '録音は保存しません。音の高さと強さを、その場で数えるだけです',
    'fine.navi': 'ナビのおすすめとして入れると、部屋の画面の予約に★が付きます',

    'breather.stats': '面 +{f} ・ 予約 {r}曲',
    'breather.turnLine': 'あなたの番まで あと{n}曲',
    'breather.turnLine.one': 'あなたの番まで あと1曲',
    'breather.turnNowLine': 'いま、あなたの番',
    'breather.turnNoneLine': 'ゆっくり聴く時間にしよう',

    reserve: '予約',
    keep: '気になる',
    pass: 'パス',
    later: 'あとで',
    notNow: '今はいい',
    nextTime: 'また今度',
    ask: '部屋に聞く',
    putDown: 'スマホを置いて聴く',
    oneMore: 'もう1ラウンド',
    undo: '戻す',
    linkReserve: 'つないで予約',
    counting: '開票中…',
    queuedN: '予約済み #{n}',

    'kind.song': '今の1曲',
    'kind.opener': '口火の1曲',
    'kind.visa': '越境の1曲',
    'kind.ask': '部屋に聞く',
    'kind.welcome': '迎える1曲',
    'kind.shift': '空気の変わり目',
    'kind.link': 'つながる',
    'kind.voice': '今夜の声',
    'kind.gap': '未踏の面',
    'kind.invite': '招待チケット',
    'kind.request': 'リクエスト便',
    'kind.twin': '二重星',
    'kind.duet': '声の相性',
    'kind.import': '持ち込み',
    'kind.coaster': '乾杯コースター',
    'kind.finale': '締めの1曲',
    'kind.breather': 'ひと息',

    askHint: '長押しで部屋に聞く',
    naviToggle: 'ナビのおすすめとして入れる',
    naviOn: 'ナビのおすすめ札つき',
    decade: '{d}年代',
    visaStamp: '越境',

    'hint.up': '予約',
    'hint.keep': 'ボールへ',
    'hint.pass': '今日はパス',
    'hint.asking': '部屋に聞いています',

    'back.why': 'なぜこの札？',
    'back.rule': 'ルール: {rule}',
    'back.evidence': '根拠',
    'back.hypothesis': 'ナビの見立て（仮説）',
    'back.versions': '歌唱版',
    'back.lang': '言語',
    'back.reservable': '予約',
    'back.canReserve': 'この店舗で予約できる',
    'back.cannotReserve': 'この店舗では配信準備中（デモ）',
    'back.key': '推奨キー',
    'back.keyValue': 'キー {k}',
    'back.keyOriginal': '原曲キー',
    'back.energy': '盛り上がり度（仮説）',
    'back.tapBack': 'タップで表に戻る',
    'source.dare': '部屋の人から',
    'source.tsunagu': 'つながりから',
    'source.yomu': '空気の読みから',
    'source.hou': '越境の歌から',
    'source.ren': 'あなたの持ち歌から',
    'source.voice': '今夜の声から',

    'ask.question': 'この曲、知ってる？',
    'ask.welcomeQ': 'みんなで迎えよう。知ってる？',
    'ask.mine': 'あなたは？',
    'ask.answered': '答えました',
    'ask.all': '全員が知ってる！',
    'ask.done': '開票おわり',

    'link.from': 'いま入れた曲',

    'breather.summary': 'このラウンド：面 +{f}／予約 {r}曲／あなたの番まで あと{t}曲',
    'breather.listen': '誰かが歌っている間は、聴く時間にしよう',

    'toast.reserved': '予約しました #{n}',
    'toast.reservedPlain': '予約しました',
    'toast.kept': 'ボールに貼りました',
    'toast.passed': 'パスしました',
    'toast.inserted': '次に挟みました',
    'toast.why': '理由は？',
    'toast.thanks': '次の読みに活かします',
    'passReason.unknown': '知らない',
    'passReason.mood': '今の空気じゃない',
    'passReason.voice': '声に合わない',

    'ghost.caption': '上に投げて予約',
    'aria.card': '{kind}の札。上にフリックで{primary}、左でパス、タップで裏返す',
    'aria.deck': '発見の札',
  },
  en: {
    'ask.know': 'Know it',
    'ask.chorus': 'Chorus only',
    keepBall: 'Keep for later',
    'budget.note': 'You have {n} songs waiting. Keep this one warm',
    'budget.note.one': 'You have 1 song waiting. Keep this one warm',

    'peek.song': 'A song for you',
    'peek.opener': 'First spark',
    'peek.visa': 'Across borders',
    'peek.ask': 'Know it?',
    'peek.welcome': 'Welcome them',
    'peek.shift': 'Turning point',
    'peek.link': '3 linked songs',
    'peek.voice': 'Your voice tonight',
    'peek.gap': 'An unlit area',
    'peek.invite': 'An invitation',
    'peek.request': 'A request!',
    'peek.requestFrom': 'Note from {name}',
    'peek.twin': 'Twin stars',
    'peek.duet': 'Voice match',
    'peek.import': 'Brought along',
    'peek.coaster': 'Cheers?',
    'peek.finale': 'Closing song',
    'peek.breather': 'Breather',

    'back.how': 'How it works',
    'fine.ask': 'Only answers are counted. Skipping is fine',
    'fine.link': 'Separate from tag picks: based on songs picked together',
    'fine.import': 'Shown only on this phone. Nothing is saved automatically (only what you pick). The service shown is demo data',
    'fine.request': 'Answering adds a wax-seal mark to the face. “Next time” is never sent to them',
    'fine.twin': 'Names show only when you both reveal',
    'fine.duet': 'Voice match is based on tonight. Only you can see it',
    'fine.voice': 'Nothing is recorded. Pitch and loudness are measured on the spot',
    'fine.navi': 'Reserve it as a Navi pick and it gets a ★ on the room screen',

    'breather.stats': 'Faces +{f} · Reserved {r}',
    'breather.turnLine': 'Your turn in {n} songs',
    'breather.turnLine.one': 'Your turn after 1 song',
    'breather.turnNowLine': 'It’s your turn now',
    'breather.turnNoneLine': 'A good moment to just listen',

    reserve: 'Reserve',
    keep: 'Keep',
    pass: 'Pass',
    later: 'Later',
    notNow: 'Not now',
    nextTime: 'Next time',
    ask: 'Ask the room',
    putDown: 'Phone down & listen',
    oneMore: 'One more round',
    undo: 'Undo',
    linkReserve: 'Link & reserve',
    counting: 'Counting…',
    queuedN: 'Reserved #{n}',

    'kind.song': 'Song for now',
    'kind.opener': 'First spark',
    'kind.visa': 'Crossing',
    'kind.ask': 'Ask the room',
    'kind.welcome': 'Welcome song',
    'kind.shift': 'Turning point',
    'kind.link': 'Linked',
    'kind.voice': 'Your voice tonight',
    'kind.gap': 'Unlit area',
    'kind.invite': 'Invitation',
    'kind.request': 'Request',
    'kind.twin': 'Twin star',
    'kind.duet': 'Voice match',
    'kind.import': 'Brought along',
    'kind.coaster': 'Toast coaster',
    'kind.finale': 'Closing song',
    'kind.breather': 'Breather',

    askHint: 'Hold to ask the room',
    naviToggle: 'Add as a Navi pick',
    naviOn: 'Tagged as a Navi pick',
    decade: '{d}s',
    visaStamp: 'Crossing',

    'hint.up': 'Reserve',
    'hint.keep': 'To the ball',
    'hint.pass': 'Not tonight',
    'hint.asking': 'Asking the room',

    'back.why': 'Why this card?',
    'back.rule': 'Rule: {rule}',
    'back.evidence': 'Evidence',
    'back.hypothesis': 'Navi’s read (hypothesis)',
    'back.versions': 'Versions',
    'back.lang': 'Language',
    'back.reservable': 'Reserve',
    'back.canReserve': 'Available at this venue',
    'back.cannotReserve': 'Not yet available at this venue (demo)',
    'back.key': 'Suggested key',
    'back.keyValue': 'Key {k}',
    'back.keyOriginal': 'Original key',
    'back.energy': 'Energy (hypothesis)',
    'back.tapBack': 'Tap to turn back',
    'source.dare': 'From the people here',
    'source.tsunagu': 'From songs picked together',
    'source.yomu': 'From reading the room',
    'source.hou': 'From songs that cross borders',
    'source.ren': 'From your own songs',
    'source.voice': 'From your voice tonight',

    'ask.question': 'Do you know this one?',
    'ask.welcomeQ': 'Welcome them in. Know it?',
    'ask.mine': 'You?',
    'ask.answered': 'Answered',
    'ask.all': 'Everyone knows it!',
    'ask.done': 'All counted',

    'link.from': 'Just reserved',

    'breather.summary': 'This round: faces +{f}, reserved {r}, songs until your turn: {t}',
    'breather.listen': 'Someone is singing. A good time to just listen',

    'toast.reserved': 'Reserved #{n}',
    'toast.reservedPlain': 'Reserved',
    'toast.kept': 'Added to your ball',
    'toast.passed': 'Passed',
    'toast.inserted': 'Slotted in next',
    'toast.why': 'Why?',
    'toast.thanks': 'Noted for the next read',
    'passReason.unknown': 'Don’t know it',
    'passReason.mood': 'Not the mood',
    'passReason.voice': 'Not my voice',

    'ghost.caption': 'Flick up to reserve',
    'aria.card': '{kind} card. Flick up to {primary}, left to pass, tap to flip',
    'aria.deck': 'Discovery cards',
  },
  zhHant: {
    'ask.know': '我會',
    'ask.chorus': '只會副歌',
    keepBall: '先貼到鏡球上',
    'budget.note': '你還有{n}首在排隊。這首先留著吧',
    'budget.note.one': '你還有1首在排隊。這首先留著吧',

    'peek.song': '給你的一首',
    'peek.opener': '點火的一首',
    'peek.visa': '跨越國界的一首',
    'peek.ask': '會唱嗎？',
    'peek.welcome': '一起歡迎',
    'peek.shift': '氣氛轉折',
    'peek.link': '串起來的3首',
    'peek.voice': '今晚的聲音',
    'peek.gap': '還沒點亮的區域',
    'peek.invite': '收到邀請',
    'peek.request': '收到點播',
    'peek.requestFrom': '來自{name}的信',
    'peek.twin': '兩顆星',
    'peek.duet': '聲音契合',
    'peek.import': '帶來的歌',
    'peek.coaster': '乾杯吧',
    'peek.finale': '壓軸曲',
    'peek.breather': '喘口氣',

    'back.how': '運作方式',
    'fine.ask': '只計算有回答的人。沒回答也沒關係',
    'fine.link': '與標籤推薦分開，依據常被一起點的紀錄',
    'fine.import': '只顯示在這支手機。不會自動儲存（只存你選的歌）。串接服務為示意資料',
    'fine.request': '回應後，面會蓋上封蠟印記。「下次吧」不會傳給對方',
    'fine.twin': '只有雙方都公開時，名字才會出現',
    'fine.duet': '聲音契合來自今晚的紀錄，只有你看得到',
    'fine.voice': '不會保存錄音，只在當下測量音高和強弱',
    'fine.navi': '以導航推薦點歌，包廂畫面上會加上★',

    'breather.stats': '面 +{f} · 點歌 {r}首',
    'breather.turnLine': '再{n}首輪到你',
    'breather.turnLine.one': '再1首輪到你',
    'breather.turnNowLine': '現在輪到你',
    'breather.turnNoneLine': '好好聽一下吧',

    reserve: '點歌',
    keep: '收藏',
    pass: '略過',
    later: '之後再說',
    notNow: '現在不用',
    nextTime: '下次吧',
    ask: '問問大家',
    putDown: '放下手機，好好聽',
    oneMore: '再來一輪',
    undo: '復原',
    linkReserve: '串起來點歌',
    counting: '開票中…',
    queuedN: '已點歌 #{n}',

    'kind.song': '此刻的一首',
    'kind.opener': '點火的一首',
    'kind.visa': '跨國的一首',
    'kind.ask': '問問大家',
    'kind.welcome': '迎接的一首',
    'kind.shift': '氣氛轉折',
    'kind.link': '串起來',
    'kind.voice': '今晚的聲音',
    'kind.gap': '未探索的面',
    'kind.invite': '邀請票',
    'kind.request': '點播信',
    'kind.twin': '雙星',
    'kind.duet': '聲音契合',
    'kind.import': '帶來的歌',
    'kind.coaster': '乾杯杯墊',
    'kind.finale': '壓軸曲',
    'kind.breather': '喘口氣',

    askHint: '長按問問大家',
    naviToggle: '以導航推薦點歌',
    naviOn: '附導航推薦標籤',
    decade: '{d}年代',
    visaStamp: '跨國',

    'hint.up': '點歌',
    'hint.keep': '貼到鏡球上',
    'hint.pass': '今晚先略過',
    'hint.asking': '正在問大家',

    'back.why': '為什麼是這張？',
    'back.rule': '規則: {rule}',
    'back.evidence': '依據',
    'back.hypothesis': '導航的推測（假設）',
    'back.versions': '演唱版本',
    'back.lang': '語言',
    'back.reservable': '點歌',
    'back.canReserve': '本店可以點',
    'back.cannotReserve': '本店尚未提供（示意）',
    'back.key': '建議調性',
    'back.keyValue': '調 {k}',
    'back.keyOriginal': '原調',
    'back.energy': '熱度（假設）',
    'back.tapBack': '點一下翻回正面',
    'source.dare': '來自包廂裡的人',
    'source.tsunagu': '來自常一起點的歌',
    'source.yomu': '來自對氣氛的解讀',
    'source.hou': '來自跨國的歌',
    'source.ren': '來自你自己的歌',
    'source.voice': '來自今晚的聲音',

    'ask.question': '這首歌，你會嗎？',
    'ask.welcomeQ': '一起歡迎吧。你會嗎？',
    'ask.mine': '你呢？',
    'ask.answered': '已回答',
    'ask.all': '大家都會！',
    'ask.done': '開票結束',

    'link.from': '剛點的歌',

    'breather.summary': '這一輪：面 +{f}／點歌 {r}首／再{t}首輪到你',
    'breather.listen': '有人在唱歌，好好聽吧',

    'toast.reserved': '已點歌 #{n}',
    'toast.reservedPlain': '已點歌',
    'toast.kept': '已貼到你的鏡球上',
    'toast.passed': '已略過',
    'toast.inserted': '已插到下一首',
    'toast.why': '為什麼？',
    'toast.thanks': '會用在下一次的推測',
    'passReason.unknown': '不認識',
    'passReason.mood': '氣氛不對',
    'passReason.voice': '不合我的聲音',

    'ghost.caption': '往上丟就能點歌',
    'aria.card': '{kind}卡。往上滑{primary}，往左略過，點一下翻面',
    'aria.deck': '發現卡',
  },
  zhHans: {
    'ask.know': '我会',
    'ask.chorus': '只会副歌',
    keepBall: '先贴到镜球上',
    'budget.note': '你还有{n}首在排队。这首先留着吧',
    'budget.note.one': '你还有1首在排队。这首先留着吧',

    'peek.song': '给你的一首',
    'peek.opener': '点火的一首',
    'peek.visa': '跨越国界的一首',
    'peek.ask': '会唱吗？',
    'peek.welcome': '一起欢迎',
    'peek.shift': '气氛转折',
    'peek.link': '串起来的3首',
    'peek.voice': '今晚的声音',
    'peek.gap': '还没点亮的区域',
    'peek.invite': '收到邀请',
    'peek.request': '收到点播',
    'peek.requestFrom': '来自{name}的信',
    'peek.twin': '两颗星',
    'peek.duet': '声音契合',
    'peek.import': '带来的歌',
    'peek.coaster': '干杯吧',
    'peek.finale': '压轴曲',
    'peek.breather': '喘口气',

    'back.how': '运作方式',
    'fine.ask': '只计算有回答的人。没回答也没关系',
    'fine.link': '与标签推荐分开，依据常被一起点的记录',
    'fine.import': '只显示在这部手机。不会自动保存（只存你选的歌）。对接服务为示意数据',
    'fine.request': '回应后，面会盖上封蜡印记。“下次吧”不会传给对方',
    'fine.twin': '只有双方都公开时，名字才会出现',
    'fine.duet': '声音契合来自今晚的记录，只有你看得到',
    'fine.voice': '不会保存录音，只在当下测量音高和强弱',
    'fine.navi': '以导航推荐点歌，包厢画面上会加上★',

    'breather.stats': '面 +{f} · 点歌 {r}首',
    'breather.turnLine': '再{n}首轮到你',
    'breather.turnLine.one': '再1首轮到你',
    'breather.turnNowLine': '现在轮到你',
    'breather.turnNoneLine': '好好听一下吧',

    reserve: '点歌',
    keep: '收藏',
    pass: '跳过',
    later: '之后再说',
    notNow: '现在不用',
    nextTime: '下次吧',
    ask: '问问大家',
    putDown: '放下手机，好好听',
    oneMore: '再来一轮',
    undo: '撤销',
    linkReserve: '串起来点歌',
    counting: '开票中…',
    queuedN: '已点歌 #{n}',

    'kind.song': '此刻的一首',
    'kind.opener': '点火的一首',
    'kind.visa': '跨国的一首',
    'kind.ask': '问问大家',
    'kind.welcome': '迎接的一首',
    'kind.shift': '气氛转折',
    'kind.link': '串起来',
    'kind.voice': '今晚的声音',
    'kind.gap': '未探索的面',
    'kind.invite': '邀请票',
    'kind.request': '点播信',
    'kind.twin': '双星',
    'kind.duet': '声音契合',
    'kind.import': '带来的歌',
    'kind.coaster': '干杯杯垫',
    'kind.finale': '压轴曲',
    'kind.breather': '喘口气',

    askHint: '长按问问大家',
    naviToggle: '以导航推荐点歌',
    naviOn: '附导航推荐标签',
    decade: '{d}年代',
    visaStamp: '跨国',

    'hint.up': '点歌',
    'hint.keep': '贴到镜球上',
    'hint.pass': '今晚先跳过',
    'hint.asking': '正在问大家',

    'back.why': '为什么是这张？',
    'back.rule': '规则: {rule}',
    'back.evidence': '依据',
    'back.hypothesis': '导航的推测（假设）',
    'back.versions': '演唱版本',
    'back.lang': '语言',
    'back.reservable': '点歌',
    'back.canReserve': '本店可以点',
    'back.cannotReserve': '本店尚未提供（示意）',
    'back.key': '建议调性',
    'back.keyValue': '调 {k}',
    'back.keyOriginal': '原调',
    'back.energy': '热度（假设）',
    'back.tapBack': '点一下翻回正面',
    'source.dare': '来自包厢里的人',
    'source.tsunagu': '来自常一起点的歌',
    'source.yomu': '来自对气氛的解读',
    'source.hou': '来自跨国的歌',
    'source.ren': '来自你自己的歌',
    'source.voice': '来自今晚的声音',

    'ask.question': '这首歌，你会吗？',
    'ask.welcomeQ': '一起欢迎吧。你会吗？',
    'ask.mine': '你呢？',
    'ask.answered': '已回答',
    'ask.all': '大家都会！',
    'ask.done': '开票结束',

    'link.from': '刚点的歌',

    'breather.summary': '这一轮：面 +{f}／点歌 {r}首／再{t}首轮到你',
    'breather.listen': '有人在唱歌，好好听吧',

    'toast.reserved': '已点歌 #{n}',
    'toast.reservedPlain': '已点歌',
    'toast.kept': '已贴到你的镜球上',
    'toast.passed': '已跳过',
    'toast.inserted': '已插到下一首',
    'toast.why': '为什么？',
    'toast.thanks': '会用在下一次的推测',
    'passReason.unknown': '不认识',
    'passReason.mood': '气氛不对',
    'passReason.voice': '不合我的声音',

    'ghost.caption': '往上丢就能点歌',
    'aria.card': '{kind}卡。往上滑{primary}，往左跳过，点一下翻面',
    'aria.deck': '发现卡',
  },
  ko: {
    'ask.know': '알아요',
    'ask.chorus': '후렴만',
    keepBall: '찜해 두기',
    'budget.note': '내 예약곡 {n}곡 대기 중. 이 곡은 아껴 둬요',
    'budget.note.one': '내 예약곡 1곡 대기 중. 이 곡은 아껴 둬요',

    'peek.song': '나를 위한 한 곡',
    'peek.opener': '첫 불씨',
    'peek.visa': '국경을 넘은 한 곡',
    'peek.ask': '알아요?',
    'peek.welcome': '함께 환영',
    'peek.shift': '분위기 전환',
    'peek.link': '이어지는 3곡',
    'peek.voice': '오늘 밤의 목소리',
    'peek.gap': '아직 어두운 영역',
    'peek.invite': '초대가 왔어요',
    'peek.request': '신청이 왔어요',
    'peek.requestFrom': '{name} 님의 편지',
    'peek.twin': '두 개의 별',
    'peek.duet': '목소리 궁합',
    'peek.import': '가져온 곡',
    'peek.coaster': '건배할까요?',
    'peek.finale': '마무리 곡',
    'peek.breather': '한숨 돌리기',

    'back.how': '작동 방식',
    'fine.ask': '대답한 사람만 세요. 대답하지 않아도 괜찮아요',
    'fine.link': '태그 추천과는 별개예요. 함께 선택된 기록을 바탕으로 해요',
    'fine.import': '이 폰에만 표시돼요. 자동으로 저장하지 않아요(고른 곡만 저장). 연동 서비스는 데모 데이터예요',
    'fine.request': '응하면 면에 봉랍 각인이 생겨요. ‘다음에’는 상대에게 전해지지 않아요',
    'fine.twin': '서로 공개했을 때만 이름이 열려요',
    'fine.duet': '목소리 궁합은 오늘 밤 기록을 바탕으로 해요. 나만 볼 수 있어요',
    'fine.voice': '녹음은 저장하지 않아요. 음높이와 세기를 그 자리에서만 재요',
    'fine.navi': '내비 추천으로 넣으면 방 화면의 예약에 ★가 붙어요',

    'breather.stats': '면 +{f} · 예약 {r}곡',
    'breather.turnLine': '내 차례까지 {n}곡',
    'breather.turnLine.one': '내 차례까지 1곡',
    'breather.turnNowLine': '지금 내 차례',
    'breather.turnNoneLine': '천천히 들어 봐요',

    reserve: '예약',
    keep: '찜하기',
    pass: '패스',
    later: '나중에',
    notNow: '이따가',
    nextTime: '다음에',
    ask: '모두에게 묻기',
    putDown: '폰 내려놓고 듣기',
    oneMore: '한 라운드 더',
    undo: '되돌리기',
    linkReserve: '이어서 예약',
    counting: '집계 중…',
    queuedN: '예약됨 #{n}',

    'kind.song': '지금의 한 곡',
    'kind.opener': '첫 불씨',
    'kind.visa': '국경을 넘은 한 곡',
    'kind.ask': '모두에게 묻기',
    'kind.welcome': '환영의 한 곡',
    'kind.shift': '분위기 전환',
    'kind.link': '이어지는 곡',
    'kind.voice': '오늘 밤의 목소리',
    'kind.gap': '미개척 면',
    'kind.invite': '초대 티켓',
    'kind.request': '신청곡',
    'kind.twin': '쌍둥이 별',
    'kind.duet': '목소리 궁합',
    'kind.import': '가져온 곡',
    'kind.coaster': '건배 코스터',
    'kind.finale': '마무리 곡',
    'kind.breather': '한숨 돌리기',

    askHint: '길게 눌러 묻기',
    naviToggle: '내비 추천으로 넣기',
    naviOn: '내비 추천 태그 붙음',
    decade: '{d}년대',
    visaStamp: '국경 넘기',

    'hint.up': '예약',
    'hint.keep': '미러볼에 붙이기',
    'hint.pass': '오늘은 패스',
    'hint.asking': '모두에게 묻는 중',

    'back.why': '왜 이 카드일까?',
    'back.rule': '규칙: {rule}',
    'back.evidence': '근거',
    'back.hypothesis': '내비의 추측 (가설)',
    'back.versions': '버전',
    'back.lang': '언어',
    'back.reservable': '예약',
    'back.canReserve': '이 매장에서 예약 가능',
    'back.cannotReserve': '이 매장에서는 준비 중 (데모)',
    'back.key': '추천 키',
    'back.keyValue': '키 {k}',
    'back.keyOriginal': '원키',
    'back.energy': '분위기 지수 (가설)',
    'back.tapBack': '탭하면 앞면으로',
    'source.dare': '함께 있는 사람들을 보고',
    'source.tsunagu': '함께 고른 곡들을 보고',
    'source.yomu': '분위기를 읽고',
    'source.hou': '국경을 넘는 노래에서',
    'source.ren': '내 애창곡에서',
    'source.voice': '오늘 밤 목소리를 보고',

    'ask.question': '이 곡, 알아요?',
    'ask.welcomeQ': '함께 환영해요. 알아요?',
    'ask.mine': '내 대답은?',
    'ask.answered': '대답했어요',
    'ask.all': '모두 알아요!',
    'ask.done': '집계 끝',

    'link.from': '방금 넣은 곡',

    'breather.summary': '이번 라운드: 면 +{f} / 예약 {r}곡 / {t}곡 뒤에 내 차례',
    'breather.listen': '누군가 노래하는 동안은 들어 봐요',

    'toast.reserved': '예약했어요 #{n}',
    'toast.reservedPlain': '예약했어요',
    'toast.kept': '미러볼에 붙였어요',
    'toast.passed': '패스했어요',
    'toast.inserted': '다음 곡으로 넣었어요',
    'toast.why': '이유는?',
    'toast.thanks': '다음 추천에 반영할게요',
    'passReason.unknown': '모르는 곡',
    'passReason.mood': '분위기 안 맞음',
    'passReason.voice': '목소리 안 맞음',

    'ghost.caption': '위로 던져서 예약',
    'aria.card': '{kind} 카드. 위로 밀면 {primary}, 왼쪽은 패스, 탭하면 뒤집기',
    'aria.deck': '발견 카드',
  },
})

export type CardsKey = Parameters<typeof S.t>[0]
